### ISSUE TITLE
Water in boats.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#100]
Water shows up in boats. Original game has some kind of "invisible square" to fix this inside of boats. Broken in re3
![image](https://user-images.githubusercontent.com/30195961/60553875-7dbee200-9d35-11e9-84b8-19945f8b9a89.png)
![image](https://user-images.githubusercontent.com/30195961/60553967-fcb41a80-9d35-11e9-98f5-32be72c0fa59.png)

**Comment by aap** [comment]
fixed by 936a8e83517fb05c34bca673140172dfa624d7b1
