### ISSUE TITLE
No sounds in main menu.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#102]
there aren't any "Main Menu" sounds, however once you load up a game or start a new game, sounds do work in pause menu.

**Comment by ShFil119** [comment]
Isn't it fixed?

**Comment by Noskillx** [comment]
it kind of is but sound is very choppy and bearly hear-able, pause menu sound is working fine tho.

**Comment by Noskillx** [comment]
fuck this, issue closed bye bye issue.
