### ISSUE TITLE
[LCS] Unable to try reLCS

### ISSUE THREAD

**Issue by ZeptoBST** [GTAmodding/re3#1027]
I am unable to try reLCS. It mentions to "Move reLCS.exe to GTA LCS directory and run it."
Problem is: What is the GTA LCS directory?
Is it the content of the PS2 or PSP iso?
Simply copying the content of either the PSP or PS2 iso into a folder then adding the executable and dll's won't work.

Do the game files need to be converted?

If so, what are the procedures?

**Comment by ZeptoBST** [comment]
For anyone who was also wondering, everything you need to know is in the Discord server.

**Comment by mrneo240** [comment]
You aren't going to share that information here?

**Comment by aap** [comment]
We don't want to link to all of the game assets publicly.

**Comment by parkerlreed** [comment]
No need to link to the assets. Just have a guide on what data files you need.

**Comment by aap** [comment]
We're not at that stage yet where the user can regenerate them themselves.
