### ISSUE TITLE
[VC] Switching antialising option starts sounds of the sea

### ISSUE THREAD

**Issue by Tomasak** [GTAmodding/re3#1030]
As weird as it sounds, if in VC on WIN64BIT d3d9 build i change aa from some quality to other and confirm it, ambient sound of ocean starts playing in menu. It thankfully disappears when i get into the game.

**Comment by erorcun** [comment]
i want to add that not just AA, also happening on changing screen resolution

**Comment by erorcun** [comment]
and weirdly this still happens. leaving a reply here to move it to the top

**Comment by Sergeanur** [comment]
Fixed
