### ISSUE TITLE
Compilation using multiple threads does not work anymore

### ISSUE THREAD

**Issue by ttyborg** [GTAmodding/re3#1032]
Hello!

I used to compile re3 on Linux using Premake, and used the "-j#" switch of make, to compile with multiple CPU threads, this significantly speeds up compilation. If I compile with only one thread, it works fine (so, without the -j#), but since commit 1b8d03f, it gives me an error message, if I use multiple threads:
```
Linking librw
==== Building re3 (release_linux-amd64-librw_gl3_glfw-oal) ====
Creating obj/linux-amd64-librw_gl3_glfw-oal/Release/re3
make[1]: *** No rule to make target '../src/extras/GitSHA1.cpp', needed by 'obj/linux-amd64-librw_gl3_glfw-oal/Release/re3/GitSHA1.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:78: re3] Error 2
```
This happens to re3 and reVC, not to reLCS, as those changes haven't been pulled into it yet.

**Comment by erorcun** [comment]
it means prebuildcommands of premake5.lua doesn't work, i suggest debugging why.

**Comment by erorcun** [comment]
now you can use it again, if you run premake with `--no-git-hash` option.

**Comment by okias** [comment]
I got hit by this issue too, maybe lets detect it and warn user + apply `--no-git-hash` option?
