### ISSUE TITLE
[VC] Blank screen (& application stalls) on startup (with CPU usage at 100%)

### ISSUE THREAD

**Issue by r2rX** [GTAmodding/re3#1033]
**Describe the bug**
When trying to start Vice City, irrespective of re3 build version, the game starts up but the screen is blank. Taking a glance at the Task Manager, it shows the CPU at 100%. On the OpenGL build, the window becomes unresponsive and I can force close the app. On the D3D9 builds, I have to force log off or reboot Windows.

**To Reproduce**
Install the retail version of Vice City (a complete install including audio from Disc 2), extract contents of re3 (applies to any pre-compiled re3 build; D3D9 MSS 32bit, D3D9 64bit or OpenGL 64bit) into the root folder and try running re3.exe.

**Expected behavior**
The game should work/launch normally.

**Screenshots**
It's just a blank, black screen

**Version**
Tested with the latest nightly builds (all versions available), running on Windows 10 x64, i7 7700HQ & NVIDIA 1070 w/ 461.40 drivers.

Note: The exact steps were replicated with GTA III (retail version), testing with all the builds, and the game loads & work fine.

Please let me know if I need to provide any further info. 👍

**Comment by hazelnot** [comment]
Wait are you trying to use re3 instead of reVC?

**Comment by r2rX** [comment]
> 
> 
> Wait are you trying to use re3 instead of reVC?

I am. As I couldn't see any links/reference to reVC builds, I assumed re3 was intended for both titles. But the fact that you asked the question seems to reveal the problem ( including some egg on my face :) ) . Is there a link to the reVC page/download section? Cheers!

**Comment by ShFil119** [comment]
https://github.com/GTAmodding/re3/tree/miami

**Comment by r2rX** [comment]
> 
> 
> https://github.com/GTAmodding/re3/tree/miami

That did it. Thank you very much for the assist!
