### ISSUE TITLE
Missing or broken strings in settings menus.

### ISSUE THREAD

**Issue by niarbeht** [GTAmodding/re3#1034]
**Describe the bug**
Some strings in the settings menus don't display correctly.

**To Reproduce**
Build re3/revc on Linux, copy files from Steam version in, fire up the game

**Expected behavior**
Settings to have user-comprehensible names.

**Screenshots**
![Weird String Bug](https://user-images.githubusercontent.com/4461717/107863157-76b7eb00-6e17-11eb-97cf-9497fa23814d.png)

**Version**
Linux 64-bit OpenGL OAL 83fdad7e

**Comment by ShFil119** [comment]
You didn't copy `gamefiles`.

**Comment by kusst** [comment]
These strings aren't available in original GXTs. Get modified GXT file from `/gamefiles/TEXT` folder in the repository.

**Comment by niarbeht** [comment]
> You didn't copy `gamefiles`.

Whoops!

Seems like the kind of thing you could just yell at the user for, though.
