### ISSUE TITLE
[III] Change default exe name (re3.exe)

### ISSUE THREAD

**Issue by lambdan** [GTAmodding/re3#1035]
**Describe the bug**
Nvidia Shadowplay thinks the game is Resident Evil 3 Remake, since the exe is called `re3.exe` and that is what the RE3 Remake's exe file is also called.

**To Reproduce**
Run `re3.exe` and capture screenshot or video using Nvidia Shadowplay. The media will appear in a Resident Evil 3 Remake folder.

**Screenshots**
![explorer_2021-02-14_00-12-40](https://user-images.githubusercontent.com/1690265/107864161-15653b80-6e5a-11eb-9c8f-5955356581e8.png)

**Solution**
Rename `re3.exe` to something else by default.  Renaming the .exe myself obviously works, so this is like the uber-low priority.

**Comment by blattersturm** [comment]
Since nothing specifies that executable names should be uniquely namespaced, isn't this on NVIDIA to use a less naive detection method?

**Comment by kusst** [comment]
Would you change your name to something else, just because there are also other people named just like you? Nonsense.

**Comment by erorcun** [comment]
we're not planning to do it, but you can always change your file name yourself..
