### ISSUE TITLE
[Error while compiling | Vice City] error C1083: Cannot open include file "rw.h"

### ISSUE THREAD

**Issue by RidgyTheFox** [GTAmodding/re3#1036]
When I try to compile the game, I get "p:\development\re3\src\fakerw\rwcore.h(5): fatal error C1083: Cannot open include file: 'rw.h': No such file or directory" error.

I select "Debug" and "win-x86-librw_d3d9-mss".
(librw Compiled successfully. That error in reVC.)

**Specs:**
My OS: Windows 10 Pro 19042.685 x64.
Microsoft Visual Studio Community 2017.
DirectX SDK 2010.

**What i do:**
I downloaded the repository using Git. (git clone https://github.com/GTAmodding/re3.git -b miami)
Installed DirectX SDK 2010.
Then i launch "premake-vs2017.cmd" file from repo root.
Opened the project, chose the platform and clicked "Compile".
I got an error saying that i don`t have Windows SDK Version 8.1. I change it to my 10.0.17763.0 in librw and reVC project settings.

After that I tried to compile and got the error.
I looked through the DirectX SDK folders and repository, but there is no such file.
Sorry, I still don't understand much about this. Am I missing a little thing?
(Maybe I need to install Windows SDK 8.1? I would do it right away, but due to the nature of my internet, I cannot download a lot. It took me a lot of time to download the current SDK. And, yes, English is not my primary language. Sorry if something is not translated correctly.)

**Comment by Sergeanur** [comment]
Clone with `git clone --recursive https://github.com/GTAmodding/re3.git -b miami`. It's submodules that you are missing.

**Comment by RidgyTheFox** [comment]
> Clone with `git clone --recursive https://github.com/GTAmodding/re3.git -b miami`. It's submodules that you are missing.

Oh.
(_I should have learned a bit more about Git._)
I'm going to try now.

**Comment by RidgyTheFox** [comment]
Yes.
It works. Thank.
(Sorry again for such nonsense.)
