### ISSUE TITLE
[Feature Request] add Dualshock 4 Button icons

### ISSUE THREAD

**Issue by Rajalolxd** [GTAmodding/re3#1038]

**Comment by Sergeanur** [comment]
What's wrong with DS3 icons?

**Comment by Rajalolxd** [comment]
> What's wrong with DS3 icons?

well nothing, i just want dualshock icons

**Comment by Sergeanur** [comment]
DS3 = DualShock 3. So, you already have those buttons.

**Comment by Rajalolxd** [comment]
> DS3 = DualShock 3. So, you already have those buttons.

Yeah ik, but how do i Change the Icons? It just shows the Xbox Buttons, does re3 have Controller autodetection?
