### ISSUE TITLE
#Interface font issues with 16:9/auto

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#104]
there is a weird font issue in between auto and 16:9, my font changes in a very weird way even tho auto is still 16:9 for me. Take a look! (Click on the Picture to see it in full screen so you'l see whats going on)
![auto](https://user-images.githubusercontent.com/30195961/60613720-c0cb9480-9dcb-11e9-9416-d9266b870030.png)
![16 9](https://user-images.githubusercontent.com/30195961/60613729-c75a0c00-9dcb-11e9-8a71-1b687503f26d.png)

**Comment by PerikiyoXD** [comment]
Maybe has to be with rendering Clamped vs Repeated texture.

**Comment by Noskillx** [comment]
FE is gone.
