### ISSUE TITLE
[Feature Request] DS4Windows support

### ISSUE THREAD

**Issue by vico93** [GTAmodding/re3#1041]
To _sightly_ expand #1038 for Windows specifically: In Windows Dualshock 4 works mainly with [DS4Windows](https://github.com/Ryochan7/DS4Windows), which also supports DualSense, Switch Pro and JoyCon support.

I'm sure is possible to detect programatically ([created a ticket on their repo to check that](https://github.com/Ryochan7/DS4Windows/issues/1871)) what device is connected (to change the button icons accordingly), plus it uses an internal UDP server to send the "extra" controls Xinput specification doesn't have (gyro and set the DualShock 4 lightbar, i think).

Plus Gyro support (via UDP) would be awesome too.

**Comment by Sergeanur** [comment]
We are planning to add DualShock 4 auto-detection the way it is done in modern games without need to emulate it as 360 pad. So far I think we're good to just switching the controller type in the menu.

**Comment by vico93** [comment]
And what about Gyro controls? Is it planned?

**Comment by Sergeanur** [comment]
You mean the sixaxis thing? I'm not what would you control with it.

**Comment by vico93** [comment]
Maybe the camera, i dont know if in GTA V that serve for anything...

**Comment by Sergeanur** [comment]
There were some things with it in IV that weren't very convenient. I don't think we'd end up utilizing it.

**Comment by vico93** [comment]
Okay then. It was just a silly question. Its sad you will not use it, since for now it also allows other devices (DualSense, JoyCon and Switch Pro Controller) to connect to Windows with all functionalities working (rumble mainly), what, at least for DualShock 4, doesn't work unless you buy a expensive addon from Sony to connect the controller with.
