### ISSUE TITLE
Overlays seem to be offset slightly

### ISSUE THREAD

**Issue by drguildo** [GTAmodding/re3#1043]
First of all, great work on this software. It's an impressive achievement.

**Describe the bug**
When playing the game at 1920x1080 with the widescreen setting set to "auto", during cutscenes there seems to be a small gap on the top and left of the screen where the black letterbox overlay is is either missing or offset wrong, so you can see what's behind it. This also seems to happen during loading screens where whatever is "behind" the loading screen causes a flickering effect.

**Screenshots**
![RE3 Border](https://user-images.githubusercontent.com/9282/107879493-fc4ba180-6ed0-11eb-9bcf-7de827e54ce1.png)

**Version**
Win 64-bit D3D9 OAL 475a4d7

**Comment by withmorten** [comment]
This is I think actually a bug with how multisampling works in D3D8/D3D9, not specifically related to this game.
