### ISSUE TITLE
Vice City / Liberty City Stories?

### ISSUE THREAD

**Issue by marczellm** [GTAmodding/re3#1044]
Would it be at all possible to bring GTA Liberty City Stories and Vice City Stories games to PC? They only came out on PlayStation and on some mobile platforms.

**Comment by kusst** [comment]
reLCS is already in the works, but it's in early stages. Check out `lcs` branch. :)
VCS is much harder to reverse, so it's not clear if reVCS will happen.

**Comment by dimiusko** [comment]
On the lcs branch, it says I can download a build "from one of the above links", but I can't seem to find any. Is there really none, or am I missing something? I am not familiar with compilation process to make one myself, sorry.

**Comment by kusst** [comment]
> 
> 
> On the lcs branch, it says I can download a build "from one of the above links", but I can't seem to find any. Is there really none, or am I missing something? I am not familiar with compilation process to make one myself, sorry.

You can get latest builds from Actions.
