### ISSUE TITLE
[III] Bug in 'Last Requests' mission; unexpected explosion blocks progress

### ISSUE THREAD

**Issue by r2rX** [GTAmodding/re3#1046]
**Describe the bug**
After starting the 'Last Requests' mission (https://gta.fandom.com/wiki/Last_Requests), the player is meant to take a (Cheetah) car to a crusher. However, the car will explode after a few seconds of entering it and thus fails the mission (thus making game progress impossible).

**To Reproduce**
Start the 'Last Requests' mission, head over to the target Cheetah car, get in and wait a second or two.

**Expected behavior**
The car shouldn't explode and allow you to progress the mission.

**Screenshots**
Link to a short video clip, with Debug version text enabled:
https://mega.nz/file/jWAhFAyA#tDz8GC5hydT-jggF_OuD7v9wW2HYBut_XhFULJwJGHA

**Comment by Sergeanur** [comment]
It's not a bug, the car is rigged, pay attention to the pager.

**Comment by r2rX** [comment]
> 
> 
> It's not a bug, the car is rigged, pay attention to the pager.

...you're absolutely right...I completely missed that and jumped the gun. Cheers for the assist.
