### ISSUE TITLE
[BUG] [III] Mouse controlling ped rotation on Skin screen

### ISSUE THREAD

**Issue by DropsMJay** [GTAmodding/re3#1047]
**Describe the bug**
Normally, the Claude model rotates on the Skins screen. The model now rotates only when the mouse is in motion.

**To Reproduce**
Just move the mouse on the Skins screen.

**Expected behavior**
Claude model rotating 360°

**Version**
OAL f372420

**Comment by DoradoOroOor** [comment]
Just change the controls to "classic" instead of "standard"

**Comment by Sergeanur** [comment]
Seems like you've got an uncapped framerate in the menu.

**Comment by DropsMJay** [comment]
No, the framerate is capped. Heres my config:

![re3_2021_02_14_17_25_32_330](https://user-images.githubusercontent.com/25830027/107888250-d1ba1280-6ee9-11eb-9e36-9a6a8d081c3b.jpg)

![re3_2021_02_14_17_25_27_100](https://user-images.githubusercontent.com/25830027/107888249-ce268b80-6ee9-11eb-91fd-0517cb6accce.jpg)

**Comment by Sergeanur** [comment]
Frame limiter only starts working when you load the game. Before that it will only be capped by vsync which you have disabled.

**Comment by DropsMJay** [comment]
Oh, I see. Sorry for the inconvenience.
