### ISSUE TITLE
Feature Request: Enable Windowed Mode

### ISSUE THREAD

**Issue by clort81** [GTAmodding/re3#1049]
**Describe the bug**
Starts in fullscreen.  Can't disable fullscreen.

**To Reproduce**
Build binary.  Run game.

**Expected behavior**
Be able to set windowed mode.

**Version**
Git Master 2021-01-14.  Linux.  aarch64.

**Comment by Tomasak** [comment]
If ini gets created at least, you can enable windowed from there.

**Comment by clort81** [comment]
Ah re3.ini is there in Game directory, 
[VideoMode]
Depth = 32
Height = 900
Subsystem = 0
Width = 1600
Windowed = 0

setting to Windowed=1 works.  Thanks.
