### ISSUE TITLE
[Linux] Main Menu works but crashes when starting game, both vc and 3

### ISSUE THREAD

**Issue by Rajalolxd** [GTAmodding/re3#1051]
[raja@localhost GTA3]$ ./re3 
[DBG]: cdvd_stream: read info 0x55caa9565c20
[DBG]: Using one streaming thread for all channels
[DBG]: Created cdstream thread
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.psInitialize:397]: gGameState = GS_START_UP
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: The previously saved language is now in use
[DBG-2]: Default skin set as no other skins are available OR saved skin not found!
[DBG]: Physical memory size 4025221120
[DBG]: Available physical memory 840343552
OpenGL version: 4.6 (Core Profile) Mesa 20.3.4
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1732]: gGameState = GS_INIT_ONCE
[ALSOFT] (EE) Failed to set real-time priority for thread: Die Operation ist nicht erlaubt (1)
[DBG]: Loadind audio cache (If game crashes around here, then your cache is corrupted, remove audio/sound.cache)
[ALSOFT] (EE) Failed to set real-time priority for thread: Die Operation ist nicht erlaubt (1)
[DBG-2]: Finding MP3s...
[DBG-2]: /media/hdd/123/GTA3\MP3\
lstat: : Datei oder Verzeichnis nicht gefunden
[DBG-2]: /media/hdd/123/GTA3\MP3\MP3Report.txt - NOT A VALID MP3
[DBG]: Initialising CTimer...
[DBG-2]: Performance counter not available, using millesecond timer

[DBG]: CTimer ready
[DBG]: Initialising CPedStats...
[DBG]: Loading pedstats data...
[DBG]: CPedStats ready
[DBG]: Intialising CTimeCycle...
[DBG]: CTimeCycle ready
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1824]: gGameState = GS_INIT_FRONTEND;
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1846]: gGameState = GS_FRONTEND;
LOAD frontend
LOAD sprite
REMOVE frontend
REMOVE menu textures
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1862]: gGameState = GS_INIT_PLAYING_GAME;
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:2013]: gGameState = GS_INIT_PLAYING_GAME;
casepath couldn't find dir/file "playback.dat", full path was playback.dat
casepath couldn't find dir/file "record.dat", full path was record.dat
[DBG]: Initialising CParticleMgr...[DBG]: Initialising CParticle...[DBG]: CParticle ready
RE3 ASSERT FAILED
        File: /home/runner/work/re3/re3/src/core/CdStreamPosix.cpp
        Line: 508
        Function: CdStreamAddImage
        Expression: false
[DBG]: Loading object types from DATA\DEFAULT.IDE ...
[DBG]: Loading texture dictionary file MODELS\MISC.TXD 
[DBG]: Loading texture dictionary file MODELS\GENERIC.TXD 
[DBG]: Loading model file MODELS\GENERIC\AIR_VLO.DFF 
[DBG]: Loading model file MODELS\GENERIC\LOPLYGUY.DFF 
[DBG]: Loading model file MODELS\GENERIC\WEAPONS.DFF 
[DBG]: Loading model file MODELS\GENERIC\WHEELS.DFF 
[DBG]: Loading collision file MODELS\COLL\VEHICLES.COL 
[DBG]: Loading collision file MODELS\COLL\WEAPONS.COL 
[DBG]: Loading object types from DATA\MAPS\generic.IDE ...
[DBG]: Loading object types from DATA\MAPS\INDUSTNE\INDUSTNE.ide ...
[DBG]: Loading object types from DATA\MAPS\INDUSTNW\INDUSTNW.ide ...
[DBG]: Loading object types from DATA\MAPS\INDUSTSE\INDUSTSE.ide ...
[DBG]: Loading object types from DATA\MAPS\INDUSTSW\INDUSTSW.ide ...
[DBG]: Loading object types from DATA\MAPS\MAKING\MAKING.ide ...
[DBG]: Loading object types from DATA\MAPS\TEMPPART\TEMPPART.ide ...
[DBG]: Loading object types from DATA\MAPS\INDROADS\INDROADS.ide ...
[DBG]: Loading object types from DATA\MAPS\COMNtop\COMNtop.ide ...
[DBG]: Loading object types from DATA\MAPS\COMNbtm\COMNbtm.ide ...
[DBG]: Loading object types from DATA\MAPS\COMSE\COMSE.ide ...
[DBG]: Loading object types from DATA\MAPS\COMSW\COMSW.ide ...
[DBG]: Loading object types from DATA\MAPS\COMROAD\COMROAD.ide ...
[DBG]: Loading object types from DATA\MAPS\LANDne\LANDne.ide ...
[DBG]: Loading object types from DATA\MAPS\LANDsw\LANDsw.ide ...
[DBG]: Loading object types from DATA\MAPS\SUBROADS\SUBROADS.ide ...
[DBG]: Loading collision file MODELS\COLL\GENERIC.COL 
[DBG]: Loading collision file DATA\MAPS\INDUSTNE\INDUSTNE.col 
[DBG]: Loading collision file DATA\MAPS\INDUSTNW\INDUSTNW.col 
[DBG]: Loading collision file DATA\MAPS\INDUSTSE\INDUSTSE.col 
[DBG]: Loading collision file DATA\MAPS\INDUSTSW\INDUSTSW.col 
[DBG]: Loading collision file DATA\MAPS\MAKING\MAKING.col 
[DBG]: Loading collision file DATA\MAPS\TEMPPART\TEMPPART.col 
[DBG]: Loading collision file DATA\MAPS\INDROADS\INDROADS.col 
[DBG]: Loading collision file DATA\MAPS\COMNtop\COMNtop.col 
[DBG]: Loading collision file DATA\MAPS\COMNbtm\COMNbtm.col 
[DBG]: Loading collision file DATA\MAPS\COMSE\COMSE.col 
[DBG]: Loading collision file DATA\MAPS\COMSW\COMSW.col 
[DBG]: Loading collision file DATA\MAPS\COMROAD\COMROAD.col 
[DBG]: Loading collision file DATA\MAPS\LANDne\LANDne.col 
[DBG]: Loading collision file DATA\MAPS\LANDsw\LANDsw.col 
[DBG]: Loading collision file DATA\MAPS\SUBROADS\SUBROADS.col 
[DBG]: Creating zones from DATA\MAP.ZON ...
[DBG]: Finished loading IPL
[DBG]: CObjectData: Cannot find object adboard1
[DBG]: CObjectData: Cannot find object taxisign
[DBG]: CObjectData: Cannot find object savecardoor
[DBG]: Creating objects from DATA\GTA3.ZON ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\COMNtop\COMNtop.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\COMNbtm\COMNbtm.IPL ...
2138:LODctm_rd4_ug txd has been set to generic
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\COMSE\COMSE.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\COMSW\COMSW.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\CULL.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\INDUSTNE\INDUSTNE.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\INDUSTNW\INDUSTNW.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\INDUSTSE\INDUSTSE.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\INDUSTSW\INDUSTSW.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\LANDne\LANDne.IPL ...
2472:LODnt7 txd has been set to generic
2474:LODnt6 txd has been set to generic
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\LANDsw\LANDsw.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\overview.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\props.IPL ...
[DBG]: Finished loading IPL
PreparePathData
Single car node: 311.002502 -938.778015 22.178200 (1817)
GraphType:0. FloodFill groups:4
GraphType:1. FloodFill groups:87
Done with PreparePathData
Done Initing waterlevels

RE3 ASSERT FAILED
        File: /home/runner/work/re3/re3/src/core/CdStreamPosix.cpp
        Line: 508
        Function: CdStreamAddImage
        Expression: false

RE3 ASSERT FAILED
        File: /home/runner/work/re3/re3/src/core/CdStreamPosix.cpp
        Line: 190
        Function: GetGTA3ImgSize
        Expression: gImgFiles[0] > 0
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by Rajalolxd** [comment]
This is my output in english:

[raja@localhost GTA3]$ export LANG=en_US.UTF-8 bash
[raja@localhost GTA3]$ ./re3 
[DBG]: cdvd_stream: read info 0x56173c4d9c20
[DBG]: Using one streaming thread for all channels
[DBG]: Created cdstream thread
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.psInitialize:397]: gGameState = GS_START_UP
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: Default skin set as no other skins are available OR saved skin not found!
[DBG]: Physical memory size 4025221120
[DBG]: Available physical memory 379002880
OpenGL version: 4.6 (Core Profile) Mesa 21.1.0-devel
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1732]: gGameState = GS_INIT_ONCE
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[DBG]: Loadind audio cache (If game crashes around here, then your cache is corrupted, remove audio/sound.cache)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[DBG-2]: Finding MP3s...
[DBG-2]: /media/hdd/123/GTA3\MP3\
lstat: : No such file or directory
[DBG-2]: /media/hdd/123/GTA3\MP3\MP3Report.txt - NOT A VALID MP3
[DBG]: Initialising CTimer...
[DBG-2]: Performance counter not available, using millesecond timer

[DBG]: CTimer ready
[DBG]: Initialising CPedStats...
[DBG]: Loading pedstats data...
[DBG]: CPedStats ready
[DBG]: Intialising CTimeCycle...
[DBG]: CTimeCycle ready
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1824]: gGameState = GS_INIT_FRONTEND;
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1846]: gGameState = GS_FRONTEND;
LOAD frontend
LOAD sprite
casepath couldn't find dir/file "GTA3sf1.b", full path was userfiles\GTA3sf1.b
casepath couldn't find dir/file "GTA3sf2.b", full path was userfiles\GTA3sf2.b
casepath couldn't find dir/file "GTA3sf3.b", full path was userfiles\GTA3sf3.b
casepath couldn't find dir/file "GTA3sf4.b", full path was userfiles\GTA3sf4.b
casepath couldn't find dir/file "GTA3sf5.b", full path was userfiles\GTA3sf5.b
casepath couldn't find dir/file "GTA3sf6.b", full path was userfiles\GTA3sf6.b
casepath couldn't find dir/file "GTA3sf7.b", full path was userfiles\GTA3sf7.b
casepath couldn't find dir/file "GTA3sf8.b", full path was userfiles\GTA3sf8.b
REMOVE frontend
REMOVE menu textures
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1862]: gGameState = GS_INIT_PLAYING_GAME;
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:2013]: gGameState = GS_INIT_PLAYING_GAME;
casepath couldn't find dir/file "playback.dat", full path was playback.dat
casepath couldn't find dir/file "record.dat", full path was record.dat
[DBG]: Initialising CParticleMgr...[DBG]: Initialising CParticle...[DBG]: CParticle ready
RE3 ASSERT FAILED
        File: /home/runner/work/re3/re3/src/core/CdStreamPosix.cpp
        Line: 508
        Function: CdStreamAddImage
        Expression: false
[DBG]: Loading object types from DATA\DEFAULT.IDE ...
[DBG]: Loading texture dictionary file MODELS\MISC.TXD 
[DBG]: Loading texture dictionary file MODELS\GENERIC.TXD 
[DBG]: Loading model file MODELS\GENERIC\AIR_VLO.DFF 
[DBG]: Loading model file MODELS\GENERIC\LOPLYGUY.DFF 
[DBG]: Loading model file MODELS\GENERIC\WEAPONS.DFF 
[DBG]: Loading model file MODELS\GENERIC\WHEELS.DFF 
[DBG]: Loading collision file MODELS\COLL\VEHICLES.COL 
[DBG]: Loading collision file MODELS\COLL\WEAPONS.COL 
[DBG]: Loading object types from DATA\MAPS\generic.IDE ...
[DBG]: Loading object types from DATA\MAPS\INDUSTNE\INDUSTNE.ide ...
[DBG]: Loading object types from DATA\MAPS\INDUSTNW\INDUSTNW.ide ...
[DBG]: Loading object types from DATA\MAPS\INDUSTSE\INDUSTSE.ide ...
[DBG]: Loading object types from DATA\MAPS\INDUSTSW\INDUSTSW.ide ...
[DBG]: Loading object types from DATA\MAPS\MAKING\MAKING.ide ...
[DBG]: Loading object types from DATA\MAPS\TEMPPART\TEMPPART.ide ...
[DBG]: Loading object types from DATA\MAPS\INDROADS\INDROADS.ide ...
[DBG]: Loading object types from DATA\MAPS\COMNtop\COMNtop.ide ...
[DBG]: Loading object types from DATA\MAPS\COMNbtm\COMNbtm.ide ...
[DBG]: Loading object types from DATA\MAPS\COMSE\COMSE.ide ...
[DBG]: Loading object types from DATA\MAPS\COMSW\COMSW.ide ...
[DBG]: Loading object types from DATA\MAPS\COMROAD\COMROAD.ide ...
[DBG]: Loading object types from DATA\MAPS\LANDne\LANDne.ide ...
[DBG]: Loading object types from DATA\MAPS\LANDsw\LANDsw.ide ...
[DBG]: Loading object types from DATA\MAPS\SUBROADS\SUBROADS.ide ...
[DBG]: Loading collision file MODELS\COLL\GENERIC.COL 
[DBG]: Loading collision file DATA\MAPS\INDUSTNE\INDUSTNE.col 
[DBG]: Loading collision file DATA\MAPS\INDUSTNW\INDUSTNW.col 
[DBG]: Loading collision file DATA\MAPS\INDUSTSE\INDUSTSE.col 
[DBG]: Loading collision file DATA\MAPS\INDUSTSW\INDUSTSW.col 
[DBG]: Loading collision file DATA\MAPS\MAKING\MAKING.col 
[DBG]: Loading collision file DATA\MAPS\TEMPPART\TEMPPART.col 
[DBG]: Loading collision file DATA\MAPS\INDROADS\INDROADS.col 
[DBG]: Loading collision file DATA\MAPS\COMNtop\COMNtop.col 
[DBG]: Loading collision file DATA\MAPS\COMNbtm\COMNbtm.col 
[DBG]: Loading collision file DATA\MAPS\COMSE\COMSE.col 
[DBG]: Loading collision file DATA\MAPS\COMSW\COMSW.col 
[DBG]: Loading collision file DATA\MAPS\COMROAD\COMROAD.col 
[DBG]: Loading collision file DATA\MAPS\LANDne\LANDne.col 
[DBG]: Loading collision file DATA\MAPS\LANDsw\LANDsw.col 
[DBG]: Loading collision file DATA\MAPS\SUBROADS\SUBROADS.col 
[DBG]: Creating zones from DATA\MAP.ZON ...
[DBG]: Finished loading IPL
[DBG]: CObjectData: Cannot find object adboard1
[DBG]: CObjectData: Cannot find object taxisign
[DBG]: CObjectData: Cannot find object savecardoor
[DBG]: Creating objects from DATA\GTA3.ZON ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\COMNtop\COMNtop.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\COMNbtm\COMNbtm.IPL ...
2138:LODctm_rd4_ug txd has been set to generic
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\COMSE\COMSE.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\COMSW\COMSW.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\CULL.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\INDUSTNE\INDUSTNE.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\INDUSTNW\INDUSTNW.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\INDUSTSE\INDUSTSE.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\INDUSTSW\INDUSTSW.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\LANDne\LANDne.IPL ...
2472:LODnt7 txd has been set to generic
2474:LODnt6 txd has been set to generic
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\LANDsw\LANDsw.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\overview.IPL ...
[DBG]: Finished loading IPL
[DBG]: Creating objects from DATA\MAPS\props.IPL ...
[DBG]: Finished loading IPL
PreparePathData
Single car node: 311.002502 -938.778015 22.178200 (1817)
GraphType:0. FloodFill groups:4
GraphType:1. FloodFill groups:87
Done with PreparePathData
Done Initing waterlevels

RE3 ASSERT FAILED
        File: /home/runner/work/re3/re3/src/core/CdStreamPosix.cpp
        Line: 508
        Function: CdStreamAddImage
        Expression: false

RE3 ASSERT FAILED
        File: /home/runner/work/re3/re3/src/core/CdStreamPosix.cpp
        Line: 190
        Function: GetGTA3ImgSize
        Expression: gImgFiles[0] > 0
Segmentation fault (core dumped)

**Comment by aap** [comment]
There's something wrong about your cdimages. Looks like it couldn't open gta3.img or maybe txd.img?

**Comment by Rajalolxd** [comment]
turned out that i didnt have correct/enough permission or whatever, i just did **chown -R raja:raja /media/hdd** , works fine now
