### ISSUE TITLE
[BUG] [III] Vibration continues on pause menu

### ISSUE THREAD

**Issue by DropsMJay** [GTAmodding/re3#1053]
**Describe the bug**
If the game is paused when the controller is vibrating, it will not stop when the game is paused.

**To Reproduce**
Pause the game when the controller is vibrating.

**Expected behavior**
Vibration stops after the game is paused.

**Version**
OAL f372420

**Comment by DemetriusXXX** [comment]
There is such a problem. You also need to adjust the vibration strength in the settings. She's very strong now.

**Comment by Sergeanur** [comment]
Fixed.
