### ISSUE TITLE
[Linux] VC and 3 cant loads forever/doesnt load 

### ISSUE THREAD

**Issue by Rajalolxd** [GTAmodding/re3#1054]
when starting after deleting re3.ini/revc.ini you can load into the game fine, but when a mission or whatever is loading, it shows the  loading screen and stucks

last line of my terminal output just says:

Start loading oceanic
Finish loading oceanic

**Comment by erorcun** [comment]
Which build? OS? And backtrace/stacktrace please (using gdb, since probably you're on linux/unix)

**Comment by Rajalolxd** [comment]
Latest Linux build
i'm using fedora
how do i get a backtrace/stacktrace with gdb?

**Comment by erorcun** [comment]
> how do i get a backtrace/stacktrace with gdb?
you can search on internet

**Comment by aap** [comment]
bt
