### ISSUE TITLE
[Linux] No audio hardware in both re3 and reVC

### ISSUE THREAD

**Issue by deennyy** [GTAmodding/re3#1055]
Console log from re3:
[DBG]: cdvd_stream: read info 0x55ec36c4cc20
[DBG]: Using one streaming thread for all channels
[DBG]: Created cdstream thread
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.psInitialize:397]: gGameState = GS_START_UP
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: Default skin set as no other skins are available OR saved skin not found!
[DBG]: Physical memory size 3898544128
[DBG]: Available physical memory 560746496
OpenGL version: 3.3.0 NVIDIA 460.39
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1732]: gGameState = GS_INIT_ONCE
[DBG]: Loadind audio cache (If game crashes around here, then your cache is corrupted, remove audio/sound.cache)
[DBG]: Initialising CTimer...
[DBG-2]: Performance counter not available, using millesecond timer

[DBG]: CTimer ready
[DBG]: Initialising CPedStats...
[DBG]: Loading pedstats data...
[DBG]: CPedStats ready
[DBG]: Intialising CTimeCycle...
[DBG]: CTimeCycle ready
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1824]: gGameState = GS_INIT_FRONTEND;
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1846]: gGameState = GS_FRONTEND;
LOAD frontend
LOAD sprite
REMOVE frontend
REMOVE menu textures
Tex still allocated: 1 mapMid01 
[DBG]: Shutting down CPedStats...
[DBG]: CPedStats shut down

Console log from reVC:
[DBG]: cdvd_stream: read info 0x5599da2d1020
[DBG]: Using one streaming thread for all channels
[DBG]: size of matrix 80
[DBG]: size of placeable 80
[DBG]: size of entity 120
[DBG]: size of building 120
[DBG]: size of dummy 128
[DBG]: Created cdstream thread
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.psInitialize:396]: gGameState = GS_START_UP
casepath couldn't find dir/file "gta_vc.set", full path was gta_vc.set
[DBG-2]: Default skin set as no other skins are available OR saved skin not found!
[DBG]: Physical memory size 3898544128
[DBG]: Available physical memory 599998464
OpenGL version: 3.3.0 NVIDIA 460.39
casepath couldn't find dir/file "gta_vc.set", full path was gta_vc.set
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1764]: gGameState = GS_INIT_ONCE
[DBG]: Initialising CTimer...
[DBG-2]: Performance counter not available, using millesecond timer

[DBG]: CTimer ready
[DBG]: Initialising CPedStats...
[DBG]: Loading pedstats data...
[DBG]: CPedStats ready
[DBG]: Intialising CTimeCycle...
[DBG]: CTimeCycle ready
[DBG]: Loadind audio cache (If game crashes around here, then your cache is corrupted, remove audio/sound.cache)
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1857]: gGameState = GS_INIT_FRONTEND;
[DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.main:1879]: gGameState = GS_FRONTEND;
casepath couldn't find dir/file "GTAVCsf1.b", full path was userfiles\GTAVCsf1.b
casepath couldn't find dir/file "GTAVCsf2.b", full path was userfiles\GTAVCsf2.b
casepath couldn't find dir/file "GTAVCsf3.b", full path was userfiles\GTAVCsf3.b
casepath couldn't find dir/file "GTAVCsf4.b", full path was userfiles\GTAVCsf4.b
casepath couldn't find dir/file "GTAVCsf5.b", full path was userfiles\GTAVCsf5.b
casepath couldn't find dir/file "GTAVCsf6.b", full path was userfiles\GTAVCsf6.b
casepath couldn't find dir/file "GTAVCsf7.b", full path was userfiles\GTAVCsf7.b
casepath couldn't find dir/file "GTAVCsf8.b", full path was userfiles\GTAVCsf8.b
LOAD frontend1
LOAD frontend2
REMOVE frontend
[DBG]: Shutting down CPedStats...
[DBG]: CPedStats shut down

Additional info:
I'm on Arch, with pulseaudio and pulseaudio-alsa installed, I'm also using a wireless USB headset, so maybe that could be an issue, but audio works in all other programs and games.

I've tried renaming the folder from Audio to audio, that didn't fix it.

**Comment by ShFil119** [comment]
Have you used steam versions of games?

**Comment by deennyy** [comment]
No, ripped from retail disks

**Comment by ShFil119** [comment]
You probably need to copy files from second disk into your gta 3/vc folder.

**Comment by Sergeanur** [comment]
This issue is usually happening if the game can't find sfx.raw and/or sfx.sdt in audio directory.

**Comment by deennyy** [comment]
sfx.raw and sfx.sdt are both in the audio directory, also tried running the exes in wine, they didnt launch, but i got some errors which might be helpful?

![image](https://user-images.githubusercontent.com/70910384/107888041-f24a9280-6f12-11eb-8ea4-604c9bc6e264.png)

**Comment by ShFil119** [comment]
Please show catalog in which you put binary.

**Comment by deennyy** [comment]
catalog? you mean folder?

**Comment by ShFil119** [comment]
ah, yes

**Comment by deennyy** [comment]
![image](https://user-images.githubusercontent.com/70910384/107888424-cdefb580-6f14-11eb-9a31-403c20998c57.png)

**Comment by erorcun** [comment]
this is caused by either wrong permissions, or missing files, or incompatible sound drivers. Case sensitivity isn't a problem here, we already handle it. I fear there is nothing we can do.
