### ISSUE TITLE
Crash with Creative OpenAL installed

### ISSUE THREAD

**Issue by sherief** [GTAmodding/re3#1056]
**Describe the bug**
On machines with a non-OpenAL Soft DLL in the search path (in my case, the Creative OpenAL DLL in System32. Don't ask me how.) ReVC crashes on launch.

The assertion in sampman_oal.cpp:300 `ASSERT(strstr(ext,"AL_SOFT_loop_points")!=NULL);` fires, since this extension is only in OpenAL Soft builds.

**To Reproduce**
Launch ReVC x64 with a non-OpenAL Soft DLL

**Expected behavior**
Gracefully fail, or warn the user explaining the issue.

**Screenshots**
N/A

**Version**
commit e604be65d9b7845ee7ca975545fc9277c662bc11

**Comment by erorcun** [comment]
You have OpenAL32.dll on your GTA root dir isn't it?

**Comment by kusst** [comment]
Just use OpenAL-Soft. It's better than Creative's implementation and more up-to-date.

**Comment by sherief** [comment]
@erorcun with an install from the original discs, OpenAL wasn't included (it used Miles), and this was a 64 bit build on Windows. 
@kusst That is what I did, I'm familiar with OpenAL soft - I just think other people with less technical skills might run into this.

An error message would be nice, or the DLL search path can be adjusted to require loading it from the current working directory. Many people out there have non-OpenAL Soft DLLs in the PATH. I wouldn't mind doing the work for this at all, just let me know what fits best with the project and its multiple platforms.

**Comment by erorcun** [comment]
man, we have OpenAL32.dll in prebuilt packages, that's why it's there. it's also explained in the link at the bottom of Building section.

**Comment by sherief** [comment]
Okay so this is just something that I ran into due to building from source, no worries then - if you're building from source you should be able to figure this one out. Thanks for the help, and thanks for the great project - I'm so happy to be able to play a well-behaving game of Vice City again on a modern PC!
