### ISSUE TITLE
Radio Stations don't load in (Likely first boot issue)

### ISSUE THREAD

**Issue by chrishazfun** [GTAmodding/re3#1059]
**Describe the bug**
Stations don't seem to load in after the transitional audio cue when scrolling, likely a first boot issue as the next time I loaded 3 and VC they were working fine.

**To Reproduce**
Enter vehicle that has radio function, change radio station.

**Expected behavior**
After transitional audio cue, nothing comes up even though the station says it's on.

**Version**
Win 64-bit D3D9 OAL 49d9aa8

**Comment by chrishazfun** [comment]
Update: Reloaded and it seems to stop loading now, might be after I used the mod menu but it was happening beforehand too.

**Comment by erorcun** [comment]
I think 5ce5000 fixed it, but I can never be sure. Please try latest build

**Comment by erorcun** [comment]
Should be fixed
