### ISSUE TITLE
[BUG] [VC] Missing SUBTITLES during Cutscenes (ITALIAN)

### ISSUE THREAD

**Issue by PhilRoll** [GTAmodding/re3#1061]
I'm on version 1.0

The game in Italian doesn't have any subtitles during the cutscenes (despite the subtitle option being on), and sometimes also some dialogue after a cutscene doesn't have subtitles.
Plz fix it!

**Comment by Sergeanur** [comment]
Sounds like you might be using gxt from III. Grab VC one in here https://github.com/GTAmodding/re3/raw/miami/gamefiles/TEXT/italian.gxt

**Comment by PhilRoll** [comment]
thanks, now italian subtitles seems works!
