### ISSUE TITLE
Can't compile vertex shader on ARM device

### ISSUE THREAD

**Issue by gamelaster** [GTAmodding/re3#1064]
- re3 version: tags/re3_v1.0 - Debug
- OS: Debian 10
- Architecture: aarch64 kernel, armhf rootfs
- GLFW Version: master (compiled by myself)

It fails to compile vertex shader, check log. I'm not sure if this can be because of using master version of GLFW, but it shouldn't happen.

[log.txt](https://github.com/GTAmodding/re3/files/5981863/log.txt)

// EDIT: I find out release version launches, but crashes after loading

**Comment by blattersturm** [comment]
> LIBGL: Using GLES 2.0 backend
> LIBGL: loaded: libbrcmGLESv2.so

I'm assuming this is an RPi?

**Comment by gamelaster** [comment]
@blattersturm no, it's RK3399 based device. Actually interesting it uses this library.

**Comment by aap** [comment]
the shaders are using f suffixes. just a C habit that snuck into the shader source. i'll fix it in a sec.

**Comment by gamelaster** [comment]
Yep, that's fixes it, thanks.
