### ISSUE TITLE
[III] Game hangs when shooting down helicopter on mission "S.A.M."

### ISSUE THREAD

**Issue by jay-m-z** [GTAmodding/re3#1067]
Game stops responding on mission "S.A.M." after shooting down the police helicopter that appears after getting 4* wanted level. It seems to happen as it is hitting the ground, tried it a few times and it is 100% reproducible.

Police helicopters outside of this mission can be shot down without problems.

Version: Win 32-bit D3D9 MSS 475a4d7

Attached savefile is saved just before that mission.
[GTA3sf1.b.zip](https://github.com/GTAmodding/re3/files/5983179/GTA3sf1.b.zip)

PS. Just finished the game and it was much more stable and complete than I expected. Great job!

**Comment by Sergeanur** [comment]
Did you play with frame limiter off?

**Comment by erorcun** [comment]
Can't reproduce. Might be fixed along the way and/or be related with frame limiter.
