### ISSUE TITLE
[VC] Segfault when trying to ride toy vehicles

### ISSUE THREAD

**Issue by xTibor** [GTAmodding/re3#1068]
**Reproduction:**

Spawn any of the toy vehicles (RC Bandit / RC Baron / RC Raider / RC Goblin) with the debug menu and try to ride them. Tommy may waltz around the vehicles for a while before finding a door and segfaulting the game.

**Version:**

* Git commit: 5ce5000b149e8df4151b758e42d0b39e1055b5e7
* OS: KDE neon 5.20 (Ubuntu 20.04 LTS)
* CMake flags: `-DLIBRW_PLATFORM=GL3 -DLIBRW_GL3_GFXLIB=GLFW -DCMAKE_BUILD_TYPE=Debug`
* Game assets: Steam version

**Backtrace:**

```
#0  0x00005555556880ec in CVector::CVector (this=0x7fffffffd54c, v=...) at /home/user/git/re3/src/math/Vector.h:16
#1  0x0000555555757557 in CMatrix::Update (this=0x7fffffffd610) at /home/user/git/re3/src/math/Matrix.cpp:63
#2  0x000055555575746b in CMatrix::Attach (this=0x7fffffffd610, matrix=0x30, owner=false) at /home/user/git/re3/src/math/Matrix.cpp:39
#3  0x00005555557573c6 in CMatrix::CMatrix (this=0x7fffffffd610, matrix=0x30, owner=false) at /home/user/git/re3/src/math/Matrix.cpp:19
#4  0x000055555589edfc in CAutomobile::OpenDoor (this=0x5555570d6880, component=15, door=DOOR_FRONT_LEFT, openRatio=0.0672514886) at /home/user/git/re3/src/vehicles/Automobile.cpp:4556
#5  0x00005555558a4db4 in ProcessDoorOpenAnimation (car=0x5555570d6880, component=15, door=DOOR_FRONT_LEFT, time=0.44228071, start=0.409999996, end=0.889999986) at /home/user/git/re3/src/vehicles/Automobile.cpp:4596
#6  0x000055555589f2ab in CAutomobile::ProcessOpenDoor (this=0x5555570d6880, component=15, anim=76, time=0.44228071) at /home/user/git/re3/src/vehicles/Automobile.cpp:4650
#7  0x00005555557b2e6b in CPed::EnterCar (this=0x5555583146e0) at /home/user/git/re3/src/peds/PedAI.cpp:4008
#8  0x000055555571a82c in CWorld::Process () at /home/user/git/re3/src/core/World.cpp:2066
#9  0x00005555556e1e59 in CGame::Process () at /home/user/git/re3/src/core/Game.cpp:915
#10 0x000055555572395d in Idle (arg=0x1) at /home/user/git/re3/src/core/main.cpp:1509
#11 0x0000555555724003 in AppEventHandler (event=rsIDLE, param=0x1) at /home/user/git/re3/src/core/main.cpp:1753
#12 0x000055555587b6a4 in RsEventHandler (event=rsIDLE, param=0x1) at /home/user/git/re3/src/skel/skeleton.cpp:210
#13 0x000055555587ac39 in main (argc=1, argv=0x7fffffffdb78) at /home/user/git/re3/src/skel/glfw/glfw.cpp:1953
```

**Comment by ozz-is-here** [comment]
As far as I know, this bug(?) is from the original version of the game. If you spawn any of RC vehicles in the original game and will try to ride them, the game will crash. 

https://gta.fandom.com/wiki/RC_Bandit

>If the player spawns the vehicle in GTA III and GTA Vice City and attempts to enter it, the game will crash as soon as the player opens the "door". In GTA San Andreas, however, if the player tries to enter it, nothing will happen. But, in GTA Liberty City Stories, the player can normally enter it and drive it around, however, on the PSP version the player has to teleport inside the RC car, otherwise the game will crash.
