### ISSUE TITLE
[Request] Multiplayer functionality from Multi Theft Auto

### ISSUE THREAD

**Issue by Thrilleratplay** [GTAmodding/re3#1069]
This is outside of the scope of reverse engineering GTA but I wanted to at least suggest incorporating networked multiplayer functionality from the [MTA project](https://github.com/multitheftauto).  Given that Multi Theft Auto works by hooking into the original game engine, the source may provide some useful information in the core RE3 efforts.

**Comment by asm95** [comment]
Multiplayer was part of PSP version both GTA Stories games, so it's not conceptually wrong to reverse this component in the future. All we need is someone interested in doing it so. Adding something similar to MTA will **never** happen in the main repository as the hole propose of this project is to maintain the code as original as possible with some improvements for modern hardware.

**Comment by kusst** [comment]
> 
> 
> Adding something similar to MTA will **never** happen in the main repository as the hole propose of this project is to maintain the code as original as possible with some improvements for modern hardware.

Pretty much this. Anyone is free to fork re3/VC, add multiplayer functionality to it and maintain it as a separate project.

**Comment by testman42** [comment]
If someone wants to investigate multiplayer further, there was a project called Liberty Unleashed that implemented multiplayer in GTA 3
[Website](https://liberty-unleashed.co.uk/)
[GTAGarage](https://www.gtagarage.com/mods/show.php?id=27489)

**Comment by erorcun** [comment]
We are not planning to do it, but it's a nice fork idea.
