### ISSUE TITLE
closedir(NULL) is undefined behaviour

### ISSUE THREAD

**Issue by brynet** [GTAmodding/re3#1072]
The Win32 API function "FindClose" is a wrapper around closedir(3) when building on POSIX platforms. There are a few places where it gets called with NULL (or INVALID_HANDLE_VALUE) which is undefined behaviour. This causes a crash on certain platforms, at least with reVC.

As this may apply to multiple branches I'm attaching it here inline as a patch, hopefully that's not too inconvenient. All other uses of FindCose appear to do this check correctly.

```
diff --git a/src/core/Frontend.cpp b/src/core/Frontend.cpp
index 861e67d1..ee67bd70 100644
--- a/src/core/Frontend.cpp
+++ b/src/core/Frontend.cpp
@@ -2502,7 +2502,8 @@ CMenuManager::DrawPlayerSetupScreen(bool activeScreen)
 				m_pSelectedSkin->nextSkin = nil;
 			}
 		}
-		FindClose(handle);
+		if (handle != INVALID_HANDLE_VALUE)
+			FindClose(handle);
 		m_nSkinsTotal = nextSkinId;
 		char nameTemp[256];
 		for (m_pSelectedSkin = m_pSkinListHead.nextSkin; m_pSelectedSkin; m_pSelectedSkin = m_pSelectedSkin->nextSkin) {
@@ -3137,7 +3138,8 @@ CMenuManager::LoadSettings()
 		if (strcmp(FindFileData.cFileName, skinfile) == 0)
 			SkinFound = true;
 	}
-	FindClose(handle);
+	if (handle != INVALID_HANDLE_VALUE)
+		FindClose(handle);
 
 	if (!SkinFound) {
 		OutputDebugString("Default skin set as no other skins are available OR saved skin not found!");
```

**Comment by erorcun** [comment]
thanks for the report, but all of our code is actually reversed code from original binaries, so we don't do/accept changes like that, and we've just changed our Contributing section and PR template according to that.

so I'll have to fix this in compatilibity layer; crossplatform.h/.cpp. Thanks again :)
