### ISSUE TITLE
Some keyboard keys dont work (escape, right control, space bar)

### ISSUE THREAD

**Issue by mrdeathjr28** [GTAmodding/re3#1073]
**Describe the bug**

Some keyboard keys dont work (escape, right control, space bar)

**To Reproduce**

before cited keys dont work in game, on main menu only work mouse input

**Expected behavior**
keyboard buttons must be run without troubles

**Version**
https://github.com/GTAmodding/re3/releases/tag/reVC_1.0

**Comment by cosmincrihan** [comment]
I confirm this bug affects both VC and GTA 3 versions, on Debian 10.8 amd64.

**Comment by hjri** [comment]
this happens sometimes to me too

**Comment by erorcun** [comment]
Let's look what PR template says:
> **Version**
Tell us what version you're running. Find out using the debug menu (Ctrl-M, Debug -> Version Text)
If you send a screenshot just enable it beforehand.

There is a reason we wrote that. I would ignore this issue if second comment wouldn't have said it's on Linux. Anyway, investigating it.

**Comment by hjri** [comment]
Well, for a long time debug menu just didn't open up for me, and if Ctrl button doesn't work you can't open it up at all.

`Linux 64-bit OpenGL OAL e604be65`

This doesn't always happen and might be related to XCB/IME settings or some key getting stuck like Alt due to Alt-tabbing.

**Comment by erorcun** [comment]
GLFW's input handling was buggy in last several years and I think that's the reason. I see no mistake on our code tbh, it's pretty straightforward and all keys are handled same. So I'll try fetching keys from X11 itself soon, I hope it will fix those bugs.

**Comment by erorcun** [comment]
ok, done. can you try again?

**Comment by mrdeathjr28** [comment]
yeah i can try but in my system dont allow compile

**Comment by erorcun** [comment]
just download the latest build

**Comment by mrdeathjr28** [comment]
> just download the latest build

many thanks dowloaded lastest re3 and revc and keybord works normally (esc for main menu and space key working correctly)
