### ISSUE TITLE
VC: Please help this russian localization

### ISSUE THREAD

**Issue by once13one** [GTAmodding/re3#1079]
reVC-vita, version 1.0 and PC-version (Windows).
datafiles from Steam.

When installing files american.dxt (or other name) whis russian text (Soft Club), and font.txd - all fonts, letters, and more items are merging.
In original version on game needed edit *.exe to replace symbol table for letters
For PSV this method doesn't work, because dont't have a executable files (expectedly) and don't use fonts.dat / *.asi loader

Please help change table in font.cpp for russian language or add new position for this lang with normal fonts table. We don't have any idea how fix this.
Thanks!

Example files with russian lang.
[example.zip](https://github.com/GTAmodding/re3/files/5987500/example.zip)
Font (texture):
[font bmp-alpha.zip](https://github.com/GTAmodding/re3/files/5988857/font.bmp-alpha.zip)

Screenshots from PC (reVC):
![1](https://user-images.githubusercontent.com/48656797/108044515-6ab86d00-7053-11eb-91a4-3ce7cd184ba0.jpg)
![2](https://user-images.githubusercontent.com/48656797/108044545-72781180-7053-11eb-86e4-2c83a633c0b0.jpg)
![3](https://user-images.githubusercontent.com/48656797/108044566-773cc580-7053-11eb-8cf0-a43335ff03c7.jpg)
![4](https://user-images.githubusercontent.com/48656797/108044580-7c017980-7053-11eb-8f12-0cc698cd5f61.jpg)

Screenshots from PSV (reVC-vita):
![2021-02-16-115050](https://user-images.githubusercontent.com/48656797/108044626-92a7d080-7053-11eb-8533-5c32ccf07a9d.jpg)
![2021-02-16-115101](https://user-images.githubusercontent.com/48656797/108044646-989db180-7053-11eb-916f-ffacc6bd47da.jpg)
![2021-02-16-115137](https://user-images.githubusercontent.com/48656797/108044664-9cc9cf00-7053-11eb-9e27-3f21f79882ac.jpg)
![2021-02-16-115213](https://user-images.githubusercontent.com/48656797/108044677-a0f5ec80-7053-11eb-8491-026dde8aa20a.jpg)

**Comment by Yoti** [comment]
```
# @generator	VCFCTool10 v0.1b
# @date  	2013/02/17 00:43:24
# @fonts 	2

# Font 0 (Pricedown)

# proportional values:
15   7  31  25  20  23  21   7    # 0   
11  10  26  14   6  12   6  26    # 8   
20   7  20  20  21  20  20  19    # 16  
21  20   8  30  24  30  24  19    # 24  
20  22  22  21  22  18  18  22    # 32  
22   9  14  21  18  27  21  24    # 40  
22  22  23  20  19  23  22  31    # 48  
23  23  21  25  13  30  10  19    # 56  
10  17  17  16  17  17  11  17    # 64  
17   7   7  18   7  25  17  17    # 72  
17  17  11  17  11  17  18  25    # 80  
19  18  17  28  26  20  15  15    # 88  
20  20  20  20  29  22  19  19    # 96  
19  19   9   9   9   9  23  23    # 104 
23  23  24  24  24  24  20  19    # 112 
17  17  17  30  16  17  17  17    # 120 
17  11  11  15  12  17  17  17    # 128 
17  17  17  17  17  19  20  20    # 136 
20  18  19  19  21  19  19  19    # 144 
19  19  16  19  19  19  20  19    # 152 
16  19  19   9  19  20  14  29    # 160 
19  19  19  19  19  19  21  19    # 168 
20  32  20  19  19  19  19  19    # 176 
19  29  19  19  19  19  19   9    # 184 
 9   9   9  19  19  19  19  19    # 192 
19  19  19  19  21  21  10   9    # 200 

# space char:
10

# value for unproportional
20


# Font 1 (Handwritten)

# proportional values:
12   9  22  17  19  19  25   4    # 0   
33  33  25  35  11  10   6  33    # 8   
18  10  17  17  17  17  17  15    # 16  
12  16   5  30  30  30  30  30    # 24  
12  16  19  16  19  18  18  17    # 32  
22  11  17  18  18  30  22  19    # 40  
22  19  19  20  18  19  19  29    # 48  
19  18  19  19  33  33  19  19    # 56  
12  14  11  11  16  11  12  14    # 64  
14  10  13  12  10  19  18  12    # 72  
16  13  13  11  12  15  12  15    # 80  
13  12  12  37  33  37  35  37    # 88  
16  16  16  16  33  17  18  18    # 96  
18  18  11  11  11  11  19  19    # 104 
19  19  19  19  19  19  15  14    # 112 
14  14  14  20  14  11  11  11    # 120 
11  10  10  10  10  12  12  12    # 128 
12  15  15  15  15  24  18  21    # 136 
10  19  19  19  19  19  19  19    # 144 
19  19  19  19  19  19  19  19    # 152 
19  19  19  19  19  19  19  19    # 160 
19  19  19  19  19  19  19  19    # 168 
19  19  19  19  19  19  19  19    # 176 
19  19  19  19  19  19  19  19    # 184 
19  19  19  19  19  19  19  19    # 192 
19  19  19  19  19  19  19  19    # 200 

# space char:
19

# value for unproportional
16


# -eof-
```
![font1](https://user-images.githubusercontent.com/1880088/108194342-9016ab00-7127-11eb-8168-90a2f6971573.png)
![font2](https://user-images.githubusercontent.com/1880088/108194354-94db5f00-7127-11eb-8eb3-5536b7a85644.png)

**Comment by AlexBe1ov** [comment]
I've made dirty hack which fixed proportional values in russian font
patch - https://github.com/AlexBe1ov/re3/commit/25da0b7f7258e3205e4c9e8ab195c68880f92e97
build - https://github.com/AlexBe1ov/re3/releases/tag/pre-release_v2021-02-17

**Comment by once13one** [comment]
> I've made dirty hack which fixed proportional values in russian font
> patch - [AlexBe1ov@25da0b7](https://github.com/AlexBe1ov/re3/commit/25da0b7f7258e3205e4c9e8ab195c68880f92e97)
> build - https://github.com/AlexBe1ov/re3/releases/tag/pre-release_v2021-02-17

Thanks a lot for fix, but this method don't work on PS Vita =( Maybe some help build reVC-vita with your changes.

**Comment by Sergeanur** [comment]
Implemented.
