### ISSUE TITLE
Compilation error on FreeBSD 13

### ISSUE THREAD

**Issue by andros-ua** [GTAmodding/re3#1080]
**Describe the bug**
gmake CC=clang CXX=clang++ config=release_bsd-amd64-librw_gl3_glfw-oal
==== Building librw (release_bsd-amd64-librw_gl3_glfw-oal) ====
==== Building re3 (release_bsd-amd64-librw_gl3_glfw-oal) ====
Running prebuild commands
"./../printHash.sh" "./../src/extras/GitSHA1.cpp"
CarCtrl.cpp
../src/control/CarCtrl.cpp:2721:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;
                       ^~~
../vendor/librw/src/rwbase.h:73:13: note: expanded from macro 'nil'
#define nil NULL
            ^~~~
/usr/include/sys/_null.h:37:14: note: expanded from macro 'NULL'
#define NULL    nullptr
                ^~~~~~~
1 error generated.
gmake[1]: *** [re3.make:814: obj/bsd-amd64-librw_gl3_glfw-oal/Release/re3/CarCtrl.o] Error 1
gmake: *** [Makefile:78: re3] Error 2

**To Reproduce**
gmake CC=clang CXX=clang++ config=release_bsd-amd64-librw_gl3_glfw-oal
or
gmake CC=clang CXX=clang++ config=debug_bsd-amd64-librw_gl3_glfw-oal
or
gmake CC=clang CXX=clang++ config=vanilla_bsd-amd64-librw_gl3_glfw-oal

**Expected behavior**
Successful compilation.

**Version**
FreeBSD 13.0-BETA2
gmake-4.3_2
premake5-5.0.0.a15

**Comment by erorcun** [comment]
oh thank you. is it fixed when you change `return nil` in that line to `return false` ?

**Comment by andros-ua** [comment]
Yes it is. And i had to apply similar to these lines:

PedAttractor.cpp
../src/peds/PedAttractor.cpp:508:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:510:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:519:9: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
        return nil;

../src/peds/PedAttractor.cpp:527:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:529:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:538:9: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
        return nil;

../src/peds/PedAttractor.cpp:546:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:548:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:557:9: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
        return nil;

../src/peds/PedAttractor.cpp:565:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:567:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:576:9: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
        return nil;

../src/peds/PedAttractor.cpp:584:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:586:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/peds/PedAttractor.cpp:595:9: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
        return nil;
 
../src/peds/PedAttractor.cpp:603:10: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nil;

../src/render/WaterLevel.cpp:614:109: error: cannot initialize a parameter of type 'bool' with an rvalue of type 'nullptr_t'
                        if (!CWorld::ProcessLineOfSight(lineStart, lineEnd, col, entity, true, false, false, false, true, false, nil))
                                                                                                                                                                                                                                   ^
../src/render/WaterLevel.cpp:621:110: error: cannot initialize a parameter of type 'bool' with an rvalue of type 'nullptr_t'
                                if (!CWorld::ProcessLineOfSight(lineStart, lineEnd, col, entity, true, false, false, false, true, false, nil))

**Comment by withmorten** [comment]
Should be fixed now, let us know if you have any other problems!
