### ISSUE TITLE
[III] Prevent despawning when looking away

### ISSUE THREAD

**Issue by TRPB** [GTAmodding/re3#1082]
This is a great project. Now that the source is available is it possible to fix one of the most annoying aspects of GTA3? Cars around you despawn when they leave the screen. Is there any way to fix this? As you have the VC code can it just be copied from there?

**Comment by katktv** [comment]
If this is to be fixed, I'd like this to be an option instead of a mandatory change, as this bug is one of the staples of GTA speedrunning.

**Comment by ZeptoBST** [comment]
I second the addition of the option. It's often annoying when a car you need despawns just because you briefly looked away. However being able to despawn trafic is useful.

**Comment by EnglishBen** [comment]
While it's a fair point to bring up, it's worth mentioning that copying the VC code would do nothing. VC deals with traffic in the exact same way, and the same behaviour exists in both games.

**Comment by Tomasak** [comment]
Wasn't this recently fixed with map memory usage set to high?

**Comment by Sergeanur** [comment]
It is fixed but map memory usage has nothing to do about it.
