### ISSUE TITLE
re3/VC doesn't run from game folder of Mac Steam version

### ISSUE THREAD

**Issue by erorcun** [GTAmodding/re3#1085]
User has to copy all game data to somewhere else. Reported from reddit. I know this isn't really a issue, I just want to learn why.
```
...
[DBG]: Using one streaming thread for all channels
[DBG]: Created cdstream thread
[DBG]: size of matrix 80
[DBG]: size of placeable 80
[DBG]: size of entity 120
[DBG]: size of building 120
[DBG]: size of dummy 128
casepath couldn't find dir/file "TEXT", full path was \\TEXT\
...
```

**Comment by sherief** [comment]
Does the binary have a quarantine attribute and if so can you try removing it using `xattr`? Translocation might be in place here.

**Comment by halpz** [comment]
that worked, I used `sudo chmod a+x reVC`
