### ISSUE TITLE
VCRUNTIME140_1.dll Not Found Error

### ISSUE THREAD

**Issue by BlackGuyRX** [GTAmodding/re3#1087]
When trying to boot the re3.exe inside my GTAIII installation folder, I get this error-
![image](https://user-images.githubusercontent.com/6956691/108088678-5d44b800-703e-11eb-9893-de2c7100a364.png)
Am I missing this file or is it because I'm not using the Steam version of the game?

**Comment by withmorten** [comment]
Which version are you running? Generally I made sure that all non glfw versions use static runtime, so unless you're using glfw, that error shold not appear.

Otherwise you're missing some vcredist. Probably the 2015 one.

**Comment by BlackGuyRX** [comment]
> 
> 
> Which version are you running? Generally I made sure that all non glfw versions use static runtime, so unless you're using glfw, that error shold not appear. (The precompiled glfw libs use dynamic runtime).
> 
> Otherwise you're missing some vcredist. Probably the 2015 one.

I'm using a "repack" that's based on patch v1.1 according to it's notes. I guess it's based on an old retail copy.

**Comment by withmorten** [comment]
I meant which build type - d3d9/glfw/mss/oal. re3 should work with any PC version.

**Comment by blattersturm** [comment]
> Otherwise you're missing some vcredist. Probably the 2015 one.

Recent 2019 one, actually. 140_1 DLL was added for the optimized exception handling functionality in a VS2019 update.

**Comment by withmorten** [comment]
Ah I see. I was assuming 140 = v140 toolset = VS2015.

**Comment by asm95** [comment]
Suggested Solution:

- Download the latest Microsoft Visual C++ Redistributable for Visual Studio **2019**: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
