### ISSUE TITLE
Censorship?

### ISSUE THREAD

**Issue by Bun01294** [GTAmodding/re3#1094]
Does this code still have the vc censorship that was implemented on the pc and later ps2 releases?

**Comment by aap** [comment]
yes, but it's disabled by default. see NASTY_GAME define in config.h

**Comment by Grovespaz** [comment]
If you mean the Haitian / Cuban censorship, that depends on which game assets you use.

If you mean the German stuff (Rampages etc.), it's not censored by default but you can change that in config.h (see the NASTY_GAME define)
