### ISSUE TITLE
How to compile release 1.0?

### ISSUE THREAD

**Issue by lindevel** [GTAmodding/re3#1095]
I tried to download and compile release tarball https://github.com/GTAmodding/re3/archive/re3_v1.0.tar.gz, but the compiler throws errors:
```
Building configurations...
Running action 'gmake2'...
Done (2068ms).
make: Entering directory 'build'
==== Building librw (release_linux-amd64-librw_gl3_glfw-oal) ====
==== Building re3 (release_linux-amd64-librw_gl3_glfw-oal) ====
Running prebuild commands
"./../printHash.sh" "./../src/extras/GitSHA1.cpp"
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Accident.cpp
In file included from ../src/core/common.h:53,
                 from ../src/core/Accident.cpp:1:
../src/fakerw/rwcore.h:5:10: fatal error: rw.h: No such file or directory
    5 | #include <rw.h>
      |          ^~~~~~
compilation terminated.
make[1]: *** [re3.make:886: obj/linux-amd64-librw_gl3_glfw-oal/Release/re3/Accident.o] Error 1
make: *** [Makefile:78: re3] Error 2
make: Leaving directory 'build'
```
The same error as in https://github.com/GTAmodding/re3/issues/1036

**Comment by Grovespaz** [comment]
It's better to clone the git repository with submodules as instructed in the readme. You're missing the vendore submodules now, including librw.

If you really really want to compile the first release, I believe there's a separate branch for them.

**Comment by lindevel** [comment]
But what if I want to create a package? md5/sha256/PGP signature required

**Comment by Grovespaz** [comment]
You can manually aquire the vendor sources and simply put them in the vendor folder if you _really_ want to.
See https://github.com/GTAmodding/re3/tree/re3_v1.0/vendor for an example of what needs to be there for the 1.0 tag.

You'd still be better off using the git repo imho, as it is not possible to tamper with the history and all vendor dependencies are also versioned, but that's up to you.
