### ISSUE TITLE
Crash when staring new game [linux amd64]

### ISSUE THREAD

**Issue by ganzzz-destroer** [GTAmodding/re3#1100]
[DBG]: cdvd_stream: read info 0x55a732b2f370
[DBG]: Using one streaming thread for all channels
[DBG]: Created cdstream thread
[DBG-2]: [../src/skel/glfw/glfw.cpp.psInitialize:397]: gGameState = GS_START_UP
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: Default skin set as no other skins are available OR saved skin not found!
[DBG]: Physical memory size 1943257088
[DBG]: Available physical memory 561410048
OpenGL version: 4.6 (Core Profile) Mesa 20.3.4
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1732]: gGameState = GS_INIT_ONCE
[DBG]: Loadind audio cache (If game crashes around here, then your cache is corrupted, remove audio/sound.cache)
[DBG-2]: Finding MP3s...
[DBG-2]: /media/data/torrent/GTA3VC_Linux/re3_revc_engine/gta3\MP3\
lstat: : Net takogo fajla ili kataloga
casepath couldn't find dir/file "GTA3.tar.gz", full path was /media/data/torrent/GTA3VC_Linux/re3_revc_engine/gta3\MP3\GTA3.tar.gz
[DBG-2]: /media/data/torrent/GTA3VC_Linux/re3_revc_engine/gta3\MP3\GTA3.tar.gz - NOT A VALID MP3
lstat: : Net takogo fajla ili kataloga
casepath couldn't find dir/file "GTAVC.tar.gz", full path was /media/data/torrent/GTA3VC_Linux/re3_revc_engine/gta3\MP3\GTAVC.tar.gz
[DBG-2]: /media/data/torrent/GTA3VC_Linux/re3_revc_engine/gta3\MP3\GTAVC.tar.gz - NOT A VALID MP3
lstat: : Net takogo fajla ili kataloga
casepath couldn't find dir/file "re3_revc_engine.tar.gz", full path was /media/data/torrent/GTA3VC_Linux/re3_revc_engine/gta3\MP3\re3_revc_engine.tar.gz
[DBG-2]: /media/data/torrent/GTA3VC_Linux/re3_revc_engine/gta3\MP3\re3_revc_engine.tar.gz - NOT A VALID MP3
[DBG]: Initialising CTimer...
[DBG-2]: Performance counter not available, using millesecond timer

[DBG]: CTimer ready
[DBG]: Initialising CPedStats...
[DBG]: Loading pedstats data...
[DBG]: CPedStats ready
[DBG]: Intialising CTimeCycle...
[DBG]: CTimeCycle ready
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1824]: gGameState = GS_INIT_FRONTEND;
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1846]: gGameState = GS_FRONTEND;
LOAD frontend
LOAD sprite
REMOVE frontend
REMOVE menu textures
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1862]: gGameState = GS_INIT_PLAYING_GAME;
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:2013]: gGameState = GS_INIT_PLAYING_GAME;
casepath couldn't find dir/file "playback.dat", full path was playback.dat
casepath couldn't find dir/file "record.dat", full path was record.dat
[DBG]: Initialising CParticleMgr...[DBG]: Initialising CParticle...[DBG]: CParticle ready
RE3 ASSERT FAILED
	File: ../src/core/CdStreamPosix.cpp
	Line: 554
	Function: CdStreamAddImage
	Expression: false
re3: ../src/core/re3.cpp:1126: void re3_assert(const char*, const char*, unsigned int, const char*): Proverochnoe utverzhdenie <<false>> ne vy`polneno.
Аварийный останов

**Comment by erorcun** [comment]
this indicates that your gta3.img is missing/your game files are corrupt/misplaced.

**Comment by ganzzz-destroer** [comment]
Fixed moving game from ntfs to ext4 partition.
