### ISSUE TITLE
Luigi's Girls death bug

### ISSUE THREAD

**Issue by viiibe** [GTAmodding/re3#1102]
**Describe the bug**
When starting the mission Luigi's Girls there is a chance that the player character dies right after the cutscene is played/skipped.

**To Reproduce**
Start the mission Luigi's Girls. This may or may not happen, I tried it three times and it happened two out of three times.

**Expected behavior**
Player character does not die and the mission goes as normal.

**Version**
Win 64bit OpenGL OAL 7db2df3

**Comment by Calinou** [comment]
Is the frame limiter enabled? If it's disabled, the game may run at very high FPS and cause physics to glitch out (which can result in sudden player deaths from fall damage). This bug is also present in the original game.

**Comment by viiibe** [comment]
The frame limiter was enabled and the game ran at 30fps.

**Comment by Nick007J** [comment]
This bug is happening in original game, only during that particular fade. It happens if you hold sprint and/or forward during it. Workaround is just not to hold movement buttons. It may be looked into at some point though.

**Comment by viiibe** [comment]
Thanks for clarifying that. Closing since it's accurate to the original.
