### ISSUE TITLE
Internal wrapper\recompiller for opcodes to support existing asi and cleo mods?

### ISSUE THREAD

**Issue by v00d00m4n** [GTAmodding/re3#1108]
I suppose its no so easy to achieve, but possible to create some sort of compatibility layer that will disassemble asi modules instead of running them directly, check for known offsets and opcodes of original game code, then remap offsets to a new code, and then run fixed code and store its a cache nearby original asi (like original.asi and original.reasi next to it), to avoid doing recompilation on every load.

So, how about doing something like this to keep compatibility with existing mods?

**Comment by aap** [comment]
Not possible. There is no way to get asi and cleo mods (that modify memory) to work without reimplementing them.
