### ISSUE TITLE
Can't choose original MSS audio with hardware EAX 3.

### ISSUE THREAD

**Issue by KainXVIII** [GTAmodding/re3#1110]
At least it should be a feature judging by this "Audio is done with MSS (using dlls from original GTA) or OpenAL."
Because OpenAL Soft EAX3 does not sound exactly like real EAX 3 on my Creative X-fi imho..

**Comment by Grovespaz** [comment]
What build are you using? You should use the 32-bit MSS build found [here (III)](https://nightly.link/GTAmodding/re3/workflows/re3_msvc_x86/master/re3_Release_win-x86-librw_d3d9-mss.zip) and [here (VC)](https://nightly.link/GTAmodding/re3/workflows/reVC_msvc_x86/miami/reVC_Release_win-x86-librw_d3d9-mss.zip)

**Comment by KainXVIII** [comment]
> What build are you using? You should use the 32-bit MSS build found [here (III)](https://nightly.link/GTAmodding/re3/workflows/re3_msvc_x86/master/re3_Release_win-x86-librw_d3d9-mss.zip) and [here (VC)](https://nightly.link/GTAmodding/re3/workflows/reVC_msvc_x86/miami/reVC_Release_win-x86-librw_d3d9-mss.zip)

Sorry, i was stupid and used wrong build, now its working with hardware EAX3! 
But maybe its an opportunity to improve software EAX3 effects for majority of people who does not have antique sound cards like me. For now sound output have to much reverb and voices are barely recognizable. Or maybe opportunity to made sound system closer to PS2 or Xbox ports if they are good and reverse source code is finally available  🙏

**Comment by HarGabt** [comment]
I'm having the same issue
Used 32-bit build, tried to set creative eax 3, but the game doesn't let me set it - "hardware not available"

**Comment by KainXVIII** [comment]
> I'm having the same issue
> Used 32-bit build, tried to set creative eax 3, but the game doesn't let me set it - "hardware not available"
> Creative X-Fi Titanium, Game mode

I also used Creative Alchemy btw.
![20210217212525_1](https://user-images.githubusercontent.com/16922126/108249919-b7409d00-7166-11eb-9160-26487195ef61.jpg)

**Comment by HarGabt** [comment]
> I also used Creative Alchemy btw.

Me too, tried Alchemy, the game lets me choose EAX 3, but it crashes when i load my save. Works only with new game.

**Comment by withmorten** [comment]
Did you load a save that was created with the x64 build? Unfortunately, x86 and x64 saves are not yet compatible.

**Comment by KainXVIII** [comment]
Strange, new 32-bit MSS build does not work for me anymore, EAX3 resets to Miles 2d all the time.
And then its just hangs on launch and i can't fix it O_o
