### ISSUE TITLE
Doesn't seem to work with Steam?

### ISSUE THREAD

**Issue by Afr0** [GTAmodding/re3#1111]
I can't seem to get this to work with the Steam version of Vice City.
What is the version of Vice City that this is expected to work with?

**Comment by Grovespaz** [comment]
Works for me, I just tried with the latest version of reVC and latest Steam. What build are you using? Are you sure you used reVC instead of re3?

**Comment by Afr0** [comment]
Yeah, I wasn't using the right branch! Sorry! ;D
