### ISSUE TITLE
[re3]When the MP3 Player finishes playing a song, it goes straight to Song 1 in the playlist.

### ISSUE THREAD

**Issue by EddieLTU** [GTAmodding/re3#1113]
Basically the MP3 Player goes back to the Song 1 of the playlist once it finishes, but only if you don't tune the radio, do that and it goes back to normal, playing the next song in the list. And since MP3 Player works only in sequential, you can easily tell that it's not the next song.

**Video**
https://streamable.com/7empob

**Version**
re3_Release_win-amd64-librw_gl3_glfw-oal

**Comment by erorcun** [comment]
fixed on III, VC soon
