### ISSUE TITLE
Enhancement (built-in imgtool or similar built-in img editor)

### ISSUE THREAD

**Issue by mrdeathjr28** [GTAmodding/re3#1116]
**Describe the bug**

Enhancement (built-in imgtool or similar built-in img editor)

**To Reproduce**

**Expected behavior**

**Screenshots**

![qRgGj8c](https://user-images.githubusercontent.com/6601480/108268677-dcb7b180-713a-11eb-9d22-d8596e38cb33.png)

**Version**

Thanks

**Comment by aap** [comment]
That will not happen, but you can check out my python script to extract and rebuild cdimages: http://gta.rockstarvision.com/utils/cdimage.py

**Comment by mrdeathjr28** [comment]
for future version cdimage still be used or game can use files directly (easy modding)

thanks
