### ISSUE TITLE
[VC] Mod support?

### ISSUE THREAD

**Issue by Wasmachineman-NL** [GTAmodding/re3#1118]
Title. GTA:HV is known for being a crashfest and I was wondering if mods like that work with reVC.

Better yet: do any mods at all work with reVC?

**Comment by asm95** [comment]
Please, checkout the _readme_: https://github.com/GTAmodding/re3#modding. I don't know what "GTA:HV" is, but if it does comes with `.asi` files it won't work.

**Comment by gamelaster** [comment]
@asm95 GTA Hill Valley (Back to the Future mod)
