### ISSUE TITLE
Vertical Sensitivity different as horizontal. Always been a problem with VC.

### ISSUE THREAD

**Issue by rexhent** [GTAmodding/re3#1120]
SIlentPatch had a thing to make it the same however its not avaliable on the latest version of VC.

**Comment by erorcun** [comment]
title suggests "same as horizontal" is a problem, and text says making it same is actually good thing, i don't get it.

our vertical mouse sensitivity is always horizontal sensitivity + 0.005(default offset), so it isn't always same as in original.

**Comment by rexhent** [comment]
> title suggests "same as horizontal" is a problem, and text says making it same is actually good thing, i don't get it.
> 
> our vertical mouse sensitivity is always horizontal sensitivity + 0.005(default offset), so it isn't always same value like in original.

Sorry! I meant to write that the problem is that you can’t change the vertical res

**Comment by erorcun** [comment]
Not planned right now.
