### ISSUE TITLE
[ Linux | Mesa/AMDGPU ] Antialiasing only goes up to 8x

### ISSUE THREAD

**Issue by TRPB** [GTAmodding/re3#1124]
**Describe the bug**

On linux, specifically when using AMDGPU (and likely intel), anti-aliasing only goes up to 8x. I can set 16x in the config file but it has no effect.

**To Reproduce**

Use Linux with an AMD gpu and the AMDGPU driver

**Expected behavior**

Should be able to select same options as Windows and nvidia cards.

**Version**
1.0

**Comment by erorcun** [comment]
Anti-aliasing levels are provided by drivers/GL/GPU, we can't change that.
