### ISSUE TITLE
Can't load save game - Windows 10 - OpenGL version

### ISSUE THREAD

**Issue by L0rdLogan** [GTAmodding/re3#1125]
**Describe the bug**
I am trying to load a save game, same error occurs when trying to use the mission select from the debug menu

**To Reproduce**
Load an already saved, save game

**Expected behavior**
The game save loads and I appear at the save house in Portland

**Screenshots**

![image](https://user-images.githubusercontent.com/5092548/108391460-a432d900-7209-11eb-85f6-8a0757fda701.png)

**Version**
OpenGL a44d7d8

**Comment by kusst** [comment]
Is this a save game from original III?

**Comment by L0rdLogan** [comment]
> Is this a save game from original III?

No - it's a save from re3

**Comment by Grovespaz** [comment]
A few people have reported this error, something is clobbering the last ~5 garages in memory, which also fucks up the save, according to @Nick007J.

**Comment by ZiUlzimaze** [comment]
i completed the sub missions (taxi,vigilante,firefighter) prior to this constant crash. I even went to the other islands without any problems, even saved and reloaded to the safehouses with no issues.
i already completed the paramedic mission twice, with the exact same result after completion.
I made multiple saves to try and isolate the problem, and i think it is highly likely that something in the Paramedic mission is causing the garage problem (or maybe the spawning of the health and adrenaline pickups?). i also do not know if some main missions might cause the issue as I haven't progressed with the main story

**Comment by Grovespaz** [comment]
Just to clarify, you haven't progressed the main story at all? Or only to a certain point?

**Comment by ZiUlzimaze** [comment]
Just the 1st mission where you escort 8-ball and maria (Luigi's Girls). after that, I just proceeded with the sub missions.

**Comment by L0rdLogan** [comment]
> Just the 1st mission where you escort 8-ball and maria (Luigi's Girls). after that, I just proceeded with the sub missions.

I am on Pump Action Pimp, but I do remember accidentally starting Paramedic, never made any progress as I cancelled it immediately afterwards

**Comment by withmorten** [comment]
I can confirm this. I created a new game with amd64 windows build, saved after the first mission - started Paramedic once and cancelled, saved, and that save is now broken.

**Comment by HotCandy69** [comment]
I'll add that I've had this issue few days ago as well when Nick fixed the file for me on Discord. And indeed I also did all the paramedic missions before it as well (alongside Vigilante & Firefighter) so I guess it could be paramedic related after all.

**Comment by withmorten** [comment]
It's 100% paramedic related. Like I said, clean new save, only started paramedic once, didn't even finish, save broken.

**Comment by mokman** [comment]
> It's 100% paramedic related. Like I said, clean new save, only started paramedic once, didn't even finish, save broken.

can confirm, save after a paramedic missions did render the safefile unusable.

**Comment by VidalVGrobu** [comment]
I completed the game 99% and cannot load the save. Can anyone debug it?
[Uploading userfiles.zip…]()

**Comment by aeifr** [comment]
I might add: one of the windows versions (which supports gamepads, might be the amd64 librw d3d9 oal version) can still load the save game. But with the error (non crashing) before. Interacting with the pop-up window (graphic in the beginning of this issue), which offers the three buttons, abort, retry and ignore. Ignoring it twice (ctrl+i or drag the window to another screen) and focus the game again allows to play. Everything is just fine. Can still save and play the game with the bummer in the beginning.

**Comment by withmorten** [comment]
Please use PR #1149 which will be merged soon, it will fix any previously broken saves and only create compatible saves from now on.

Create a backup of your saves beforehand to be extra sure, but the conversion process should create one as well.

**Comment by hanseliezer** [comment]
> 
> 
> Please use PR #1149 which will be merged soon, it will fix any previously broken saves and only create compatible saves from now on.
> 
> Create a backup of your saves beforehand to be extra sure, but the conversion process should create one as well.

sorry I'm a noob in github: how do I 'use' a pull request?

**Comment by Nopey** [comment]
This is the pull request's repository: https://github.com/withmorten/re3/tree/saves
Download it and build it with the same steps you would to build the main branch.
If you're not comfortable with building it, [waiting for the next release](https://github.com/GTAmodding/re3/releases/latest) may be an option, although I'm unsure when that will happen.

**Comment by withmorten** [comment]
Merged into master now!

**Comment by hanseliezer** [comment]
> 
> 
> This is the pull request's repository: https://github.com/withmorten/re3/tree/saves
> Download it and build it with the same steps you would to build the main branch.
> If you're not comfortable with building it, [waiting for the next release](https://github.com/GTAmodding/re3/releases/latest) may be an option, although I'm unsure when that will happen.

right, I've cloned the master repo now, and it seems like I've successfully run premake_vs2019.cmd, and now I'm trying to do the second step of compiling re3.sln. I've opened it on VSC, but I don't know what/how I should do this step?

**Comment by withmorten** [comment]
Just redownload the updated master build from the re3 readme, no need to compile it yourself.
