### ISSUE TITLE
[re3] Game gets stuck/hangs at loading screen during boot-up with D3D9 MSS 32-bit version

### ISSUE THREAD

**Issue by ViperAcidZX** [GTAmodding/re3#1126]
I was trying to see if I can use the 32-bit MSS version of re3 but for some reason it refuses to launch the game beyond the initial loading screen and gets stuck there unlike the 64-bit version. I wanted to try the 32-bit hearing about how saves from the vanilla PC version aren't compatible with the 64-bit version of re3 but now I'm running into this problem where I can't even use the the 32-bit version at all.

1. Install the Grand Theft Auto III (I used the retail version).
2. Install re3 (tried to use the version on the Releases page and the nightly builds)
3. Attempt to launch the game.

I was hoping the game would launch with the 32-bit version but it doesn't work at all.

![re3_2021-02-18_13-04-43](https://user-images.githubusercontent.com/19318128/108401081-f5cb6b80-71e9-11eb-8d97-a73e6fb3c7f0.png)
My game just gets stuck on this screen on the initial launch with re3 D3D9 MSS 32-bit.

My system's specs:

- **OS:** Windows 10 Home, 64-bit
- **RAM:** 8 GB DDR3
- **GPU:** Nvidia GeForce GTX 960
- **CPU:** AMD FX-4350

**Comment by withmorten** [comment]
Are you loading a save or starting a new game? A save previously created with a 64bit build will not work with 32bit builds.

**Comment by ViperAcidZX** [comment]
This happens when launching the game from a clean installation with re3 D3D9 MSS 32-bit, and I haven't moved my save file from my Documents to re3's userfiles folder.

**Comment by erorcun** [comment]
is re3.ini created?

**Comment by ViperAcidZX** [comment]
It creates one but even then it re3 32-bit seems to refuse to work on my computer even after making a re3.ini file.

**Comment by erorcun** [comment]
can you try changing Windowed to 1 on ini, then running it with passing -console parameter to re3.exe?
you can do that by typing "re3.exe -console" on your explorer's address bar.

i wonder if it will show anything on console.

**Comment by ViperAcidZX** [comment]
I have tried that and this is what I get shown in this video I took with ShareX: https://drive.google.com/file/d/1KHX5tbONnC5o17bain0q48QJD8Pl0WsU/view?usp=sharing

It seems like the console shows the game gets stuck at this point going by this screenshot of the video I took:
![mpc-hc64_2021-02-19_15-31-16](https://user-images.githubusercontent.com/19318128/108558238-a22f4f80-72c7-11eb-8f90-e6ea6839a2b3.png)

Strangely I never had this problem with reVC's 32-bit version at all.

**Comment by erorcun** [comment]
hm actually last line seen on console is "TimeCycle ready", in window switcher.

can you confirm original GTA III works?

**Comment by ViperAcidZX** [comment]
I have just done a clean re-install of GTA III on Steam, and other using Windows XP (SP3) compatibility mode on gta3.exe because I'm using Windows 10 Home (64-bit) to get around the "Cannot find 640x480 resolution" problem until I can change the resolution to 1920x1080, the original game is playable on my PC,

**Comment by withmorten** [comment]
Hm, I've had some strange issues with Windows 10 with this the past few weeks - have you rebooted recently by any chance?

I had the same error on re3 and other games until I did. They couldn't find any video modes ...

**Comment by withmorten** [comment]
Do you still have this issue? Please reopen if yes.
