### ISSUE TITLE
Keybinds missing upon first boot

### ISSUE THREAD

**Issue by samy-k97** [GTAmodding/re3#1129]
**Describe the bug**
With the re3.ini/reVC.ini being regenerated, there are a few keybinds missing.

![Screenshot from 2021-02-18 18-27-06](https://user-images.githubusercontent.com/66317077/108406775-c1bc6e80-721a-11eb-8fbc-ad8e810b08b2.png)

![Screenshot from 2021-02-18 18-37-45](https://user-images.githubusercontent.com/66317077/108406819-cf71f400-721a-11eb-8082-3a48bba47061.png)

This can be remedied by clicking "Restore Defaults" which places the missing keybinds back

![Screenshot from 2021-02-18 18-27-53](https://user-images.githubusercontent.com/66317077/108407066-25469c00-721b-11eb-97da-ccaee6ac8c58.png)

![Screenshot from 2021-02-18 18-37-59](https://user-images.githubusercontent.com/66317077/108407183-4dce9600-721b-11eb-9567-8070b5f5b40b.png)

**To Reproduce**
1. Delete re3.ini/reVC.ini
2. Look at the keybinds

**Expected behavior**
Keybinds should be equal to the "Restore Defaults" instead missing a few

**Version**
![Screenshot from 2021-02-18 18-44-06](https://user-images.githubusercontent.com/66317077/108407528-be75b280-721b-11eb-9e25-c3d50cc259b7.png)

![Screenshot from 2021-02-18 18-47-10](https://user-images.githubusercontent.com/66317077/108407537-c2093980-721b-11eb-9b4f-bf345bd250fd.png)

**Comment by erorcun** [comment]
Fixed on master and miami. Thanks for your patience, closing it.
