### ISSUE TITLE
Is there any doc about file structure and usage in gta3 game directory?

### ISSUE THREAD

**Issue by fpemud** [GTAmodding/re3#1130]
Therefore, re3 users can debug by themselves more easily.

**Comment by erorcun** [comment]
how? what do you mean?

**Comment by fpemud** [comment]
I have failed to run reVC with my gta3 vice city installation.
I’d like to know what file/dir structure re3/revc expects in detail, as a baseline for further checking and debugging.

**Comment by erorcun** [comment]
you should download one of re3 or reVC builds(.zip), extract all the files to game folder, and then run re3/reVC

**Comment by Grovespaz** [comment]
See also https://github.com/GTAmodding/re3/issues/1106#issuecomment-780627089
