### ISSUE TITLE
[Bug] [VC] Kruger crosshair disappears with Standard Controller mode

### ISSUE THREAD

**Issue by KiralyCraft** [GTAmodding/re3#1143]
**Describe the bug**
In the mission where the Kruger is first obtained, attempting to aim it in first person shows the crosshair correctly, but moving the camera around in this mode makes it disappear and won't reappear unless 1st person is toggled. If the camera is not moved, it seems to stay in the correct position. Only seems to happen if the camera is moved with the right joystick.

**To Reproduce**
Pick up the Kruger, aim in first-person, and move the camera with the right joystick. I've only seen this happen in the "Standard Mode" controller style. The crosshair will disappear.

**Expected behavior**
While moving the camera in first person, the crosshair should stay in the same place.

**Screenshots**
[MKV Video here](https://cdn.discordapp.com/attachments/697929296903143494/812402448919560242/VID_20210219_211017.mkv)

**Version**
Linux 64-bit OpenGL OAL 3457ff4 ARM64

**Comment by Sergeanur** [comment]
You use left stick to aim a weapon. Using right stick toggles first person view on classic controls at all times. This is not a bug.
