### ISSUE TITLE
[Bug] [VC] Picking up the "adrenaline" pill that slows down time also slows down the pause menu animations

### ISSUE THREAD

**Issue by KiralyCraft** [GTAmodding/re3#1144]
**Describe the bug**
When the game time is slowed down using an adrenaline pill, pausing the game also makes the menu animations slow. It feels like they slowed down about the same amount as the game itself.

**To Reproduce**
Pick up the adrenaline pill, pause the game. Notice the background animation moving slower, choppier. Notice the menu highlights moving slower, choppier when selecting different options.

**Expected behavior**
No part of the menu should be affected by any in-game actions. If the player picks up something that slows down time, it should not slow down the menu too.

**Screenshots**
[MP4 Video here](https://cdn.discordapp.com/attachments/810628538852048928/812395145113632798/VID_20210219_203043.mp4)

**Version**
Linux 64-bit OpenGL OAL 3457ff4 ARM64

**Comment by Sergeanur** [comment]
Should be fixed

**Comment by KiralyCraft** [comment]
Indeed it is, many thanks!
