### ISSUE TITLE
(reVC) Vigilante level 13+: Game crashes when blowing up enemy car before all enemy cars have spawned

### ISSUE THREAD

**Issue by Barracuda6** [GTAmodding/re3#1146]
**Describe the bug**
Starting from vigilante mission level 13 in reVC, three cars of criminals spawn per level. Sometimes, not all three cars spawn at the same time at the start of the level, and the remaining cars spawn a short while later.

What I have experienced is that there are times when, upon completion of a vigilante level, a single enemy car spawns on the map but you do not receive the "Vigilante mission level x" message for the new level on the screen. The mission timer is also frozen like it is waiting for the targets to be spawned. If you wait for some time, the other two enemy cars will spawn, you will see the mission level message appear on the screen, and the mission timer resumes.

If you blow up the single enemy car before the other two have spawned, the game will crash once the other two spawn. if you wait for all three to spawn, you can play the level without it crashing.

Something else I noticed during this is that sometimes I will have to fly around for up to a few minutes before the targets for the next level spawn, and I seem to have a low number of peds/traffic in general. Not sure if this is related.

**To Reproduce**

Setting that I experienced this issue in:
- No main storyline progression (I was working on a starter save - only the first island was unlocked)
- Hunter retrieved from Fort Baxter (after 100 hidden packages were collected) and flown back to the first island, and the vigilante mission started here

1. Enter a Hunter (I did not try to reproduce with any other police vehicle)
2. Start the vigilante mission over the first island (Vice City Beach)
3. Play until vigilante level 13+ is reached and you find a level where only one car spawns in the beginning and you do not see the "Vigilante mission level x" message on screen
4. Blow up the single enemy car before the other two cars have a chance to spawn
5. The game should crash once the other two cars spawn

Save file that I was using (created on 64-bit Linux): [GTAVCsf8_vigilante_lvl13_bug.b.zip](https://github.com/GTAmodding/re3/files/6712419/GTAVCsf8_vigilante_lvl13_bug.b.zip)

**Expected behavior**

- All three enemy cars should spawn on the map at the same time at the beginning of the level
- The "Vigilante mission level x" message should appear on screen at the beginning of the level; there should be no delay in this message appearing

**Screenshots**

![vigilante_crash_level_25ish](https://user-images.githubusercontent.com/41495078/123339377-fda17080-d539-11eb-9002-9921cfca4bbd.png)
^ This time, I briefly saw a yellow target icon back behind me over the water, then it appeared on land where you see it in the screenshot then the game crashed. Log snippet: [vigilante_crash_level_25ish.txt](https://github.com/GTAmodding/re3/files/6712379/vigilante_crash_level_25ish.txt)

**More Logs**

[vigilante_crash.txt](https://github.com/GTAmodding/re3/files/6712424/vigilante_crash.txt)
[vigilante_crash_level_13.txt](https://github.com/GTAmodding/re3/files/6712425/vigilante_crash_level_13.txt)
[vigilante_crash_level_35.txt](https://github.com/GTAmodding/re3/files/6712427/vigilante_crash_level_35.txt)

**Version**

 linux-amd64-librw_gl3_glfw-oal, self-built from commit 60bc816a

**Comment by Barracuda6** [comment]
Still an issue as of 9382e86d.

Single enemy car spawned for the next level but without the "vigilante mission level x" messaging, and mission timer is frozen:
![screen_ 1624656285](https://user-images.githubusercontent.com/41495078/123486923-81239600-d5fc-11eb-9d78-7d8396ebe65f.png)

Single enemy car disappeared before the other two cars spawned (I think I've seen the cars clipping through the bridge and into the water before):
![screen_ 1624656320](https://user-images.githubusercontent.com/41495078/123487042-b6c87f00-d5fc-11eb-8da7-11c6d41e4a0e.png)

Game crashed soon after (probably when the other two cars tried to spawn):
```
REVC ASSERT FAILED
        File: ../src/control/Script.cpp
        Line: 3763
        Function: ProcessCommands100To199
        Expression: ped
Segmentation fault (core dumped)
```

[20210625_revc_vigilante_crash_9382e86d.txt](https://github.com/GTAmodding/re3/files/6718920/20210625_revc_vigilante_crash_9382e86d.txt)

**Comment by shilin-da** [comment]
It's pretty much the same to me, however I can't even get to 13 level because of missing targets. It happens randomly various levels. For example level 4 is completed, but nothing happens after that: no targets, no level 5 start message. The timer is frosen until I exit from the police car, then timer starts back but still no targets and no new level =(

**Comment by Barracuda6** [comment]
> It's pretty much the same to me, however I can't even get to 13 level because of missing targets. It happens randomly on various levels. For example level 4 is completed, but nothing happens after that: no targets, no level 5 start message. The timer is frosen until I exit from the police car, then timer starts back but still no targets and no new level (even after returnig to the police car) =(

This happens to me quite often as well. Sometimes I will have to fly around for a few minutes before the targets for the next level spawn.

**Comment by Barracuda6** [comment]
It appears that 8e6e46a919579b98962c2a0c770bda4f98323f46 fixed both issues:
- Delay in the spawning of targets for a level
- Only one of three target cars spawning at the beginning of a level at level 13+, with the remaining two cars spawning with a delay

From this commit, all targets spawned immediately at the beginning of the levels, including at levels 13+.
