### ISSUE TITLE
[reVC] [Modded] Crash on handling in GTA VC: Deluxe

### ISSUE THREAD

**Issue by DartPower** [GTAmodding/re3#1154]
Crash when initialize
![image](https://user-images.githubusercontent.com/2005369/123509729-d94fac00-d67f-11eb-9f65-69170515d847.png)

On vanilla this is working (modded vanilla, without any asi's, old mod from 2004)

Version: d8f5e86ededa61863629e2c90a84e2b97cdf76b9

Handling from mod:
[handling.zip](https://github.com/GTAmodding/re3/files/6719926/handling.zip)

**Comment by ermaccer** [comment]
Most likely the issue is one empty line at line 162 in the file you attached.

**Comment by ViperAcidZX** [comment]
I've been having similar problems too when trying to mod the game's gta3.img archive, and no matter what I change it always crashes the game. Can you guys please look into this for reVC? I've also had issues with mods such as Vice City: The Leftovers Fix, Updated SCM, and Rocky24pl's Map Fixes resulting in crashes, the game refusing to start, or when trying to start a new game, it freezes before the intro cutscene starts when starting a new game but freezes and shows some text with version of reVC I'm using.
