### ISSUE TITLE
[relcs]The game don't start

### ISSUE THREAD

**Issue by flutterbrony** [GTAmodding/re3#1158]
**Describe the bug**
On linux, when I try to launch the game, I just have a black screen, then the game stop

**To Reproduce**
Download the latest build, uncompress it in a folder, copy the game data (I did from the ps2 version, because I couldn't extract the obb file I got from the play store), then launch reLCS

**Expected behavior**
The game start

**logs of executable**
> $ ./reLCS 
> cdvd_stream: can't get filesystem info
> 
> RELCS ASSERT FAILED
>         File: /home/runner/work/re3/re3/src/core/CdStreamPosix.cpp
>         Line: 205
>         Function: CdStreamInit
>         Expression: 0
> [DBG]: size of matrix 80
> [DBG]: size of placeable 80
> [DBG]: size of entity 120
> [DBG]: size of building 120
> [DBG]: size of dummy 128
> [DBG-2]: [/home/runner/work/re3/re3/src/skel/glfw/glfw.cpp.psInitialize:412]: gGameState = GS_START_UP
> casepath couldn't find dir/file "gta_vc.set", full path was gta_vc.set
> casepath couldn't find dir/file "skins", full path was skins\
> [DBG-2]: Default skin set as no other skins are available OR saved skin not found!
> [DBG]: Physical memory size 3522134016
> [DBG]: Available physical memory 542818304
> OpenGL version: 4.6 (Core Profile) Mesa 21.1.2
> casepath couldn't find dir/file "coll", full path was models\coll\peds.col
> Erreur de segmentation (core dumped)

**Comment by Sergeanur** [comment]
reLCS doesn't work with PS2 files, it only works with files you could grab on our Discord server

**Comment by flutterbrony** [comment]
Thanks ! it explain a lot, I remembered obb files of the gta games was just zip files on android, and it seems it is not anymore with lcs ? Your files are from there ? Or a modded game (from vice city/III) maybe ?

**Comment by Sergeanur** [comment]
Read #1164, thank you.
