### ISSUE TITLE
[reVC] Aiming is broken with minigun and flamethrower

### ISSUE THREAD

**Issue by yasinkaraaslan** [GTAmodding/re3#1159]
Since the PS2 version didn't have auto aiming with minigun and flamethrower, R* didn't bother making these weapons compatible with mouse-aiming in the PC version (Like they did with M4 and Ruger). There is a mod that fixes it. I don't know much about reverse engineering so I couldn't decompile it and implement it to re3. 

If you guys can, here is the link: 
https://gamemodding.com/en/gta-vice-city/scripts/74011-fiks-pricelivaniya-s-minigana-i-ognemeta.html

**Comment by Sergeanur** [comment]
Fixed.
