### ISSUE TITLE
[reLCS]: Sound effects that do not match the floor

### ISSUE THREAD

**Issue by leanndroguedes** [GTAmodding/re3#1163]
**Describe the bug**
What's wrong with the sound effects?
When walking, jumping, or running on the floor, it plays sound effects that do not match the floor.

In older commits/builds like this [8232229](https://github.com/GTAmodding/re3/commit/82322293fe65682c32ee18a82296e8727f42d788) the audio works correctly.

**To Reproduce**
Start from a vanilla VC installation
Delete the directories from the installation that come with this archive (lcs_dist.7z)
Delete audio directory but keep the two sfx files
Copy the directories from this archive there (lcs_dist.7z)
Copy audio directory from PS2 LCS:
![Audio directory from PS2 LCS](https://user-images.githubusercontent.com/25756622/123545888-cd6ff280-d730-11eb-8d74-0f1cbc10d655.png)

**Expected behavior**
Floor-matching audio effect

**Screenshots**
[![Short YT video](https://user-images.githubusercontent.com/25756622/123546222-14121c80-d732-11eb-96f1-2f1f7f401e41.png)](https://youtu.be/r00tkwGZhHw)

**Version**
Linux 64-bit OAL [879761a](https://github.com/GTAmodding/re3/commit/879761af2ced44c28053656089622467452c7ff1)

**Comment by Sergeanur** [comment]
Read #1164, thank you.
