### ISSUE TITLE
Regenerated re3.ini and reVC.ini doesn't have missing key bindings

### ISSUE THREAD

**Issue by samy-k97** [GTAmodding/re3#1169]
**Describe the bug**
While booting the game without the ini file some keybindings will be missing (most notably the mouse buttons) and is only recovered by pressing "Restore Defaults"

**To Reproduce**
1. Boot the game with the re3.ini/reVC.ini deleted or moved
2. Check "Redefine Controls" and some key bindings will be missing

**Expected behavior**
Newly generated ini file should have the same keybindings as pressing "Restore Defaults"

**Screenshots**
re3 - Newly Generated ini
![Screenshot from 2021-06-28 01-27-40](https://user-images.githubusercontent.com/66317077/123564146-1b780b00-d7b0-11eb-99b8-de6910cbb7c6.png)

re3 - After pressing "Restore Defaults"
![Screenshot from 2021-06-27 22-44-03](https://user-images.githubusercontent.com/66317077/123564176-35195280-d7b0-11eb-8901-e61c41d5a783.png)

reVC - Newly Generated ini
![Screenshot from 2021-06-27 22-45-20](https://user-images.githubusercontent.com/66317077/123564192-45313200-d7b0-11eb-9761-5e62c0421ab9.png)

re3 - After pressing "Restore Defaults"
![Screenshot from 2021-06-27 22-45-28](https://user-images.githubusercontent.com/66317077/123564244-8aedfa80-d7b0-11eb-9c4a-fd17424d1f6f.png)

**Version**
Tell us what version you're running. Find out using the debug menu (Ctrl-M, Debug -> Version Text)
If you send a screenshot just enable it beforehand.
re3 - Linux 64-bit OpenGL OAL cc235be3
reVC - Linux 64-bit OpenGL OAL 3587cb02

**Comment by erorcun** [comment]
Your previous issue is already on my mind :) https://github.com/GTAmodding/re3/issues/1129

Closing this one.

**Comment by samy-k97** [comment]
Oops, Didn't even remember this after the DMCA. Sorry
