### ISSUE TITLE
Sport's cars drivers use wrong sitting animation.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#117]
Sport's cars drivers use "standard" sitting animation in sports cars:
![GTA3 07 07 2019 15_41_57](https://user-images.githubusercontent.com/30195961/60769389-536f7a80-a0cf-11e9-83ad-3fc3e2f6d02c.png)

**Comment by erorcun** [comment]
This is original game bug, but I'll fix it at some point.

**Comment by erorcun** [comment]
should be fixed with https://github.com/GTAmodding/re3/pull/338
