### ISSUE TITLE
openal installed from openal.org doesn't work with re3/VC

### ISSUE THREAD

**Issue by Akczht** [GTAmodding/re3#1172]
**Describe the bug**
It's not a bug but I wanted to know if re3/VC is supposed to work with openal installed from [here](https://www.openal.org/downloads/oalinst.zip) ? When I open it , it gives an error , I'm not a dev .

**To Reproduce**
download openal from [here](https://www.openal.org/downloads/oalinst.zip)
install it , remove openal32.dll from root dir .

**Expected behavior**
It should be working right ? 

**Screenshots**
don't have my computer right now , but it's easy to reproduce.

**Version**
any version till now

**Comment by Sergeanur** [comment]
No, it shouldn't work like that. It works when you put openal32.dll into game's dir.
