### ISSUE TITLE
[reVC] Crashing when meleeing peds

### ISSUE THREAD

**Issue by Veyrdite** [GTAmodding/re3#1179]
Game sometimes crashes when meleeing peds.  I've encountered this several times over the past few days, using fists, chainsaw or sword.

I have started running the game with gdb so I'll add backtraces+screenshots of each incident that I encounter from now on.

* OS: Linux x86_64 5.11.22_1
* Graphics: Radeon RX570 with in-kernel drivers.  

**Example 1**
Version: f8297df9
Framelimiter: off

Bug triggered after I threw the first punch.
```
[DBG]: Request Ped WFYBU
[DBG]: Remove Ped WFOSH
[DBG]: Request Ped HFYBU
[DBG]: Remove Ped WFYBU
[DBG]: Request Ped WFOSH
[DBG]: Remove Ped HFYBU
[DBG]: Request Ped WMOBU
[DBG]: Remove Ped WFOSH
[DBG]: Request Ped WFOSH
[DBG]: Remove Ped WMOBU
[DBG]: Request Ped HFYBU
[DBG]: Remove Ped WFYSH
[DBG]: Request Ped WMOBU
[DBG]: Remove Ped HFYBU
[DBG]: Request Ped WFOSH
[DBG]: Remove Ped WMOBU
[DBG]: Request Ped WMOBU
[DBG]: Remove Ped WFYSH

Thread 1 "reVC" received signal SIGSEGV, Segmentation fault.
CPedIK::LookAtPosition (this=this@entry=0x5555571ce900, pos=...) at /home/runner/work/re3/re3/src/peds/PedIK.cpp:159
159	/home/runner/work/re3/re3/src/peds/PedIK.cpp: No such file or directory.
(gdb) bt
#0  CPedIK::LookAtPosition (this=this@entry=0x5555571ce900, pos=...) at /home/runner/work/re3/re3/src/peds/PedIK.cpp:159
#1  0x00005555555c36f3 in CPed::MoveHeadToLook (this=this@entry=0x5555571ce640) at /home/runner/work/re3/re3/src/peds/Ped.cpp:1081
#2  0x00005555555d6428 in CPed::ProcessControl (this=this@entry=0x5555571ce640) at /home/runner/work/re3/re3/src/peds/Ped.cpp:2542
#3  0x00005555555b31ed in CCivilianPed::ProcessControl (this=0x5555571ce640) at /home/runner/work/re3/re3/src/peds/CivilianPed.cpp:232
#4  0x0000555555571171 in CWorld::Process () at /home/runner/work/re3/re3/src/core/World.cpp:1967
#5  0x0000555555547652 in CGame::Process () at /home/runner/work/re3/re3/src/core/Game.cpp:921
#6  0x0000555555577f10 in Idle (arg=0x1) at /home/runner/work/re3/re3/src/core/main.cpp:1540
#7  0x00005555555785f0 in AppEventHandler (event=event@entry=rsIDLE, param=param@entry=0x1) at /home/runner/work/re3/re3/src/core/main.cpp:1784
#8  0x0000555555674fe2 in RsEventHandler (event=event@entry=rsIDLE, param=param@entry=0x1) at /home/runner/work/re3/re3/src/skel/skeleton.cpp:210
#9  0x0000555555439b75 in main (argc=<optimized out>, argv=<optimized out>) at /home/runner/work/re3/re3/src/skel/glfw/glfw.cpp:2251
(gdb) 
```
Screenshot at time of crash:
![2021-06-30 20:52:25 834934025+10:00 Shyarenris reVC](https://user-images.githubusercontent.com/6168874/123949080-80687680-d9e5-11eb-9e88-701975953ea6.png)

**Comment by Veyrdite** [comment]
**Example 2**
Using sword against a policeman.  The first one or two policeman I attacked with the sword were fine, but this particular one triggered the crash.

Different function stack this time:
```
Thread 1 "reVC" received signal SIGSEGV, Segmentation fault.
CPed::ProcessControl (this=this@entry=0x5651331856c0) at /home/runner/work/re3/re3/src/peds/Ped.cpp:1749
1749	/home/runner/work/re3/re3/src/peds/Ped.cpp: No such file or directory.
(gdb) bt
#0  CPed::ProcessControl (this=this@entry=0x5651331856c0) at /home/runner/work/re3/re3/src/peds/Ped.cpp:1749
#1  0x00005651303b5e70 in CCopPed::ProcessControl (this=0x5651331856c0) at /home/runner/work/re3/re3/src/peds/CopPed.cpp:596
#2  0x0000565130371171 in CWorld::Process () at /home/runner/work/re3/re3/src/core/World.cpp:1967
#3  0x0000565130347652 in CGame::Process () at /home/runner/work/re3/re3/src/core/Game.cpp:921
#4  0x0000565130377f10 in Idle (arg=0x1) at /home/runner/work/re3/re3/src/core/main.cpp:1540
#5  0x00005651303785f0 in AppEventHandler (event=event@entry=rsIDLE, param=param@entry=0x1) at /home/runner/work/re3/re3/src/core/main.cpp:1784
#6  0x0000565130474fe2 in RsEventHandler (event=event@entry=rsIDLE, param=param@entry=0x1) at /home/runner/work/re3/re3/src/skel/skeleton.cpp:210
#7  0x0000565130239b75 in main (argc=<optimized out>, argv=<optimized out>) at /home/runner/work/re3/re3/src/skel/glfw/glfw.cpp:2251
```
Screenshot at time of crash:
![2021-06-30 22:34:19 992077387+10:00 Shyarenris reVC](https://user-images.githubusercontent.com/6168874/123961299-8a917180-d9f3-11eb-800e-9258f5be748d.png)

**Comment by erorcun** [comment]
Can you compile a build? If so I would appreciate if you can revert this https://github.com/GTAmodding/re3/commit/618d689dff9a22d9385abf36f5e364b38273b7cf and try again

**Comment by Veyrdite** [comment]
This is becoming annoying, the bug exhibits within a few minutes of punching peds in the build I downloaded but never appears in any build that I compile myself.

| Source | commit | Shows bug? |
| --------- | --------- | --------------- |
| own-built debug | cb72fee941 (latest miami) with 618d689 reverted | no bug |
| own-built debug | cb72fee941 (latest miami) | no bug |
| downloaded build | f8297df (old version shown above) | yes |
| own-built debug | f8297df (old version shown above) |  no bug |

Question: are the downlodable builds **vanilla**_linux-amd64-librw_gl3_glfw-oal or **release**_linux-amd64-librw_gl3_glfw-oal?

**Comment by withmorten** [comment]
which version is your gcc? on github actions it's 7.5.0

**Comment by Veyrdite** [comment]
gcc (GCC) 10.2.1 20201203

I'm on a rolling-release distro (Void Linux)

**Comment by parkerlreed** [comment]
Does it matter when you punch peds? x86_64 Linux Arch compiled myself. Start game, drive down to streets, get out and mash Ctrl to punch people. Works and no crash. This is with gcc 11.1.0

**Comment by erorcun** [comment]
Thank you.

> Question: are the downlodable builds vanilla_linux-amd64-librw_gl3_glfw-oal or release_linux-amd64-librw_gl3_glfw-oal? I can try and make those, see if anything changes.

Both are available to download, and just like you I was also only able to reproduce it in downloadable Release binary. Haven't tested it in Vanilla, and imo it's not needed.

Can you test it again? And if it crashes again backtrace will be different this time I think.

**Comment by Veyrdite** [comment]
Bug no longer triggers.  Downloaded build 74fd5851
