### ISSUE TITLE
[re3] undefined reference to `glfwGetX11Display`

### ISSUE THREAD

**Issue by bugaevc** [GTAmodding/re3#1180]
Commit https://github.com/GTAmodding/re3/commit/bf7280b55bffd568b00d5145f5799c7f73114ffc breaks building re3 on freedesktop systems that don't use X11 and/or don't build GLFW with `GLFW_EXPOSE_NATIVE_X11`.

Namely, this manifests as a linking error:

```
/usr/bin/ld: obj/linux-amd64-librw_gl3_glfw-oal/Debug/re3/glfw.o: in function `initkeymap()':
/re3/build/../src/skel/glfw/glfw.cpp:1473: undefined reference to `glfwGetX11Display'
/usr/bin/ld: obj/linux-amd64-librw_gl3_glfw-oal/Debug/re3/glfw.o: in function `checkKeyPresses()':
/re3/build/../src/skel/glfw/glfw.cpp:1687: undefined reference to `glfwGetX11Display'
collect2: error: ld returned 1 exit status
```

I have encountered this on several major GNU/Linux distributions:
* Fedora 34
* Ubuntu 20.04
* Arch Linux (latest at the moment of writing, using `glfw-wayland` package)

This is easily worked around by reverting the commit (which is not needed when not using X11 anyway).

Would be great if disabling this code was done automatically at configuration time.

**Comment by erorcun** [comment]
You just need to disable `#define GET_KEYBOARD_INPUT_FROM_X11`

**Comment by bugaevc** [comment]
I know nothing about Premake, so I cannot exactly help you with that, but say in Meson, you'd need to do something like this to detect whether `glfwGetX11Display()` exists, and only define `GET_KEYBOARD_INPUT_FROM_X11` in that case:

```meson
test_code = '''
#define GLFW_EXPOSE_NATIVE_X11
#include <GLFW/glfw3.h>
#include <GLFW/glfw3native.h>

void foo() { glfwGetX11Display(); }
'''

cxx = meson.get_compiler('cpp')
if cxx.links(test_code, dependencies: glfw)
    add_project_arguments('-DGET_KEYBOARD_INPUT_FROM_X11', language: 'cpp')
endif
```

And in CMake, like this:

```cmake
include(CheckSymbolExists)

set(CMAKE_REQUIRED_LIBRARIES glfw)
set(CMAKE_REQUIRED_DEFINITIONS "-DGLFW_EXPOSE_NATIVE_X11")
check_symbol_exists(glfwGetX11Display "GLFW/glfw3.h;GLFW/glfw3native.h" GLFW_HAS_X11)

if (GLFW_HAS_X11)
    add_compile_definitions("-DGET_KEYBOARD_INPUT_FROM_X11")
endif (GLFW_HAS_X11)
```

Note that this is not actually related to Wayland, but simply to whether GLFW was built with the X11 backend or not. So for example, if you're using GLFW's OSMesa backend, you also won't have this function. Or if you're using an X11-enabled build of GLFW on macOS, you would have this symbol, but your current check won't notice it:

https://github.com/GTAmodding/re3/blob/9a7fa478578beaba947ea867c15a25e411d641d8/src/skel/glfw/glfw.cpp#L54-L56

**Comment by erorcun** [comment]
Fixed with this: https://github.com/GTAmodding/re3/pull/1300

Thanks for the idea!

**Comment by bugaevc** [comment]
Thank you!

Now eagerly awaiting this in `master` :)
