### ISSUE TITLE
Not running(linux)

### ISSUE THREAD

**Issue by programerr01** [GTAmodding/re3#1182]
```cdvd_stream: can't get filesystem info

RE3 ASSERT FAILED
	File: /home/runner/work/re3/re3/src/core/CdStreamPosix.cpp
	Line: 205
	Function: CdStreamInit
	Expression: 0
casepath couldn't find dir/file "coll", full path was models\coll\peds.col
Segmentation fault (core dumped)

```

**Comment by kusst** [comment]
any more details? which branch are you trying to run?

**Comment by asm95** [comment]
The error is raised from the [CdStreamInit](https://github.com/GTAmodding/re3/blob/9a7fa478578beaba947ea867c15a25e411d641d8/src/core/CdStreamPosix.cpp#L205) function. Which attempts to find the main IMG file (`models/gta3.img`) using the function [statvfs](https://man7.org/linux/man-pages/man3/statvfs.3.html). An error code is raised and `re3` assumes that something is wrong with the installation.

In addition to @kusst suggestions...
* Check if copied the executable file (`re3`) to the root installation directory of GTA 3
* Check if you have the appropriate permissions to the game files

This is not a bug of `re3` but some misunderstanding in the appropriate configuration. Let us know if you could figure out.

**Comment by programerr01** [comment]
@asm95 thanks, it was some issue with the permissions
