### ISSUE TITLE
Pedestrians become solid after death

### ISSUE THREAD

**Issue by Griffathan** [GTAmodding/re3#1190]
Hi `there,` just noticed that whenever you kill someone, their bodies become solid rocks that you cant run through and you have to run around them. When you run someone over with a car, if they go under the vehicle, the vehicle stops dead onto of the body and cant move. If you pick up a prostitute,  she'll fall through the vehicles floor. Any idea why this is happening and how I can fix it? I. Running ver. 1.1

**Comment by erorcun** [comment]
Please read the issue template and write the correct version.

**Comment by erorcun** [comment]
Turned out this is a Vita issue, so closing it.
