### ISSUE TITLE
Pedestrian/npc vehicle bug

### ISSUE THREAD

**Issue by Griffathan** [GTAmodding/re3#1193]
**Describe the bug**
-pedestrians block the cars movement once they've been run over. Prostitutes fall through the car once they've been picked up. Dead bodies seem to have an invisible wall around them and restrict running through them.

**Expected behavior**
- to be able to run over people without coming to a complete stop if they're under the vehicle

**Version**
1.1 on ps vita

**Comment by erorcun** [comment]
This bug is special to Vita port, so closing it.
