### ISSUE TITLE
(reVC) Audio-related crash during Hotring event

### ISSUE THREAD

**Issue by Barracuda6** [GTAmodding/re3#1194]
**Describe the bug**
Around 40% of the time, in my experience, the game crashes around the beginning of the Hotring event at Hyman Stadium around the time all of the cars start crashing into each other.

**To Reproduce**
Start the Hotring event. The game might crash shortly after the race starts.

**Expected behavior**
The game should not crash.

**Screenshots**
At the point of the crash:
![Screenshot_20210701_211853](https://user-images.githubusercontent.com/41495078/124206885-c865c700-dad3-11eb-9054-f6379223259f.png)

**Version**
Linux 64-bit OpenGL OAL a0c76102
This is a build with COMPATIBLE_SAVES2 fixes found here: https://github.com/withmorten/re3/tree/miami-saves

**Save file**
Save file for testing: 
[GTAVCsf5_compatiblesaves2_hotring.b.zip](https://github.com/GTAmodding/re3/files/6751541/GTAVCsf5_compatiblesaves2_hotring.b.zip)

**Log**
```
[DBG]: Game successfully loaded 
Start loading airtrain
Finish loading airtrain
[DBG-2]: [../src/audio/sampman_oal.cpp.InitialiseChannel:1491]: Stopping channel 0 - really!!!
[DBG-2]: [../src/audio/sampman_oal.cpp.InitialiseChannel:1491]: Stopping channel 1 - really!!!
[DBG-2]: [../src/audio/sampman_oal.cpp.InitialiseChannel:1491]: Stopping channel 2 - really!!!
[DBG-2]: [../src/audio/sampman_oal.cpp.InitialiseChannel:1491]: Stopping channel 3 - really!!!
[DBG-2]: [../src/audio/sampman_oal.cpp.InitialiseChannel:1491]: Stopping channel 4 - really!!!
[DBG-2]: [../src/audio/sampman_oal.cpp.InitialiseChannel:1491]: Stopping channel 5 - really!!!
[DBG]: Loading ANIMS playidles
Start loading maverick
Finish loading maverick
[DBG]: Removing ANIMS playidles
[DBG]: Loading ANIMS bikes
Start loading pcj600
Finish loading pcj600
Start loading greenwoo
Finish loading greenwoo
[DBG]: Loading ANIMS coach
Start loading coach
Finish loading coach
[DBG]: Request Ped HFYPR
[DBG]: Remove Ped BFYPR
Start loading landstal
Finish loading landstal
[DBG]: Request Ped WFOTR
[DBG]: Remove Ped HMOST
THIS SHOULDN@T HAPPEN TOO OFTEN
[DBG]: colmodel kickstart is huge, size 53056
[DBG]: colmodel kickcar3 is huge, size 27968
[DBG]: colmodel kickbus03 is huge, size 17052
[DBG]: colmodel kickcar23 is huge, size 49564
[DBG]: colmodel kickcar28 is huge, size 39668
[DBG]: colmodel kickcar36 is huge, size 49612
[DBG]: colmodel carsontrack is huge, size 39620
Start loading hermes
Finish loading hermes
[DBG]: Start load scene
[DBG]: End load scene
[DBG]: colmodel doontoon23 is huge, size 20652

Thread 1 "reVC" received signal SIGSEGV, Segmentation fault.
0x000000000043ec2e in cAudioManager::ProcessActiveQueues (this=this@entry=0x84ea20 <AudioManager>) at ../src/audio/AudioManager.cpp:950
950                     if (!sample.m_bIsProcessed && !sample.m_bLoopEnded &&
(gdb) bt
#0  0x000000000043ec2e in cAudioManager::ProcessActiveQueues (this=this@entry=0x84ea20 <AudioManager>) at ../src/audio/AudioManager.cpp:950
#1  0x000000000043fdf1 in cAudioManager::ServiceSoundEffects (this=this@entry=0x84ea20 <AudioManager>) at ../src/audio/AudioManager.cpp:476
#2  0x000000000044021c in cAudioManager::Service (this=0x84ea20 <AudioManager>) at ../src/audio/AudioManager.cpp:115
#3  0x000000000050931a in cDMAudio::Service (this=<optimized out>) at ../src/audio/DMAudio.cpp:26
#4  0x00000000006f5cce in Idle (arg=0x1) at ../src/core/main.cpp:1545
#5  0x00000000006f6650 in AppEventHandler (event=<optimized out>, param=0x1) at ../src/core/main.cpp:1784
#6  0x000000000070ea30 in RsEventHandler (event=rsIDLE, param=0x1) at ../src/skel/skeleton.cpp:210
#7  0x000000000040dc5b in main (argc=<optimized out>, argv=0x7fffffffdd78) at ../src/skel/glfw/glfw.cpp:2251
```

**Comment by Veyrdite** [comment]
I can confirm this bug (cb72fee9 debug own-compiled).

**Comment by Sergeanur** [comment]
Should be fixed now.

**Comment by Barracuda6** [comment]
> Should be fixed now.

I played Hotring and Bloodring several times each with the fix in place and did not experience any crashes. Thank you!

**Comment by Ahmedmakhlouf123** [comment]
Not sure who that mother fucked using my email and my Xbox like he own it ? You r scam and shit bag not mean shit on plant thief cunt so you are one of the people hacked me ? Fuck you all believe me on way to u  all qnd don’t think you r watching my move because I’m actually watching you !!!! Watch ur back !    I’m the mother fucked not assed to die now and by the way I lost my underwear in Italy with the mother fucker in street so welcome to my fuckin no life which I don’t even know u ? Or what u want ? U got money? So not need but if u do ? Think again ? Do not fuckin ever think u gonna send whatever from ur gangster? I know who u r but do not challenge me because if u kill me now ? I’m not assed and I do have people know so u will be report to the police ? Not asses for u shagging ber ? She is yours my friend? Not need slag in my life and is enough lost my kids and my life for her dirty not human being 
Fuck u all
