### ISSUE TITLE
rw.h missing when trying to build.

### ISSUE THREAD

**Issue by Timtendo12** [GTAmodding/re3#1206]
**Describe the bug**
I keep getting this error. 

I use:
Release - win-amd64-librw-d3d9-oal

**To Reproduce**
I tried to build the game from source.

**Expected behavior**
I expect it to build without a error.

**Screenshots**
![image](https://user-images.githubusercontent.com/41442518/124448116-5f57ab00-dd82-11eb-9ed9-e5d4e798bccf.png)

**Version**
latest.

**Comment by erorcun** [comment]
You didn't read readme, did you?
