### ISSUE TITLE
(reVC) Two Wheels Double Bonus always records distance as 0.0m

### ISSUE THREAD

**Issue by Barracuda6** [GTAmodding/re3#1207]
**Describe the bug**
The "two wheels double bonus" stunt always awards only $1 to the player, and the distance recorded is always 0.0m. The duration of the stunt seems to be recorded correctly.

**To Reproduce**
Perform a two wheel stunt by driving a car on only two of its wheels.

**Expected behavior**
The distance travelled during the stunt should be recorded correctly, and the stunt payout should also be correct.

**Video**
https://user-images.githubusercontent.com/41495078/124500704-c2136b80-ddaf-11eb-89d7-3d9e06680b14.mp4

**Version**
Linux 64-bit OpenGL OAL 891be523 (https://github.com/withmorten/re3/commit/891be523)

**Comment by Sergeanur** [comment]
Fixed.
