### ISSUE TITLE
[reVC] Missing sound while stealing a bike

### ISSUE THREAD

**Issue by TheLonerD** [GTAmodding/re3#1210]
**Describe the bug**
"Kick" sound does not plays while stealing a bike from ped.

**To Reproduce**
https://user-images.githubusercontent.com/6560567/124812129-e9169c80-df6b-11eb-8539-88721558bd94.mp4

However "kick" sound plays if you steal a bike from the front of it.
https://user-images.githubusercontent.com/6560567/124812152-eddb5080-df6b-11eb-9c82-301e0331dc1c.mp4

**Expected behavior**
A "kick" sound should be played while stealing a bike.

**Version**
reVC_Release_win-amd64-librw_d3d9-oal, e6544a69

**Comment by Sergeanur** [comment]
Fixed.
