### ISSUE TITLE
reVC: Free camera and Look Right Button doesn't work on RC Bandit Race

### ISSUE THREAD

**Issue by PPastene** [GTAmodding/re3#1211]
**Describe the bug**
During the RC Bandir Race the freecam and the right look button doesn't work, but the left look is working as expected

**To Reproduce**
Before going into the Top Fun van which triggers the RC Bandit race have the free cam activated and map right look into the keyboard (E key by default)

**Expected behavior**
With free cam activated you should be able to look freely with the mouse and also be able to look from your right of the RC vehicle like any other vehicle in the game. This bug is only present on the RC Bandit event, on RC Baron and RC Chopper events there's no bug

**Version**
Win 64-bit D3D9 OAL 72f6780

**Comment by withmorten** [comment]
Can you expand on this? I was able to move the camera with the mouse and the controller. Looking right and left doesn't work for me either, but pressing both buttons to look back does weirdly enough.

**Comment by VitalRus95** [comment]
I have the same bug on _Windows D3D9 MSS 32bit_ version of reVC. I used CLEO Redux to test my own RC vehicles and launched the standard RC Bandit mission as well. In both cases free camera and looking right (`E` button) _don't_ work. Interestingly, looking left (`Q` button) and looking back (`E+Q`) work fine. I also noticed that pressing look right button seems to have retained one function, that is putting the camera right behind the vehicle, so it looks like it skips changing camera view and goes to resetting it immediately.

**Comment by ShaggE** [comment]
> 
> 
> Can you expand on this? I was able to move the camera with the mouse and the controller. Looking right and left doesn't work for me either, but pressing both buttons to look back does weirdly enough.

Maybe you mistook RC Bandit with RC Baron (I did that when I saw this issue).
For me, RC Baron (plane) works fine, but RC Bandit (car) works as it described in this issue: I can look left, but I cannot look right and the free camera doesn't work.

**Comment by erorcun** [comment]
Free cam not working is expected, since game is using BEHINDCAR cam for some reason in the race. 
Looking right not working however was a bug, and fixed with https://github.com/GTAmodding/re3/commit/09f693b9b908c844701502befeb549fda27ff24c. Closing the issue.
