### ISSUE TITLE
re3 bug with Ambulance mission

### ISSUE THREAD

**Issue by Gr33nEyes** [GTAmodding/re3#1212]
**Describe the bug**
Game can't load save with completed Ambulance mission

**To Reproduce**
Loading save file with completed Ambulance

**Expected behavior**
Loading game without errors

**Screenshots**
![screen](https://user-images.githubusercontent.com/40704849/124884403-e737f200-dfda-11eb-99f5-ea478c75af24.png)

**Version**
re3-Release_win-amd64-librw_d3d9-oal
If you send a screenshot just enable it beforehand.

**Comment by withmorten** [comment]
This is fixed now in master btw, please try it!
