### ISSUE TITLE
How reliable is this port for a serious 100% playthrough?

### ISSUE THREAD

**Issue by VlDAL** [GTAmodding/re3#1221]
Yesterday I decided to play GTA 3 after almost 20 years and I thought this project was probably the best way to play the game today on a modern machine.

I've played for a couple of hours then I took a break. When I came back to it, my save was currpted with no way to get back in where I left of. Trying to load the game would crash it.

During that session I did save and load a few times so I thought perhaps it was an one off case of bad luck. I did, however, found a bug during Taxi missions in which at some point, after dropping my last customer, the game only gave me 2 seconds to find the next one.. almost instantly failing my run in which was over 10 in a row. Not sure if this issue happens on the original as well or just in this port... but it certainly not what it was supposed to do.

Corrupted save and atll, I started over today.. After doing the first Misty mandatory mission, I jumped back into the TAXI missions and it was simply broken. I could only do one fare. After dropping off a customer, all NPCs disappeared from the world. I mean, ALL of them. The cars were still around but no pedestrians, meaning I could not find another customer and was just crusing around until the time ran out.. then all pedestrias suddenly populated the world again. I tried again and the same issue happened again and again.. with no way to do TAXI missions beyound the first customer.

So now I ask... I was planning on trying a 100/% run of this game for the first time, but it seems this port is not quite ready and reliable for such stunts yet, right?

**Comment by zerocool1992** [comment]
I have completed all mission in gta3 and almost all on VC . But vigilante missions sometimes throwing errors.

**Comment by Stekke** [comment]
I just finished the main storyline today, only had about 3 crashes during the entire run, and no other notable problems.  Perhaps some of the issues have been fixed in latest master but aren't in the latest release yet... I played on commit ec45ba68cd

**Comment by Sergeanur** [comment]
I think someone was able to beat re3 100%, but we didn't test 100%ing the game much ourselves. Though issues you describe sound very extreme, I certainly would not expect all that to happen. It would be helpful if you provide which build you were playing and save files that got corrupted.

**Comment by VlDAL** [comment]
> I think someone was able to beat re3 100%, but we didn't test 100%ing the game much ourselves. Though issues you describe sound very extreme, I certainly would not expect all that to happen. It would be helpful if you provide which build you were playing and save files that got corrupted.

I wish I could be more helptful. The build I used was the Windows D3D9 64bit link on the installation section of the main page. Used on Steam version. The currupted save did give me an error msg.. I should have screenshot it. I remember it being a bunch of nonsense and codes but there was the word GARAGE into the error msg. Garage door I think? Perhaps something to do with the car I had saved in the garage was unable to load? 

As for the taxi issues.. I don't know... like I said, all pedestrians would disappear during the taxi mission and reappear the moment the taxi mission fails and ends.

I actually gave up after this... for now. I'm ok with waiting a bit... give it more time and wait for future versions and make sure it works 1:1 before attempting those time sinking missions... Or maybe who knows... Perhaps Rockstar have some official plans for GTA 3 in October when the game turns 20. Rumours of a remaster are all over the place.. I will wait to see if something official happens then.. if now, I will check back the state of this project.

Thanks anyway. I will keep following the progress here regardless.. I think it's fascinating and I hope Take Two won't shut this down again.

**Comment by withmorten** [comment]
The save corruption is fixed now, the latest builds will fix any previously corrupted saves (if they had an assertion about Garages before) and convert them to the original format.

I was able to complete re3 100% with no major issues, and taxi worked fine too. No idea ...

**Comment by erorcun** [comment]
Saves issue is fixed. If taxi issue persists, you can consider opening a new issue for it.
Closing this one.
