### ISSUE TITLE
[reVC] uint16 m_numNearPeds can decrement below 0

### ISSUE THREAD

**Issue by Photosounder** [GTAmodding/re3#1222]
While flying around (I was diving from a higher altitude) I encountered a crash which was caused by `m_numNearPeds` (defined in Ped.h) having a value of 65535, which was then used in a loop. It probably shouldn't decrement to this value, but yet it did. The simplest workaround is to redefine this value as a `int16_t` so that when it has a value of -1 (instead of 65535) the for loops that depend on it don't run at all.

For reference [I tried it that workaround](https://github.com/Photosounder/re3/commit/12349658bcb00d5affa44047c6766ba5f6f81020#diff-26736f016ff6ccbdc0291320e03c3892033dc19f293458548cd1368c16754b2a) and that didn't seem to break anything.

**Comment by withmorten** [comment]
Should be fixed here fb5a207abcdf7b76fdb719b46c5c706deb7026fa, please reopen if not.
