### ISSUE TITLE
Please provide manual how to import project in Clion or Netbeans. 

### ISSUE THREAD

**Issue by zerocool1992** [GTAmodding/re3#1223]
I want to be able to modify code and debug application under Linux but I am not able to run debug build in IDE, I don`t have much experience in C++ development, but i want to try. Some please write simple manual how can I import project in IDE and start engine.

**Comment by asm95** [comment]
* This project supports CMake which is compatible with [CLion](https://www.jetbrains.com/clion/). They already wrote a [guide](https://blog.jetbrains.com/clion/2020/06/makefile-projects-in-clion/) on how to import CMake projects.
* Netbeans also supports CMake. Check out this [guide](https://stackoverflow.com/a/8027379) by `@Alba Mendez`.
* If you're running Windows then this project is compatible with Visual Studio 2015 up to 2019. That's the easiest way of compiling and running the project.
