### ISSUE TITLE
[re3] Crash when entering a car while mission cutscene is loading (on mission retry) in CPed::ScanForThreats

### ISSUE THREAD

**Issue by Stekke** [GTAmodding/re3#1224]
**Describe the bug**
GTA 3 crashes when entering a car while the mission cutscene is loading, on a mission retry attempt.
I suspect you aren't supposed to be able to enter your car at this time.

**To Reproduce**
I haven't been able to reproduce this issue. It might have to do with pedestrians being around your car, or behaving in a certain way while you are in the car and the cutscene is starting.
Specifically this crash happened on this save file, last story line mission: [GTA3sf2.b.gz](https://github.com/GTAmodding/re3/files/6796768/GTA3sf2.b.gz)

My compiled debug binary: [re3.gz](https://github.com/GTAmodding/re3/files/6796830/re3.gz)  
And core dump file: [core.gz](https://www.rinsa.eu/datastore/re3/core.gz)
You can load it up in gdb like so: `gdb re3 core` to get a debug session.

**Backtrace**

```
#0  0x00000000005298b9 in CPed::ScanForThreats (this=this@entry=0x65a0a70) at ../src/peds/Ped.cpp:753
#1  0x00000000004819d8 in CCivilianPed::CivilianAI (this=0x65a0a70) at ../src/peds/CivilianPed.cpp:75
#2  0x0000000000482500 in CCivilianPed::ProcessControl (this=0x65a0a70) at ../src/peds/CivilianPed.cpp:413
#3  CCivilianPed::ProcessControl (this=0x65a0a70) at ../src/peds/CivilianPed.cpp:233
#4  0x00000000006059aa in CWorld::Process () at ../src/core/World.cpp:1884
#5  0x00000000004dc43d in CGame::Process () at ../src/core/Game.cpp:1071
#6  0x000000000062835b in Idle (arg=arg@entry=0x1) at ../src/core/main.cpp:1606
#7  0x0000000000628af8 in AppEventHandler (event=event@entry=rsIDLE, param=param@entry=0x1) at ../src/core/main.cpp:1859
#8  0x000000000063bdb0 in RsEventHandler (event=event@entry=rsIDLE, param=param@entry=0x1) at ../src/skel/skeleton.cpp:210
#9  0x000000000040d0ec in main (argc=<optimized out>, argv=<optimized out>) at ../src/skel/glfw/glfw.cpp:2217
```

**Stack variables**

```
i = 0
flagsOfNearPed = <optimized out>
pedToFearFrom = 0x0
lastVehicle = 0
vehicles = {0x1, 0x0, 0x0, 0x0, 0x3f00cd2b3f5a734f, 0x7fc33e0c08dd, 0xc39f6e1e00000000, 0x426b71f9436b6b6e}
foundVeh = <optimized out>
fearFlags = 42991616
ourPos = {<rw::V3d> = {x = -318.860291, y = 235.419647, z = 58.8613014}, <No data fields>}
closestPedDist = 60
explosionPos = {x = -318.860291, y = 235.419647}
shooter = <optimized out>
deadPed = <optimized out>
```

**Version**
Linux 64-bit OpenGL OAL DEBUG ec45ba68

**Comment by erorcun** [comment]
I think this is fixed with https://github.com/GTAmodding/re3/commit/894495689f860631fa2f084769473296281a0d85 .
Please re-open the issue if you encounter it again.
