### ISSUE TITLE
[re3] Location indicator on map screen always points down

### ISSUE THREAD

**Issue by Stekke** [GTAmodding/re3#1225]
**Describe the bug**
The little indicator to show where you are on the map (in the menu map screen) always points down.

**To Reproduce**
Start a new game, open the menu and then the map screen.

**Expected behavior**
The location indicator should point in the direction that the player is facing.

**Screenshots**
Correctly pointing in the players direction on the mini radar:
![2021-07-11-150016_1680x1012_scrot-fs8](https://user-images.githubusercontent.com/1751956/125196223-8e6d9100-e248-11eb-8e8c-30022a08170e.png)
But always pointing down in the big map screen:
![2021-07-11-150025_1680x1012_scrot-fs8](https://user-images.githubusercontent.com/1751956/125196224-90375480-e248-11eb-9bde-23a656dbbdc0.png)

**Version**
Linux 64-bit OpenGL OAL DEBUG 3194fdb2

**Comment by ClaudeLib** [comment]
The person who did the pause map did this intentionally, it's supposed to look like a map pin.

**Comment by Stekke** [comment]
@ClaudeLib ah, alright! Then this can be closed.
