### ISSUE TITLE
[re3] Gaps on the map causing damage

### ISSUE THREAD

**Issue by Speciesx** [GTAmodding/re3#1227]
![re3_2021_06_30_13_41_04_704](https://user-images.githubusercontent.com/1196375/125202365-9989e680-e273-11eb-825e-6dcdee9c9f0f.jpg)

![re3_2021_07_11_17_11_34_380](https://user-images.githubusercontent.com/1196375/125202396-b3c3c480-e273-11eb-9f10-991039485c6a.jpg)

Not only a visual glitch, causing also player damage when running over that gaps.

**Version**
3194fdb

**Comment by withmorten** [comment]
The game only works correctly at 30fps, so any bugs that occur when at higher one are currently out of scope.
