### ISSUE TITLE
[re3] Garages not opening on save file across multiple builds/platforms

### ISSUE THREAD

**Issue by pathartl** [GTAmodding/re3#1246]
**Describe the bug**
Garages on my save game are no longer working and will not open. This goes for every hideout and spray and 8-ball garage.

**To Reproduce**
I can provide the save, if desired. This was tested against multiple PC builds and the unofficial Switch (re3-nx) build.

I attached a debugger to the game to try to investigate a bit, and `CGarage::Update()` is being spammed with a `m_eGarageType` value of 92, which is not a valid garage type. Tracing this back makes it feel like there could be something wrong with the script parser? I'm not familiar with the codebase but this is what I've been able to figure out so far.

**Comment by pathartl** [comment]
Did some more things, now actually tested on the latest build. I was previously using the latest release. Some progress, but now I'm getting crashes in Garages.cpp at the same location as #1125.

Tried downloading the latest artifact, the latest files linked in the README, and building from master myself and all exhibit the same issue. Provided is the bugged save file. The first slot will load up, but going into the hideout garage will crash the game. Game will then crash in subsequent loads in that slot. Slot 2 is the result of that.

[GTA3sf1.zip](https://github.com/GTAmodding/re3/files/6838066/GTA3sf1.zip)

**Comment by withmorten** [comment]
Did you do anything inbetween the saves? The very oldest backup file gets properly converted and then loads normally, so I'd suggest using that: `GTA3sf1.b.1626670717.bak`.

As to what happened, I assume you intermingled switch and windows saves or something similar, saved one as the other, resulting in garages coordinates to be *completely* broken ... ? They were previously incompatible.

**Comment by withmorten** [comment]
I looked into it and somehow your garages are all (at the very least) missing the proper value for the `m_fZ2` field. It's 0.0f instead of the actual value for each garage. I have no idea how that happened, but I would deem your save to be unfixeable, and so FIX_INCOMPATIBLE_SAVES tries to fix it each time you open the load game screen, resulting in it getting more and more broken all the time ... because the only way to detect if a save came from gcc or msvc, is to check the hardcoded crusher garage values, and if they're wrong, it's deemed to be a gcc save.

I think I should probably add some value into the save to denote the save has been fixed so it doesn't get "refixed" everytime but just deemed as broken.

**Comment by pathartl** [comment]
I was primarily playing on Switch which was built from master back in January, so well before any save fixes. I got to Bomb Da Base: Act II and moved my save over to PC for mouse + kb sniping and used the re3_v1.0 release build. I played a bit more on PC and then ran into issues with the garages not opening at all.

So as far as codebase timeline goes I believe every step was chronologically in order, but yeah I'm assuming it was just a matter of going across 2-3 different builds. When adding a value to the save it would probably make sense to "version" the saves, no? e.g. don't allow older builds to try to fix saves updated/created by newer builds. I could see someone trying to bounce around between versions and corrupting their save in the process.

**Comment by withmorten** [comment]
Yes, that explains it. Switch's gcc64 and Windows' msvc64 save types (as i've named them during fixing them) are not compatible. Not incompatible enough to directly cause crashes apparently though. There was a bitfield in CStoredCar which took 1 byte in gcc saves, and 4 bytes in msvc saves, causing some alignment issues.

I think we might be able to fix it by just replacing your garages block with a new clean one (from a save that just started the game), you'll of course lose all cars, but with the debugmenu or save editors you can just add new ones, I can try that later. I would do this on the oldest backup file, that's okay right?

**Comment by pathartl** [comment]
Ahhh yeah okay that completely makes sense.

Yeah that's completely fine. I didn't use garages anyway since they were broken ¯\_(ツ)_/¯

Is there documentation anywhere on the structure of the save / what you'd be doing? I'd be happy to write a utility to handle the process in case others need it as well.

**Comment by asm95** [comment]
> Is there documentation anywhere on the structure of the save / what you'd be doing? I'd be happy to write a utility to handle the process in case others need it as well.

Documentation is to look at the code and figure out yourself. If you take your time to write something, it would be very nice 🙂.

**Comment by withmorten** [comment]
I'd basically be doing this manually, anyway, I did start a small utility that reads the blocks and blocksizes and so can tell me at which file offset which block is, but nothing automatic regarding this.

**Comment by withmorten** [comment]
Okay here we go, I fixed it:

[GTA3sf1_fixed.zip](https://github.com/GTAmodding/re3/files/6844001/GTA3sf1_fixed.zip)

This is still in the msvc64 format, so re3 will now fix it *once* to be msvc32 afterwards, but I decided to upload the original save you had just in case :)

**Comment by pathartl** [comment]
Works perfectly! It even saved my car at the first hideout. Thank you for your time!

RE: Utility: I might attempt something later and throw it under debug menu with a PR. C++ skills aren't great but I'll give it a shot.

**Comment by withmorten** [comment]
That's a lot more complicated than it sounds, since GTA's saving is a bit chaotic. An external utility would probably be easiest, but I doubt this specific issue will come up that often.

No problem! And that car is from me, I just saved the starting car :D
