### ISSUE TITLE
The game crashes on startup if the gta3.set file is missing.

### ISSUE THREAD

**Issue by ClaudeLib** [GTAmodding/re3#125]
![image](https://user-images.githubusercontent.com/5920490/60915793-29bc7c00-a2a6-11e9-8657-5685e43a1315.png)
If using the file generated by the stock game, re3 launches and plays fine.

**Comment by ClaudeLib** [comment]
The issue is still there for me, just checked.

**Comment by sodomon2** [comment]
I have the same problem, only I'm running it on AlpineLinux(MUSL)

![re3](https://user-images.githubusercontent.com/49420637/96211565-ae368980-0f42-11eb-8aa9-d9decdb9aa11.png)
