### ISSUE TITLE
[reVC] Traffic light glow faces the wrong direction

### ISSUE THREAD

**Issue by Danmoni** [GTAmodding/re3#1252]
**Describe the bug**
The light corona for the traffic lights faces the wrong direction in reVC. This is especially noticeable at night time. Here's an example:
![trafficREVC](https://user-images.githubusercontent.com/87886882/126856552-c98a8c66-e224-45be-bece-0b82efb694dd.jpg)

**To Reproduce**
1. Boot up reVC and go to the nearest traffic light, preferably at night.

**Expected behavior**
The traffic light should glow when being looked at from the front, like in the vanilla game. 
![trafficVANILLA](https://user-images.githubusercontent.com/87886882/126856563-7d7e2706-80e0-4640-b03a-8d09dd9f28d9.jpg)

**Version**
Win 64-bit D3D9 OAL bf757fc9

**Comment by Sergeanur** [comment]
Fixed.
