### ISSUE TITLE
[reVC] Wanted level is not increase above 4 stars

### ISSUE THREAD

**Issue by TheLonerD** [GTAmodding/re3#1256]
**Describe the bug**
Wanted level is not increased above 4 stars no matter what is used: cheats, debug menu or by normal gameplay.

**To Reproduce**
Try to increase wanted level by Debug Menu or using a cheat `YOUWONTTAKEMEALIVE`

**Expected behavior**
Wanted level can be set to 5 or 6 stars

**Screenshots**
https://user-images.githubusercontent.com/6560567/127022182-4b798795-cf89-4b70-ac86-fd5b7239edd5.mp4

**Version**
reVC_Release_win-amd64-librw_d3d9-oal 1180f32

**Comment by ttyborg** [comment]
If I recall correctly, you can get 5 or 6 stars after all of the islands are unlocked.

**Comment by withmorten** [comment]
Yes, it works to 6 on a 100% savegame.
