### ISSUE TITLE
[reVC] Missing character 'y' in font

### ISSUE THREAD

**Issue by YALdysse** [GTAmodding/re3#1264]
**Describe the bug**
Character 't' replaces 'y' in texts. There is on Linux version with English language.

**Screenshots**
https://ibb.co/k2GDkLx

**Version**
commit 3006139

**My proposition**
Include 4K font by djdarko. [[link](https://gtaforums.com/topic/966506-vice-city-4k-fonts/)].
For Russian language you can use [this font](https://libertycity.ru/files/gta-vice-city/134083-hd-1c-font.html).
In my opinion, montana style is better than rage.

4K font for GTAIII [[link](https://gtaforums.com/topic/966838-iii-4k-fonts/)]

**Comment by Sergeanur** [comment]
The problem is that you're using russian fonts.txd instead of the original one.
