### ISSUE TITLE
Weird names in menu

### ISSUE THREAD

**Issue by Rugaliz** [GTAmodding/re3#1269]
**Describe the bug**
When on menu I get these weird names for the options. Some strings are missing?
I compiled this on my Fedora 34 Linux with the latest commit but this has been going on since late last year.

**Screenshots**
![Screenshot from 2021-08-01 12-24-21](https://user-images.githubusercontent.com/37263443/127769141-3be2f807-763e-4717-b075-b86c6eb73e45.png)

**Version**
I'm using the GTA III version that comes with Steam.

**Comment by parkerlreed** [comment]
https://github.com/GTAmodding/re3/wiki/Building-on-Linux

>In case you didn't copy some of the required gamefiles, copy all content from re3/gamefiles/ to the game root directory

**Comment by Rugaliz** [comment]
Oh that fixed it!
I didn't realized I had to copy those files,  thanks for your time!
