### ISSUE TITLE
HQ Interface and restoring PS2 Loadscreen like SkyGFX

### ISSUE THREAD

**Issue by YALdysse** [GTAmodding/re3#1272]
## My proposition ##
This is best compilation with Menu, Splashes, HUD and others.
I my opinion, these mods should to be included in re3/reVC
HQ Interface pack to III: [[link](https://www.mediafire.com/folder/iemex6mpa62ap/Best+HQ+Interface+for+GTAIII)]
HQ Interface pack to Vice City: [[link](https://www.mediafire.com/folder/1ri0adbd5byli/Best+HQ+Interface+for+GTA+VC)]

**Comment by Sergeanur** [comment]
Remaking interface is not in the scope of this project. The PS2 loading screens we already have, but loading screen is disabled since the game loads much faster.
