### ISSUE TITLE
Miami: Traffic lights half-illuminated

### ISSUE THREAD

**Issue by QuestionableTrifle** [GTAmodding/re3#1279]
Hello,

The traffic lights along Vice Point appear to be vertically split down the centre of each coloured light and illuminated on the left side. All other lights don't appear to be affected, and I have not seen this issue in re3. 

**To Reproduce**
Drive or walk along Vice Point and it should be quite apparent. 

**Expected behavior**
Each coloured light should be fully illuminated across its entire radius.

**Screenshots**
![screen_01628189901](https://user-images.githubusercontent.com/72353216/128407692-b1d7df5a-dc69-4a31-965e-7741f901140a.png)
![screen_01628189917](https://user-images.githubusercontent.com/72353216/128407776-48b8d3ed-822c-427a-9c7b-56082ec10fb1.png)
![screen_01628189935](https://user-images.githubusercontent.com/72353216/128407786-e939c71c-cbbd-42bf-a19b-af1d8cc497cb.png)
![screen_01628190040](https://user-images.githubusercontent.com/72353216/128407799-6f6a3fa2-fcb0-43a7-baa0-4298e432f0ff.png)

The final screenshot shows the location where the bug stops occurring.

**Version**
I last cloned the repository and compiled the game yesterday (04/08/21), though the issue has been present for months and I do not know when it first appeared. No mods, just vanilla reVC.

**Comment by aap** [comment]
Unfortunately this is a vanilla bug.

**Comment by QuestionableTrifle** [comment]
Thank you, @aap; I suspected that it might be since all of the other traffic lights were fine, but I wasn't able to find anything online to confirm.
