### ISSUE TITLE
[re3]El burro's mission serious can be trigered again even if you have completed "Big 'N Veiny"

### ISSUE THREAD

**Issue by MonaziteC** [GTAmodding/re3#1290]
**Describe the bug**
"Big 'N Veiny" is the last mission that given to protagonist by El Burro with phone. But when protagonist get close to the phone after conpleting "Big 'N Veiny" the fisrt mission "Turismo" start again.

**To Reproduce**
1. Complete the mission "Big 'N Veiny";
2. Get close to the phone which El Burro used to give missions;
3. The first misson "Turismo" start.

**Expected behavior**
1. Complete the mission "Big 'N Veiny";
2. Get close to the phone which El Burro used to give missions;
3. Nothing happens.

**Screenshots**
It's even impossible to take screenshots on Windows 11 as the cursor is locked in the upper left corner during the game. But I attached a game save with the mission "Big 'N Veiny" just completed.

**Version**
win 64-bit D3D9 OAL 033d89a9
[GTA3sf5.zip](https://github.com/GTAmodding/re3/files/6984440/GTA3sf5.zip)

**Comment by Nick007J** [comment]
This is exactly as in vanilla and is intentional (so that player can improve his record in stats).

**Comment by MonaziteC** [comment]
@Nick007J Thanks, it's my first time playing gta3.😂
