### ISSUE TITLE
[re3] HQ Fonts

### ISSUE THREAD

**Issue by YALdysse** [GTAmodding/re3#1292]
Please, include HQ Fonts to re3.
Russian HQ fonts by DimZet13: [[link](https://www.mediafire.com/file/0izz3j3uws6hmgx/HD_HUD_v1.1_by_DimZet13.7z/file)]
English, Spanish, Italian and Deutch HQ fonts by DJDARKO: [[link](https://gtaforums.com/topic/966838-iii-4k-fonts/)]

**Comment by Domiiniik** [comment]
No, RE is not about modifying game assets.

**Comment by Rider66code** [comment]
Doesn't looks like a good idea. All HD/HQ assets like fonts, vehicles, wheels, weapons can be installed/added to some personal branches, but definitely not master, which is not supposed to have modified assets.

**Comment by YALdysse** [comment]
Re3 included some game assets.
Look at re3/gamefiles/models/fonts_r  or generic.txd or menu.txd
Why you can not replace this file, that you have.

**Comment by Domiiniik** [comment]
Because no. Do it in your own fork, case closed.

**Comment by Sergeanur** [comment]
The txd files we provide are either fixes from PS2 version or required for new features to work. We do not use HQ recreations made by someone else. Please stop posting these.
