### ISSUE TITLE
[reVC] Helicopters clip through water

### ISSUE THREAD

**Issue by Zbignyev** [GTAmodding/re3#1296]
**Describe the bug**
If you dive a chopper into the water fast enough the helicopter clips right through the water.

**To Reproduce**
When in a helicopter, dive into the water using the lean up/down key. You can use any chopper to reproduce this bug except for the Sea Sparrow (video below). 

**Expected behavior**
The helicopter should remain on the surface of the water and Tommy should drown (poor Tommy).

**Screenshots**
![Zrzut ekranu 2021-08-14 o 20 20 34](https://user-images.githubusercontent.com/52549982/129458681-c32de327-da13-411b-bfa7-6986ef5fe147.png)

**Version**

https://user-images.githubusercontent.com/52549982/129458462-b87d6e2e-fe58-4a8d-ae86-e8b1b311423d.mp4

**Comment by Nick007J** [comment]
should be fixed after https://github.com/GTAmodding/re3/commit/eadf0496bf2b365938b64f5f239d0c353ce9770e
