### ISSUE TITLE
Tursimo does not complete after finishing every other mission and collectibles

### ISSUE THREAD

**Issue by samy-k97** [GTAmodding/re3#1314]
**Describe the bug**
Upon completing every mission and collectibles except the Payphone missions, it is impossible to go beyond "Turismo" at the El Burro booth. Even after completing the mission and save, the save name remains on "The Exchange" which could mean that the game doesn't recognise the completion of "Tursimo"

**To Reproduce**
- Complete every Mission and Collectibles (with the exception of the Payphone missions)
- Complete "Turismo"
- Go to the payphone and the mission "Tursimo" will start again

**Expected behavior**
- Going through the payphone start the next mission

**Screenshots**
![Screenshot from 2021-08-23 16-21-31](https://user-images.githubusercontent.com/66317077/130474783-4a72ca42-3ae9-4fa6-840b-3ca3e43f1054.png)

**Version**
Tell us what version you're running. Find out using the debug menu (Ctrl-M, Debug -> Version Text)
If you send a screenshot just enable it beforehand.

**Comment by samy-k97** [comment]
[GTA3sf1.zip](https://github.com/GTAmodding/re3/files/7033114/GTA3sf1.zip)
Save file if needed

**Comment by ClaudeLib** [comment]
Have you checked if it happens in vanilla game as well?
