### ISSUE TITLE
Player can't move in the new game.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#132]
Player won't be able to move and get stuck after:
You'l launch the game > Start a new game>and then quickly start a new game again.
Result:
![GTA3 12 07 2019 19_02_07](https://user-images.githubusercontent.com/30195961/61145438-bc902d00-a4d7-11e9-80ea-407fef989555.png)
(Player will stuck in air if you'l jump)
(Player will be jogging in place without moving forward if you'l try to go forward)

Additional info that will might help to trace this issue:
After you load up the save game (after steps above)
Claude will still be locked from jogging and jumping will make him stuck however:
If you decide to use flamethrower it will use Shotgun animation and also no bullets/fire will come out
![GTA3 12 07 2019 19_07_12](https://user-images.githubusercontent.com/30195961/61145852-c9615080-a4d8-11e9-819a-0b62bb041f44.png)
If you decide to throw a grenade/molotov none will throw out of Claude's hands
![GTA3 12 07 2019 19_12_28](https://user-images.githubusercontent.com/30195961/61145938-04fc1a80-a4d9-11e9-835c-7dc054f2a610.png)
If you decide to use rocket launcher and shoot under the player he'l be stuck laying on the ground forever
![GTA3 12 07 2019 19_12_09](https://user-images.githubusercontent.com/30195961/61145967-1c3b0800-a4d9-11e9-9764-80b4e8f60286.png)
And if you' try to shoot any other weapon the animation will play once (no bullets will fire) and the player will lock again idling (you wont be able to switch weapons or fire again from that point)
![GTA3 12 07 2019 19_15_16](https://user-images.githubusercontent.com/30195961/61146086-6fad5600-a4d9-11e9-8012-b54cc51b788e.png)

And if you'l try to reload again the same will happen as after first loading of the savegame (the game will load significantly longer too, this issue causes it)

**Comment by Nick007J** [comment]
Very likely this is fixed by https://github.com/GTAmodding/re3/pull/179/commits/ebbcd92de28d37f1dd36c9120f92c958e394ff75
