### ISSUE TITLE
[reVC] Add the higher-quality KCHAT & VCPR

### ISSUE THREAD

**Issue by BreakinBenny** [GTAmodding/re3#1326]
**Describe the bug**
It's evident that PS2 discs could hold much more data than the CDs we might've had back in the early 2000's, but it's hard to not notice K-CHAT and VCPR sound grainy and low-quality in the PC version.

**To Reproduce**
...I guess it doesn't have to be demonstrated, but I know the files provided with the [Leftover Fixes](https://gtaforums.com/topic/750757-vice-city-the-leftovers-fix/) have noticably larger file sizes than the PC (and Steam) ones. Feel free to listen to the two ADF files side-by-side if you have to!

**Version**
Tell us what version you're running. Find out using the debug menu (Ctrl-M, Debug -> Version Text)
If you send a screenshot just enable it beforehand.

**Comment by withmorten** [comment]
Not within the scope of this project.
