### ISSUE TITLE
NPC'S react to the gun shoots like they'd see a dead body.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#144]
(broken event's code)
video for a reference:
https://streamable.com/xilgv
One more event's issue -
Peds scream and run away when Diablos hit Claude, that doesnt happen in the original.
Video reference for this issue:
https://streamable.com/mozs7

**Comment by aap** [comment]
fixed by f63c614d6aace99bc2d63ffa187f96d215f4369b
