### ISSUE TITLE
'Gone Fishing Softlock"

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#173]
Mission Gone Fishing will softlock when approaching the Ghost boat.
https://streamable.com/fg8xr

**Comment by Nick007J** [comment]
Original game has similar issue but to lesser extent, which should be noticed after this fix: https://github.com/GTAmodding/re3/pull/181/commits/d3ddfd8e408c7a8bef92f1276ae4e433b5d0af5d
