### ISSUE TITLE
Damage bar can become misplaced/broken.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#174]
Damage bar can break in each mission that has it, breaks in many different ways, one of encounteres:
![GTA3 28 07 2019 21_36_09](https://user-images.githubusercontent.com/30195961/62034933-23f3ef80-b1ef-11e9-8cfd-745b0cb51e07.png)
(it became more then full at one point)

**Comment by Noskillx** [comment]
Haven't seen the issue for a long while - closing

**Comment by erorcun** [comment]
I believe I've fixed that, so closing it.

**Comment by erorcun** [comment]
It seems this continues...

**Comment by erorcun** [comment]
This may be fixed (if still continues) with https://github.com/GTAmodding/re3/commit/42ff0f7c586b6700dea7729e9f4e1fa5bd42fc96#diff-73fe93df60d477ac0f0d24b48cf1bc12

And https://github.com/GTAmodding/re3/commit/f9316d9cc3cfb748366758c41cf02634b6df9a08#diff-93ef7a9acad2c6fe0854f857b4084bef puts an assert there in case damage value exceeds 100, so this issue needs to be checked again...

**Comment by Noskillx** [comment]
this looks fixed.
