### ISSUE TITLE
Can't save the game.

### ISSUE THREAD

**Issue by gennariarmando** [GTAmodding/re3#21]
Game crashes when trying to save to a slot, also the slot get corrupted.
This seems to happen only on default "main.scm" but not on the stripped one.

![slot](https://user-images.githubusercontent.com/24763112/59590723-f9d9e880-90ec-11e9-90d5-7045676078f8.jpg)

**Comment by aap** [comment]
After the first mission I tried to save and got a crash at 4539AF
