### ISSUE TITLE
Path finding for Peds is broke.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#236]
Example: Curtly bob in "Cutting the grass" after the cutscene has ran on his own on the edge of the bay and then fell into the water next to the ship without the player doing anything. He was totally ignoring his scripted path.

**Comment by erorcun** [comment]
these commits fixed it

https://github.com/GTAmodding/re3/commit/37f0bbc05e87a2a7c0858c6da4a6d51c485fdf64
https://github.com/GTAmodding/re3/commit/9d2b7a99b3c01483329891fcb01e13a5a536bc0a
https://github.com/GTAmodding/re3/commit/5c36eae89f6b256badbe8ff665bec1660220d453
