### ISSUE TITLE
Pedestrian have issues with entering van's during "The Fuzz Ball"

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#301]
New passangers totally ignore the fact that the front passanger seat is already occupied by other ped.
They keep entering front seat even through back seats are free,
and then when the front seat is already occupied and new passangers opens up the front door previous front sitting passanger gets teleported to the back of the van and new pasanger replaces old one in the front seat, example:
(You can see the "brown" clothing hooker sitting on a front seat)

![](https://cdn.discordapp.com/attachments/363012096725745665/672789073966137384/unknown.png)

and then she gets teleported to the back when the 'pink hooker" starts "open door" animation:

![](https://cdn.discordapp.com/attachments/363012096725745665/672789625126780968/unknown.png)

**Comment by erorcun** [comment]
Fixed with https://github.com/GTAmodding/re3/pull/322
