### ISSUE TITLE
Weird LOD-Map showing up above me after dying in the water when swimming from Stauton to Portland

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#308]
Weird LOD-Map showing up above me in Portland  after dying in the water when swimming from Stauton to Portland

![](https://cdn.discordapp.com/attachments/363012096725745665/672905950889246721/unknown.png)

![](https://cdn.discordapp.com/attachments/363012096725745665/672905987631611914/unknown.png)

![](https://cdn.discordapp.com/attachments/672805672316043264/672906159295954954/unknown.png)

![](https://cdn.discordapp.com/attachments/672805672316043264/672906198302851102/unknown.png)

![](https://cdn.discordapp.com/attachments/672805672316043264/672906278384828486/unknown.png)

![](https://cdn.discordapp.com/attachments/672805672316043264/672910902873292810/unknown.png)

![](https://cdn.discordapp.com/attachments/672805672316043264/672910997329281042/unknown.png)

![](https://cdn.discordapp.com/attachments/672805672316043264/672910751169511454/unknown.png)

**Comment by Sergeanur** [comment]
Fixed
