### ISSUE TITLE
You can't back out of the "save game" menu with esc button.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#314]
![image](https://user-images.githubusercontent.com/30195961/73600600-24c95d80-4553-11ea-80c8-c21a380fb9aa.png)
You cannot back out with the "esc" button out of this "save game?" menu back into the game,like you can back out from this one:
![image](https://user-images.githubusercontent.com/30195961/73600611-475b7680-4553-11ea-8c5b-1d30c401ce8b.png)

**Comment by erorcun** [comment]
this is due to nature of a ps2 screen. and i can't make esc work in a near future because ProcessButtonPresses isn't reversed yet and it needs a hell of a work.

**Comment by erorcun** [comment]
Will be "fixed" with https://github.com/GTAmodding/re3/pull/348
