### ISSUE TITLE
The vehicle name is blinking/overlapping.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#317]
[Original Game Bug] The vehicle name is blinking/overlapping with "wasted" text if both are displayed at the same time. To reproduce: enter a vehicle and quickly type bang bang bang to blow yourself up, you'l clearly see it blinking.

**Comment by erorcun** [comment]
now vehicle names are removed when there is wasted/busted text with https://github.com/GTAmodding/re3/pull/472
