### ISSUE TITLE
Cars can make weird turns

### ISSUE THREAD

**Issue by erorcun** [GTAmodding/re3#330]
Like
![resim](https://user-images.githubusercontent.com/6575995/74862806-d216e080-535d-11ea-834e-83eda67adc98.png)

I've also seen one in Porter Tunnel.

Reported by Noskillx

**Comment by onurctirtir** [comment]
Does it differ by cars or depend on the surface that you're driving the car ?

**Comment by erorcun** [comment]
Same weird behaviour exists across all cars and surfaces afaik

**Comment by PerikiyoXD** [comment]
Maybe PathNode related?

**Comment by Nick007J** [comment]
Chance is this is fixed after https://github.com/GTAmodding/re3/pull/508

**Comment by Noskillx** [comment]
Seems fixed from my observation.
