### ISSUE TITLE
Cars can have black parts some time

### ISSUE THREAD

**Issue by erorcun** [GTAmodding/re3#331]
Seems like body goes black and damage parts/wheels preserve the normal color/behaviour
Changes by camera angle

The Pony in the away
![resim](https://user-images.githubusercontent.com/6575995/74862925-05596f80-535e-11ea-84b5-9b292117dfa0.png)

Reported by Dominik

**Comment by aap** [comment]
Should be fixed now. Please confirm. I'm slightly worried by the cause though. Vehicles had a pixel shader set from previous rendering. Where did that come from?

**Comment by erorcun** [comment]
I can confirm it's fixed
