### ISSUE TITLE
Glasses near Staunton safehouse isn't see-through

### ISSUE THREAD

**Issue by erorcun** [GTAmodding/re3#341]
![resim](https://user-images.githubusercontent.com/6575995/75673371-de6f3780-5c93-11ea-8a8a-9199d53ec19c.png)

**Comment by onurctirtir** [comment]
can you share the exact issue and steps to reproduce the bug as well ?

**Comment by Noskillx** [comment]
FacePalm, this is an original game bug and has nothing to do with code - map issue which was fixed in GTA LCS.

**Comment by erorcun** [comment]
no, they're also see through in gta 3 :)

**Comment by erorcun** [comment]
probably fixed with https://github.com/GTAmodding/re3/commit/398cc6bbec2ca16fbff7be3de0e421957ae36192
