### ISSUE TITLE
The radio icons in the settings are in wrong order.

### ISSUE THREAD

**Issue by ClaudeLib** [GTAmodding/re3#398]
![20200410150722_1](https://user-images.githubusercontent.com/5920490/78983292-653dec80-7b3d-11ea-81bd-36eb5d38927d.jpg)

This is how they should look:
https://images.pcgamingwiki.com/8/8c/Grand_Theft_Auto_III_Audio.png

**Comment by erorcun** [comment]
Will be fixed with https://github.com/GTAmodding/re3/pull/464
