### ISSUE TITLE
Game crashes during saving and your savegame becomes corrupted.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#417]
![](https://cdn.discordapp.com/attachments/582894364737404963/699611514256097340/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699611569088102480/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699611608384667668/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699622849266319440/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699622901292335174/unknown.png)

**Comment by Sergeanur** [comment]
Fixed
