### ISSUE TITLE
Car thief's can glitch themself and player during a steal attampt.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#419]
![](https://cdn.discordapp.com/attachments/582894364737404963/699584761592545280/unknown.png)
this is the carjacker bug
he entered my patriot i started driving he suddently got "detached" from sitting position and fall through and he stands idle
and then my patriot started to break
and Claude exited it with exit animation
and is frozen in place now just like that ped ^
but if you press enter and get back into it it all works

**Comment by Noskillx** [comment]
as of 18.04.2020 it still happens with additional issues to this issue, the thief now dies instnantly after he'l teleport out of my vehicle leaving no blood, just an outline and money instantly.

**Comment by erorcun** [comment]
fixed with https://github.com/GTAmodding/re3/pull/473
