### ISSUE TITLE
Player is invisible through vehicle windows and sometimes windows turn into "blue hell gate" (doesn't happen in original)

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#420]
![](https://cdn.discordapp.com/attachments/582894364737404963/699615537667375134/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699615404598755398/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699748070522486885/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699748453969821796/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699748858812563506/unknown.png)

**Comment by Sergeanur** [comment]
Does the console spam with "Ran out of space in alpha entity list" here?

**Comment by Noskillx** [comment]
@Sergeanur Yes, it did here.

**Comment by Sergeanur** [comment]
Should be fixed now.
