### ISSUE TITLE
Make the game fall back to using radar tiles for the pause map if the map images are not found inside menu.txd.

### ISSUE THREAD

**Issue by ClaudeLib** [GTAmodding/re3#424]

**Comment by kattjevfel** [comment]
Is there any progress on this? It appears my copy of menu.txd (steam version of game) doesn't have any map related stuff in menu.txd so I'm just getting one big blank screen.

**Comment by erorcun** [comment]
we "fixed" that by not showing the map menu, when map textures aren't found
