### ISSUE TITLE
Crash after stealing car through passenger's seat on Release build

### ISSUE THREAD

**Issue by Sergeanur** [GTAmodding/re3#425]
Game crashes in CPed::PedSetOutCarCB somewhere an SetObjective. Doesn't crash on Debug or with noinline set for SetObjective. Needs further research.

**Comment by Sergeanur** [comment]
Confirmed to be a compiler bug. Added noinline for problematic function as a workaraound until compiler is fixed 669bbe3c.

**Comment by x87** [comment]
@Sergeanur was the compiler issue reported anywhere? can you link the ticket?

**Comment by Nick007J** [comment]
@x87 https://developercommunity.visualstudio.com/content/problem/1006957/incorrectly-generated-code-for-switch-statement-in.html

**Comment by Calinou** [comment]
Should this issue be closed? The original issue appears to be resolved.

**Comment by erorcun** [comment]
Reportedly MS fixed it and updated the VS.
