### ISSUE TITLE
Game is dying/dropping to 1 FPS if the fences are touched/destroyed.

### ISSUE THREAD

**Issue by Domiiniik** [GTAmodding/re3#427]
![image](https://user-images.githubusercontent.com/30195961/79237621-ac461d80-7e6e-11ea-9345-6b210deccf27.png)

**Comment by aap** [comment]
Maybe try a release build?

**Comment by Noskillx** [comment]
> Maybe try a release build?

I tried, result is the same.

**Comment by ShFil119** [comment]
I tried to reproduce, but it didn't have such big impact.

Can you try with "show timebars" enabled?

**Comment by Domiiniik** [comment]
My PC is such a p000p
