### ISSUE TITLE
Airport doors didn't fully close in "Marked Man" after a cutscene.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#433]
![](https://cdn.discordapp.com/attachments/582894364737404963/699749054577377350/unknown.png)
another script bug? these doors kept weirdly opening/closing when Ray entered.
but they ended up bit open after the cutscene was done
they should be closed

**Comment by erorcun** [comment]
should be fixed with https://github.com/GTAmodding/re3/pull/465
they're still a bit open in the end, but i think that also happens on vanilla
