### ISSUE TITLE
Bait crash

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#438]
![](https://cdn.discordapp.com/attachments/582894364737404963/699751623110426684/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699751560112111767/unknown.png)
in the mission "BAIT" happen when i got 2 sentinel's to follow me at the same time
then one of them stopped following and only second one was
and then - Crash
i baited into the trap the one near the "LCS Donald's homeless house"
they killed him
and then i went to Cedar Grove to make the one next to Catalina's house follow me and then i went for the one near the dam

**Comment by Nick007J** [comment]
Should be fixed after https://github.com/GTAmodding/re3/commit/1fd7b0288c00486721faaff6af4d9d36ebe9b57d
