### ISSUE TITLE
Missing 2DFX.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#44]
For example, lugi's sex club lights which should be displayed at night are gone.

![](https://cdn.discordapp.com/attachments/463014238521131010/592743801630621696/unknown.png)

![](https://cdn.discordapp.com/attachments/363012096725745665/592747009325269021/unknown.png)
GTA III picture for reference:

![](https://cdn.discordapp.com/attachments/363012096725745665/592747261625237504/unknown.png)

**Comment by aap** [comment]
Works for me. Someone else please check too.

**Comment by aap** [comment]
I misunderstood, and fixed it.
