### ISSUE TITLE
Convoy mission crash when approaching Securicar.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#442]
![](https://cdn.discordapp.com/attachments/582894364737404963/699765601803173908/unknown.png)

![](https://cdn.discordapp.com/attachments/582894364737404963/699765715502235740/unknown.png)

**Comment by Nick007J** [comment]
Fixed by https://github.com/GTAmodding/re3/commit/3517f3f1a1c41d3a5334f8676c60f7cb87d4bc4c
