### ISSUE TITLE
Gang members (cartel, mafia) are not hostile towards Claude.

### ISSUE THREAD

**Issue by ClaudeLib** [GTAmodding/re3#45]
They do spawn, weapons in hands, but they just peacefully walk by. If you attack them, they strike back. After removing re3 and loading the same savefile they revert to their normal behavior (if "shoot on sight" can be described as normal).

**Comment by aap** [comment]
fixed

**Comment by ShFil119** [comment]
Ref:
b19e1d369ce71681ac48c9e8bbce8f419261ac77
