### ISSUE TITLE
[Original game bug] Wrecked Car will still have alarm going once you destroy it.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#450]
![image](https://user-images.githubusercontent.com/30195961/79398558-4302ff00-7f81-11ea-8b41-edba63696cf6.png)

**Comment by erorcun** [comment]
Fixed with https://github.com/GTAmodding/re3/pull/451

**Comment by erorcun** [comment]
Actually lights was still there, but now it should be fixed for real (III that is, VC already has it fixed)
