### ISSUE TITLE
Car engine sound pitch doesn't change when shifting gears

### ISSUE THREAD

**Issue by jinxgtaf** [GTAmodding/re3#461]

**Comment by ShFil119** [comment]
1) player car or cars of others?
2) can you give sample/example? it'd make much easier to track issue

**Comment by jinxgtaf** [comment]
1. player car. npc ones use a different sound
2. kuruma in the beginning. compare between re3 and vanilla

**Comment by ShFil119** [comment]
There are two separate snippets of code to process sound of vehicle engine. One for player, one for npc. 

Looks like at least code for player has a bug.

**Comment by Sergeanur** [comment]
Should be fixed.
