### ISSUE TITLE
Claude won't close car doors

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#468]
If you open driver doors and then cancel getting in and you will get in from the passanger side doors Claude will refuse to close the driver doors while sitting in and the doors won't be moving (effected by physics).
![image](https://user-images.githubusercontent.com/30195961/79637113-ce94af80-817c-11ea-84c1-be19fbffad3e.png)

**Comment by erorcun** [comment]
will be fixed with https://github.com/GTAmodding/re3/pull/475
