### ISSUE TITLE
Menu sliders are off scale.

### ISSUE THREAD

**Issue by gennariarmando** [GTAmodding/re3#471]
Sliders in menu are wrong, result in different positions using different aspect ratios.
![Resident Evil 3 Remake Screenshot 2020 04 18 - 18 07 35 10](https://user-images.githubusercontent.com/24763112/79642725-863ab900-819f-11ea-8cf4-a28db576506d.png)
![Resident Evil 3 Remake Screenshot 2020 04 18 - 18 07 36 92](https://user-images.githubusercontent.com/24763112/79642728-88047c80-819f-11ea-9efd-8a473d7adb96.png)

**Comment by erorcun** [comment]
this doesn't happen on me, so I never got what you mean. fix is on the way.
