### ISSUE TITLE
Mouse Controlled Steering is set to ON when launching without the SET file.

### ISSUE THREAD

**Issue by ClaudeLib** [GTAmodding/re3#484]
Also, both original GTA III and reIII have Invert Mouse Vertically initially set to OFF, but after clicking on Restore Defaults, it sets to ON in both games, IMHO this is wrong too.

**Comment by gennariarmando** [comment]
Will be fixed in my next commit.

**Comment by Nick007J** [comment]
Please check if this is solved after https://github.com/GTAmodding/re3/commit/4b883f2b40f488a67479e3c83d9c1c5686375364.

**Comment by ClaudeLib** [comment]
Yup, now it behaves exactly like in original game, thank you.
