### ISSUE TITLE
Bug with DestroyVehicleAndDriverAndPassengers

### ISSUE THREAD

**Issue by jack9267** [GTAmodding/re3#486]
In the code there is an #ifdef FIX_BUGS around a call to CDarkel::RegisterKillByPlayer in the mentioned function.

https://github.com/GTAmodding/re3/blob/master/src/vehicles/Vehicle.cpp#L1007

This change breaks taking a passenger to the car crusher and having that passenger count as being killed by the player. Which the player is responsible for that death so how is it "unfair" ?

The code is used by CGarages, it's only the car crusher that can make use of the passengers though.
Garages won't close if it's a mission vehicle or if theres passengers (so can't even cause the "unfair" part)
The car crusher always works (even if mission vehicle) so we could take 8ball to the car crusher and indeed the player is responsible for his death.

**Comment by Nick007J** [comment]
Agree. Fixed in https://github.com/GTAmodding/re3/commit/458eb3a4f079af4c118357fb3bd0594626151e9d
