### ISSUE TITLE
Particles from gun shooting is misalinged from certain height

### ISSUE THREAD

**Issue by Tomasak** [GTAmodding/re3#511]
Happens on vanilla tho.
![Resident Evil 3 Remake Screenshot 2020 05 05 - 13 35 53 88](https://user-images.githubusercontent.com/11007651/81062072-a5db1c80-8ed5-11ea-96bf-f9f406105f06.png)
![Grand Theft Auto 3 Screenshot 2020 05 05 - 13 37 18 47](https://user-images.githubusercontent.com/11007651/81062100-b390a200-8ed5-11ea-9423-cce36dd2868a.png)

**Comment by ZLau92** [comment]
Funny enough, unable to replicate current re3.
But I can replicate in vanilla/ps2.

**Comment by Tomasak** [comment]
same. closing
