### ISSUE TITLE
Resizing the window in windowed mode has issues.

### ISSUE THREAD

**Issue by Domiiniik** [GTAmodding/re3#589]
Game will have a black spot in the place where you resized the window in x axis however once you'l resize the window in y axis after resizing in x axis the black bars will fix themself however trails effect will still be cut and won't get applied on the resized portion of the screen:
![image](https://user-images.githubusercontent.com/30195961/82838127-80857100-9ecb-11ea-9b9d-a1a03284382c.png)
![image](https://user-images.githubusercontent.com/30195961/82838139-8c713300-9ecb-11ea-92ff-4c10095de466.png)

**Comment by erorcun** [comment]
fixed a while ago (RwHelper.cpp)
