### ISSUE TITLE
Free camera player movement sometimes glitches out.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#590]
bug:
https://cdn.discordapp.com/attachments/582894364737404963/714247122920276098/GTA3_2020-05-25_00-40-56.mp4
without bug for comparison:
https://cdn.discordapp.com/attachments/582894364737404963/714247453628432454/GTA3_2020-05-25_00-43-25.mp4
issue happens randomly - it fixes itself once you'l reload the savegame

**Comment by erorcun** [comment]
should be fixed on both master and miami now
