### ISSUE TITLE
FPS goes to 30-40 from 60 after water splash in fullscreen

### ISSUE THREAD

**Issue by majesticCoding** [GTAmodding/re3#598]
Using lock on 60 FPS it's possible to get 30 after water splash in fullscreen:
![image](https://user-images.githubusercontent.com/60937741/82905999-738f6e80-9f19-11ea-8c3d-bcd78d55fc29.png)

But if I use windowed mode with the same screen size it's almost ok:
![image](https://user-images.githubusercontent.com/60937741/82906064-8b66f280-9f19-11ea-8be6-3c30f405b0ff.png)

**Comment by aap** [comment]
Have you tried disabling vsynch?

**Comment by majesticCoding** [comment]
No, but I tried now the latest librw update, and with such things doesn't happen; hence, I think the issue can be closed

**Comment by Calinou** [comment]
This issue can probably be closed now :slightly_smiling_face:
