### ISSUE TITLE
Request - Radio scroll to previous station

### ISSUE THREAD

**Issue by Tomasak** [GTAmodding/re3#628]
Add ability to scroll radio previous station (like in SA) with mouse wheel down

**Comment by ClaudeLib** [comment]
Either go to previous radio station with MWD _if_ the control for the next one is set to MWU, or add a separate control.

**Comment by erorcun** [comment]
ok: https://github.com/GTAmodding/re3/pull/886

**Comment by Tomasak** [comment]
I would like to reopen this as:
VC and LCS didnt get this improvement
There is no way to rebind scroll back button
The "Off" text is weird, why it couldnt be Radio off like stories and SA? This got custom gxt, so one more line wouldn't hurt

**Comment by erorcun** [comment]
now this is also on VC, and "off" has been changed with "radio off" but I can't say anything about extra binding

**Comment by Sergeanur** [comment]
Implemented.
