### ISSUE TITLE
Game is not displaying distance travelled on foot and in car propertly,

### ISSUE THREAD

**Issue by Domiiniik** [GTAmodding/re3#645]
Game is not displaying distance travelled on foot and in car propertly, it 's always 0.00.
![image](https://user-images.githubusercontent.com/30195961/86402516-3e123980-bcac-11ea-9fb6-4c2fec0122f6.png)

**Comment by ShFil119** [comment]
Fixed by bf2624692c6b04c25275ddb35b7da1cf1e6a9953
