### ISSUE TITLE
Some menu text is wrong

### ISSUE THREAD

**Issue by Krutonium** [GTAmodding/re3#714]
I'm running the game with the Steam release of GTA 3, on Arch Linux, built with `make config=release_linux-amd64-librw_gl3_glfw-oal`

![20200926022734_1](https://user-images.githubusercontent.com/3945538/94332070-dbc19000-ff9f-11ea-8241-0a31b90091bb.jpg)
![20200926022738_1](https://user-images.githubusercontent.com/3945538/94332072-dbc19000-ff9f-11ea-891a-f82af6c63d01.jpg)
![20200926022742_1](https://user-images.githubusercontent.com/3945538/94332073-dc5a2680-ff9f-11ea-8734-a30c451c1195.jpg)

**Comment by Sergeanur** [comment]
Get GXT files from https://github.com/GTAmodding/re3/tree/master/gamefiles/TEXT

**Comment by Krutonium** [comment]
There is still an issue - In `Display Setup` one of the Entries is still called `F`

**Comment by erorcun** [comment]
Yeah, we'll fix it soon

**Comment by Krutonium** [comment]
In the meantime, what does F do?

**Comment by erorcun** [comment]
:D it was supposed to be "Free Cam". i.e. enables GTA SA camera on vehicles, but I don't know is Switch's right stick tied to camera on vehicle.

Should be fixed now, but needs verification.

**Comment by erorcun** [comment]
Fixed, but don't forget to get update american.gxt.
