### ISSUE TITLE
Can't bind auxiliary mouse buttons to in-car Look Left/Look Right on Linux

### ISSUE THREAD

**Issue by Calinou** [GTAmodding/re3#725]
**OS:** Fedora 32
**GPU:** GeForce GTX 1080 (NVIDIA 450.66)
**re3 version:** Git 70aac0f460a9e57956de00ae5d84d8bb4bf4643c

I like using AUX1 and AUX2 (auxiliary Back/Forward buttons on my mouse) to look left and right while in a car. This works when running the original executable in WINE, but I can't bind them in the key configuration menu. Nothing happens when pressing those keys.

**Comment by parkerlreed** [comment]
As mentioned elsewhere, the mapping screen may only be accepting inputs from the first detected controller, regardless of which one is in use. 

https://github.com/GTAmodding/re3/issues/710#issuecomment-699813157

**Comment by erorcun** [comment]
actually it will always accept input from keyboard and mouse, alongside the controller.

it is expected that AUX buttons of mouse won't be registered. it was TODO, and will be fixed soon.

**Comment by erorcun** [comment]
Fixed.
