### ISSUE TITLE
Use the "Auto" aspect ratio setting by default

### ISSUE THREAD

**Issue by Calinou** [GTAmodding/re3#728]
While the game [uses the native resolution by default](https://github.com/GTAmodding/re3/blob/5144b5051ccf7bbbbbf6022e7526431dd8fe2fa8/src/core/config.h#L204), it still keeps the 4:3 aspect ratio even if the resolution isn't 4:3.

I think it would make more sense to use the "Auto" aspect ratio setting by default. This way, the game looks correct on widescreen displays out of the box.

**Comment by erorcun** [comment]
done
