### ISSUE TITLE
Future ideas

### ISSUE THREAD

**Issue by DartPower** [GTAmodding/re3#729]
Hi, you are planning these or not?

1) Multiplayer support (OpenSpy or another netcode?)
2) SDK? (Editors, Map Editor, Interface and Loading bar editors and etc?)
3) Support for fully creating game from null (as game engine) 

Before thanks a lot for answers :)

**Comment by Sergeanur** [comment]
No, we don't plan anything like that.

**Comment by DartPower** [comment]
> No, we don't plan anything like that.

But why you realised the edit mode, but you write "don't plan anything"? Where the logic?
Can you answer normally?

**Comment by Sergeanur** [comment]
What edit mode are you talking about?

**Comment by DartPower** [comment]
In debug mode

**Comment by Sergeanur** [comment]
Okay so what about a debug mode? You mean a debug camera? That's not an edit mode.

**Comment by DartPower** [comment]
Okay :(
