### ISSUE TITLE
2 Handed weapons can shoot while jogging

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#74]
2 Handed weapons can shoot while jogging after you stop shooting and hold an arrow to walk, the weapon still shoots without holding a mouse button while jogging:

![](https://cdn.discordapp.com/attachments/592994941760962560/594543591301316638/unknown.png)

**Comment by erorcun** [comment]
This bug isn't caused by CPed btw, I've removed all CPed functions and the bug was still there. 
Probably CWeaponInfo or most probably RpAnimBlend, CAnimBlendAssociation etc. related.

**Comment by Noskillx** [comment]
Erorcun fixed the issue - *btw weapon anim bug was my code actually. weapon.dat loading wasn't correct, all weapons had second anim as "0" if they don't have one. and game was thinking it's enabled during walking with gun* - Closed
