### ISSUE TITLE
reVC: Vertical mouse sensitivity isn't affected by the mouse sensitivity setting and remains very high

### ISSUE THREAD

**Issue by Calinou** [GTAmodding/re3#744]
**OS:** Fedora 32
**reVC version:** Git https://github.com/GTAmodding/re3/commit/9d53b738cc064f722cf18f37515daeb1fa8e443d

To get a reasonable mouse sensitivity given my OS settings, I have to decrease the mouse sensitivity in GTA III/VC to 2 or 3 bars in the mouse settings menu. This works fine in vanilla GTA III/VC and re3, but in reVC, it seems the mouse sensitivity isn't affected by this slider.

PS: I've noticed that even when I do this in vanilla, the vertical mouse sensitivity remains higher no matter what. Would it be possible to have a separate slider for horizontal and vertical mouse sensitivity? I'd like both of them to be equal, as is common in FPS games.

**Comment by erorcun** [comment]
it's been done already, but forgot to close this. note that vertical will always be 0.005 higher then horizontal sensitivity, as R* had intended.

also high-dpi still isn't handled nicely, saying this just in case your problem is related to that.
