### ISSUE TITLE
macOS: in-game mouse support broken

### ISSUE THREAD

**Issue by Tatsh** [GTAmodding/re3#749]
Mouse movement works great in the menus, but in-game movement does nothing. Middle-click works.

This also affects the touchpad.

As far as I know, there is no way to turn around without the mouse in the game.

**Comment by Tatsh** [comment]
Could this bug be related to GLFW?

**Comment by MrYadro** [comment]
Seems like it's fixed now

**Comment by Tatsh** [comment]
Yes, it seems so. Closing.
