### ISSUE TITLE
Management issues on Linux

### ISSUE THREAD

**Issue by DJs3000** [GTAmodding/re3#764]
I ran RE3 on Linux but there is a problem, the character is constantly going to the left. This is a regular Debian-like distribution, only the processor architecture is exotic(Elbrus 8C - VLIW).
[Videos.zip](https://github.com/GTAmodding/re3/files/5370978/Videos.zip)

**Comment by erorcun** [comment]
this is a known issue, I forgot about it. will fix it during the day.

**Comment by DJs3000** [comment]
Thanks!

**Comment by DJs3000** [comment]
Hello! I'm really looking forward to fixing the bug :)

**Comment by parkerlreed** [comment]
For reference the issue is here https://github.com/GTAmodding/re3/issues/710

As noted, fix should be implemented soon

**Comment by erorcun** [comment]
fixed, i hope

**Comment by DJs3000** [comment]
The problem remained. I connected another mouse and the problem was solved. There is a problem with the "Razer DeathAdder 2013" mouse, but there is no problem with the simplest mouse. "Razer" is defined as a gamepad. :)

**Comment by erorcun** [comment]
do you see your mouse's name when you open `re3.ini` in game root directory? if so, can you try after deleting it and trying again?

**Comment by DJs3000** [comment]
Yesterday I built the latest git version and the problem is solved.
