### ISSUE TITLE
After a while of playing the audio gets completely broken.

### ISSUE THREAD

**Issue by niobium93** [GTAmodding/re3#784]
[Example video](https://youtu.be/3L23Tv3sw30)
After playing about 3 to 4 missions various sounds in the game seem to become randomized. The sounds your car makes, the pedestrian cars, footsteps, the menu - everything.

**Comment by Sergeanur** [comment]
Is this an OAL build?

**Comment by TheOfficialFloW** [comment]
We noticed the same problem on switch and vita ports (also using OAL).

**Comment by hazelnot** [comment]
Ngl this is one of the most hilarious glitches I've ever encountered. It's happened to me too, also on Linux, at some point I was being chased by some cops and their yells were car reversing sounds.

**Comment by niobium93** [comment]
I've been playing on a new build and it seems the issue has been fixed, but now some sounds cut off too early:
[Example video](https://www.youtube.com/watch?v=3kGpve8Obkc)
Not sure if this is related or if I should start a new issue.

**Comment by erorcun** [comment]
yeah, please open a new issue
