### ISSUE TITLE
switch ? - No Skin selection available anymore

### ISSUE THREAD

**Issue by soaresden** [GTAmodding/re3#786]
Hi, i'm using switch version so I don't know if this is only switch version issue.

Because of the PS2 looking menu now, we can't select a skin for the player, is it possible to bring it back ?
thanks !

**Comment by hazelnot** [comment]
The Switch repo is here: https://github.com/AGraber/re3-nx

This one is just for PC

**Comment by soaresden** [comment]
Sorry for inconvenience, since Graber didn't opened the issues tab in his fork I thought I had to post here.
