### ISSUE TITLE
switch ? skip mp3 music and alsways the same music playing

### ISSUE THREAD

**Issue by soaresden** [GTAmodding/re3#787]
Using re3 on switch, every time I play, it's always playing the same song from the beginning.
Is it possible to make it resume or at least let it play like the normal radio ?
Can we skip it by button ? Is it possible to make it random ?
thanks !

**Comment by hazelnot** [comment]
Wrong repo

**Comment by soaresden** [comment]
Sorry for inconvenience, since Graber didn't opened the issues tab in his fork I thought I had to post here.
