### ISSUE TITLE
[reVC] Walking on sand creates bloody footprints

### ISSUE THREAD

**Issue by hazelnot** [GTAmodding/re3#788]
I assume it's because the sand footprints in Vice City use the same code as the bloody footprints but with a different texture, but still, I opened an issue just in case.

![image](https://user-images.githubusercontent.com/10992973/97166638-424bf080-178e-11eb-9796-57c66b69596c.png)

**Comment by kattjevfel** [comment]
Sand must be really rough on his feet :(

**Comment by aap** [comment]
Fixed.
