### ISSUE TITLE
Feature request: Start mission via debug menu

### ISSUE THREAD

**Issue by kattjevfel** [GTAmodding/re3#800]
I noticed a bug where Toni is very quiet in Cipriani's Chauffeur, but I've since overwritten my save, so I can't go back and check if the bug is fixed with a PR or even try bisect it easily. 

So my request is to be able to manually start a mission via debug menu, for easy testing.

**Comment by withmorten** [comment]
I've added that in a PR here, so it will hopefully be available soon: https://github.com/GTAmodding/re3/pull/820

**Comment by kattjevfel** [comment]
I'd give your PR a go but can't due to #813.
