### ISSUE TITLE
Paparazzi purge mission crash

### ISSUE THREAD

**Issue by BoredAlchemist** [GTAmodding/re3#805]
during this mission if you go all the way around portland island chasing the boat when it comes back round near the start docks the game will crash, if you destroy the boat near or before the oil tanker after the cliff face with the hole in it, it will not crash. 
I did not test where the cut off point was before it would crash.

**Comment by BoredAlchemist** [comment]
this is on ps vita by the way

**Comment by hazelnot** [comment]
This repo is just for the PC version, try asking on... wherever they offer support for that (the official repo has issues disabled) or try reproducing it on the PC version and post a log.

**Comment by BoredAlchemist** [comment]
> This repo is just for the PC version, try asking on... wherever they offer support for that (the official repo has issues disabled) or try reproducing it on the PC version and post a log.

thanks, my bad its prob a memory issue on the ps vita so dount it happen on pc

**Comment by erorcun** [comment]
tried this with ASan(address sanitizer) and no crash happened, so I think either we fixed it along the way since this issue opened, or it wasn't happening on PC. closing it.
