### ISSUE TITLE
Remove version splash option

### ISSUE THREAD

**Issue by strikersix23** [GTAmodding/re3#806]
Id like to request way to remove version 1.0 splash text from the top or completly

**Comment by kattjevfel** [comment]
Comment out the following line:
https://github.com/GTAmodding/re3/blob/460f3cea447296cb5757c04108b9ac6becd6c968/src/core/config.h#L173

**Comment by withmorten** [comment]
Which I added to do specifically that :D

**Comment by strikersix23** [comment]
I figured it out vc gets compile errors if using standard comment out
Do this 
//#define DRAW_GAME_VERSION_TEXT
