### ISSUE TITLE
Game repeatedly crashes after shooting down the helicopter in the last mission.

### ISSUE THREAD

**Issue by niobium93** [GTAmodding/re3#807]
I'm on Arch Linux. I could play through the entire game without crashes that happen more than once, but every time I try to finish it this happens:
[Video](https://www.youtube.com/watch?v=qxu8MgZevlk)
[Terminal log](https://gist.github.com/niobium93/501f48b902c0366e99bb80b9c8ec3a53)

**Comment by niobium93** [comment]
I was using a 5 day old re3 build because of #802 but I don't see anything relevant in the commit logs so I assume it still happens. Will retest once I can compile it again.

**Comment by Sergeanur** [comment]
Does it crash with framerate limiter turned on?

**Comment by niobium93** [comment]
Huh. No it doesn't.

**Comment by ShFil119** [comment]
Can you try to run this mission with enabled asan and post here log:
`./premake5Linux gmake2 --with-librw --with-asan`
then run with:
`ASAN_OPTIONS=halt_on_error=1 /re3`
(It would make much easier to debug.)

**Comment by niobium93** [comment]
Sorry, still can't compile due to #802 
Don't feel like downgrading my system to compile a game.
Is there any way to compile without audio support at all?

**Comment by niobium93** [comment]
I compiled with asan and it just crashes on startup now. [log](https://gist.github.com/niobium93/43011fb7614138fe038299fb596dc644)
Am I doing something wrong?

**Comment by withmorten** [comment]
Since this always seems to fix it, did you delete models/txd.img ?
