### ISSUE TITLE
Various effects break with the frame limiter turned off.

### ISSUE THREAD

**Issue by niobium93** [GTAmodding/re3#808]
I'm on Arch Linux. The water splashes behind boats, splashes when driving through puddles and smoke coming off of damaged cars renders wrong without the frame limiter. Smoke also disappears when driving fast and I swear once I couldn't even see the flames before my car exploded, though I can't reproduce that.
[Video with giant water splash effects behind boats](https://www.youtube.com/watch?v=V5NLizJ7YLw)
[Video with a smoking car](https://www.youtube.com/watch?v=_rzZE5W-LwI)

**Comment by kusst** [comment]
It's a known problem which also happens in the vanilla version of the game.
see: https://github.com/GTAmodding/re3/wiki/Frames-as-a-period-of-time

**Comment by erorcun** [comment]
problems with frame limiter off are well-known in gta community, so we don't recommend playing without frame limiter.
closing this and moving your description to our Wiki, thanks.
