### ISSUE TITLE
C(XX)_EXTENSIONS is wrongfully disabled on CMake files.

### ISSUE THREAD

**Issue by AGraber** [GTAmodding/re3#818]
Some functions like `strcasecmp` aren't strictly part of the C(++) standard library, but are available as extensions. When off, they will be not be found when building on CMake beacuse extensions are disabled. The same goes for librw (`strdup`)

Solutions:
- Build own replacements for these functions into the code
- Enable C(XX)_EXTENSIONS on the CMakeFile

I guess the latter would be desirable, If that's the case then I'll make a PR.
Just asking in case you have any other opinions.

**Comment by AGraber** [comment]
Examples of errors:
```
/home/graber/re3-nx/src/animation/AnimManager.cpp:613:6: error: 'strcasecmp' was not declared in this scope; did you mean 'strncmp'?
  613 |   if(strcasecmp(ms_aAnimBlocks[i].name, name) == 0)
      |      ^~~~~~~~~~
      |      strncmp
```

On librw:
```
/home/graber/re3-nx/vendor/librw/src/gl/gl3shader.cpp:40:62: error: 'strdup' was not declared in this scope; did you mean 'strcmp'?
   40 |  uniformRegistry.uniformNames[uniformRegistry.numUniforms] = strdup(name);
      |                                                              ^~~~~~
      |                                                              strcmp
```

**Comment by ShFil119** [comment]
I'm ok with enabling extensions for now
