### ISSUE TITLE
[Question] Any chance of a PS3 port in the far future?

### ISSUE THREAD

**Issue by JejSooS** [GTAmodding/re3#829]
Even though the PS3 has near perfect PS2 compatibility with GTA III, Vice City and so forth it would be nice to have the additions such a rebuild like this could provide on a PS3 such as the ability to use a custom radio station and extras like that.

**Comment by aap** [comment]
It would be very cool, but it's also a lot of work...right now we have higher priority tasks.

**Comment by erorcun** [comment]
even though this doesn't seem possible in near future, i'm moving some things to "Possible improvements" wiki page so I'm closing this.
