### ISSUE TITLE
8-Ball does not go towards the car in "Give Me Liberty".

### ISSUE THREAD

**Issue by ClaudeLib** [GTAmodding/re3#83]
![20190701100142_1](https://user-images.githubusercontent.com/5920490/60411770-bfda0d80-9be7-11e9-9f2b-7e9029e57821.jpg)
Several seconds later he teleports near the car and enters the front right seat though.
![20190701100154_1](https://user-images.githubusercontent.com/5920490/60411792-dbddaf00-9be7-11e9-8014-5b501f8349ac.jpg)

**Comment by ClaudeLib** [comment]
Probably related to this, when I press F near a car, Claude does not turn to it, he starts jogging to where the camera was looking. It is still possible to enter vehicles if you look at the driver door first,
![20190701103334_1](https://user-images.githubusercontent.com/5920490/60412826-24976700-9bec-11e9-84bd-841d49ba7233.jpg)

**Comment by erorcun** [comment]
Fixed.
