### ISSUE TITLE
[reVC] Error: Can't load WILD.ADF

### ISSUE THREAD

**Issue by DartPower** [GTAmodding/re3#832]
Used this build.
https://github.com/GTAmodding/re3/actions/runs/378682176
reVC_Release_win-amd64-librw_d3d9-oal

![image](https://user-images.githubusercontent.com/2005369/100018868-30418a00-2dee-11eb-92c7-fa8a55700ffe.png)
![image](https://user-images.githubusercontent.com/2005369/100018890-3afc1f00-2dee-11eb-9c8a-68102392472d.png)

Tried to rename WILD.adf (originally in dir) in WILD.ADF but error.

**Comment by Sergeanur** [comment]
There's something with your ADF files, they shouldn't all be the same size.

**Comment by DartPower** [comment]
Oooooh... Thanks a lot! Will try to reinstall VC

**Comment by DartPower** [comment]
Thanks a lot! This is really screwed up files.
