### ISSUE TITLE
hydraulics numpad keybinds wrong

### ISSUE THREAD

**Issue by kattjevfel** [GTAmodding/re3#835]
Noticed this when I got into a Yardie, pressing the 4 and 6 would normally make the car jump left and right, and 7 and 2 would be front and back, but that is not the case, instead I get this:

1 - Look left
2 - Look right
3 - Nothing
4 - Jump left
5 - Jump right
6 - Jump front
7 - Nothing
8 - Nothing
9 - Jump back

Gamepad (Xbox 360) works just fine, I'm running debug_linux-x86-librw_gl3_glfw-oal b6da31cfaa021559939ed596d18a27f4db6acebc.

**Comment by Sergeanur** [comment]
Just remap them in the settings? That's default controls from vanilla.

**Comment by kattjevfel** [comment]
> Just remap them in the settings? That's default controls from vanilla.

You can't remap those from what I see.

**Comment by Sergeanur** [comment]
Here they are
![изображение](https://user-images.githubusercontent.com/4450430/100118511-97a71a80-2e7e-11eb-975c-cea818965a84.png)
