### ISSUE TITLE
GTA 3 1.1 Transparent textures are not visible from one side

### ISSUE THREAD

**Issue by Dima353** [GTAmodding/re3#837]
Bellyup car problem, transparent body. 
At train stops there are transparent stairs and perryl, the roofs of stops.
game data files from Steam version.
![1](https://user-images.githubusercontent.com/75039669/100268715-73bf0400-2f66-11eb-9e82-8f50ec60cca0.PNG)
![2](https://user-images.githubusercontent.com/75039669/100268722-77528b00-2f66-11eb-97b6-d1e1cd27d744.PNG)
![3](https://user-images.githubusercontent.com/75039669/100268731-79b4e500-2f66-11eb-8bc6-ea95c4caece5.PNG)

**Comment by aap** [comment]
That's a problem of the backface culling list. I stole it from android but it seems rather incomplete.

**Comment by Dima353** [comment]
> Это проблема списка отбраковки обратной стороны. Я украл его с андроида, но он кажется неполным.

Is this problem solvable?

**Comment by aap** [comment]
we'd have to find more bugged models and then the vita port would need a new release.

**Comment by Dima353** [comment]
> we'd have to find more bugged models and then the vita port would need a new release.

Strange, but in version 1.0 for ps vita, there were no such problems

**Comment by Dima353** [comment]
> we'd have to find more bugged models and then the vita port would need a new release.

Found more

![photo_2020-11-25_22-06-15](https://user-images.githubusercontent.com/75039669/100271405-7e7b9800-2f6a-11eb-996c-d417fb2eb2ac.jpg)

**Comment by Dima353** [comment]
> we'd have to find more bugged models and then the vita port would need a new release.

Checked all cars defect only with Bellyup.

**Comment by aap** [comment]
I have fixed the bug with the belly up and will push it soon. in the meantime feel free to find more buggy objects.

**Comment by Dima353** [comment]
> I have fixed the bug with the belly up and will push it soon. in the meantime feel free to find more buggy objects.
 
Replaced the Bellyup texture with the XBOX version, the transparency is gone, the model is displayed well

**Comment by Dima353** [comment]
> I have fixed the bug with the belly up and will push it soon. in the meantime feel free to find more buggy objects.

Found more
![photo_2020-11-27_00-21-15](https://user-images.githubusercontent.com/75039669/100392124-94f72180-3046-11eb-9856-b93988cc85da.jpg)
![photo_2020-11-27_00-21-28](https://user-images.githubusercontent.com/75039669/100392125-96c0e500-3046-11eb-916e-0a82425b01e0.jpg)

**Comment by ShFil119** [comment]
Should be fixed after: https://github.com/GTAmodding/re3/commit/c2ff1713648384867944e476e97c5be72da71f69
