### ISSUE TITLE
Custom controller pictures for non-PS2 pads

### ISSUE THREAD

**Issue by IlDucci** [GTAmodding/re3#848]
I'm going to continue the non-PS2 controller images discussion from https://github.com/GTAmodding/re3/issues/845 here, related to https://github.com/GTAmodding/re3/pull/454, just so both issues are on topic.

I've done the first pictures, for now for the XBOX 360 controller (this is the end file, I'm willing to share the PSD file. It's vectorized, so it can be resized into HD or higher)
![fe_controller_360](https://user-images.githubusercontent.com/5641681/100539555-a6ebe680-3237-11eb-85ed-f2ec63459888.png)

There's a couple of issues that I'd like to comment. The biggest one is purely physical: buttons are not in the same place as the PS2 controller, so the arrow positioning won't work just like that. The way I see it, there's two ways to solve this: the artist-based way, and the programming-based way.

The artist-based way would consist in adding new positions for the text via code, following the new positions of the arrows. It's visually cleaner.
![fe_controller_360_CUSTOMPERCONTROLLER](https://user-images.githubusercontent.com/5641681/100539622-106bf500-3238-11eb-9fc4-9c2ac8d8ccec.png)

And the programmer-based way would respect the original starting position of the arrows, but would look a bit more confusing (specially when the left stick and the directional pad are reversed, just like in this case).
![fe_controller_360_PRESERVINGPS2POSITIONS](https://user-images.githubusercontent.com/5641681/100539644-2f6a8700-3238-11eb-85d3-5db59eb6145d.png)

What do you think about all of this?

P.D. Just realized there seems to be an action missing on presets 3 and 4, where the arrow that points towards both L2 and R2 should have the "Look back" action.

EDIT: Whoops, now I realized that the L3 action isn't properly placed in the customized arrow positions version.

**Comment by Sergeanur** [comment]
Nice job, mate, I really like it! We would certainly need to reposition text in code so it would look sane, though we may end up moving arrows a bit too in case repositioned texts end up overlapping each other. Btw not sure if you know, but there's 4 sets of arrows in frontend.txd the game is using.

**Comment by IlDucci** [comment]
> Btw not sure if you know, but there's 4 sets of arrows in frontend.txd the game is using.

I know, I've made them all. It's just that I wanted to be sure on what's the way you guys want to proceed so I know what to do with other controller schemes.

**Comment by IlDucci** [comment]
So I've ended up using custom positions per controller. Today I've went with XBOX ONE and DS3 (this last one is basically a recreation of the original controller, as its color palette was crushed because the original was just 16 colors).

![fe_controller_xboxone](https://user-images.githubusercontent.com/5641681/100649320-94120880-3342-11eb-8941-06b7d925654d.png)
![fe_controller_dualshock3](https://user-images.githubusercontent.com/5641681/100649328-96746280-3342-11eb-9d65-0adf8b368214.png)

So the last one for now would be the DS4. Please tell me if I should stop or go on with other controllers.

**Comment by hazelnot** [comment]
I'd maybe remove the Xbox logo from the Xbox controller, cause we're _probably_ not allowed to use it

**Comment by IlDucci** [comment]
> 
> 
> I'd maybe remove the Xbox logo from the Xbox controller, cause we're _probably_ not allowed to use it. I love the graphics though.

Gotcha. Here's a version with the "logo" devolved like in the 360 controller.

![fe_controller_xboxone](https://user-images.githubusercontent.com/5641681/100673422-b700e480-3363-11eb-8c32-a46c4ba445f1.png)

**Comment by IlDucci** [comment]
And lastly, here's the DualShock4:
![fe_controller_dualshock4](https://user-images.githubusercontent.com/5641681/100742250-c5d6ae00-33da-11eb-8328-061c5d058de9.png)

If the feedback is good and you guys give me the go, I'll upload the sources and materials.

**Comment by IlDucci** [comment]
Here you go, ladies and gentlemen. If there's any other controller graphics things I can help with, please comment them and I'll get with them when I have some free time.
[GTA3Controllers.zip](https://github.com/GTAmodding/re3/files/5655219/GTA3Controllers.zip)
