### ISSUE TITLE
All vehicles behave as if max LOD was applied (low poly, close to no spawns)

### ISSUE THREAD

**Issue by marysiamzawka** [GTAmodding/re3#858]
This issue occurs as of version 1.0.3458 (appveyor artifact), both dx9 and ogl builds.

Vehicles appear as if you were very far away from them (low poly models). This applies to all drivable cars, but not any other models.
There are no set spawns, other than those spawned by mission script.
There may be traffic spawns outside of your view, but they will despawn the second they come into view.

[Video](https://www.youtube.com/watch?v=xIuY1dJmd5o)

**Comment by aap** [comment]
fixed now. apparently my cam fix was bad.
