### ISSUE TITLE
Attempting to remotely enter a boat (eg. from a dock) only warps you to the driver seat

### ISSUE THREAD

**Issue by marysiamzawka** [GTAmodding/re3#864]
Occurs as of version 1.0.3493 (3c245059)

# Expected behavior (vanilla game)
When entering a boat remotely (from a dock), you're warped to the driver's seat, sat in it, and given control of the boat after a second.

# Actual behavior
When entering a boat remotely, you're only warped to the driver's seat. You have to press "Enter vehicle" again to be sat in the seat and take control.

**Comment by erorcun** [comment]
Can't reproduce, might be fixed along the way.

**Comment by erorcun** [comment]
Actually it looked like an original bug that's fixed in VC, so I copied some code from VC and now it's working ok.
