### ISSUE TITLE
ANCHOR_BOAT command condition

### ISSUE THREAD

**Issue by x87** [GTAmodding/re3#866]
https://github.com/GTAmodding/re3/blob/56c471d02e1c704202f809de7f3d179c98ae121f/src/control/Script4.cpp#L92

It looks like the condition should be inverted?

**Comment by Nick007J** [comment]
You are right, thanks, fixed in https://github.com/GTAmodding/re3/commit/efb28b888d4ed89e1f8fc770a66ddfd7e03f4942
