### ISSUE TITLE
[miami] Sound doesn't work in miami on ubuntu 20.04

### ISSUE THREAD

**Issue by DJs3000** [GTAmodding/re3#878]
There is no sound in Ubuntu 20.04. In re3, the sound works perfectly.
see the screenshot
![scr_2020-12-14_03-25-55](https://user-images.githubusercontent.com/16526540/102028726-a2d5d200-3dbc-11eb-9f03-104f5de39086.png)

**Comment by DJs3000** [comment]
now the sound doesn't work in re3 either.
![scr_2020-12-14_03-42-50](https://user-images.githubusercontent.com/16526540/102029240-baae5580-3dbe-11eb-8264-c571383e78a8.png)

**Comment by DJs3000** [comment]
I use a sound card "Sound BlasterX AE-5". The sound in the system works perfectly, maybe some library is missing.

**Comment by ShFil119** [comment]
reVC isn't finished yet and can be missing fixes and improvements. As workaround you can rename `Audio` directory of gamefiles to `audio`.

**Comment by DJs3000** [comment]
Excuse me. I didn't close the Internet browser, which was the problem.
