### ISSUE TITLE
COMMAND_IS_CAR_PASSENGER_SEAT_FREE

### ISSUE THREAD

**Issue by x87** [GTAmodding/re3#881]
https://github.com/GTAmodding/re3/blob/d6b5672e38694e26ff761049708d848d2f19455b/src/control/Script6.cpp#L548

`COMMAND_IS_CAR_PASSENGER_SEAT_FREE` does exist in GTA 3. Is this intentional that it has not been implemented in re3?

**Comment by ShFil119** [comment]
fixed
