### ISSUE TITLE
Peds become suicidal after they notice a dead ped in water.

### ISSUE THREAD

**Issue by CoderReece** [GTAmodding/re3#892]
No video or screenshots but if you make the ped(s) dive off the map into the water with a speeding car in a decently populated area, peds will constantly run into the water and die over and over again.

Edit: Sometimes peds just willingly walk off into the water. This is near the safehouse area just after the very first mission.

I don't know if this is a vanilla glitch because I've never seen it before.

**Comment by erorcun** [comment]
I checked the code and there was nothing to prevent peds to investigate dead peds in the water, so yeah it looks like vanilla bug and should be fixed now
