### ISSUE TITLE
Cleo compatibilty

### ISSUE THREAD

**Issue by strikersix23** [GTAmodding/re3#896]
Is it possible to load some basic mods with cleo or have a modified cleo opcodes to work with re3/revc

**Comment by asm95** [comment]
CLEO expects the original game executable file. `re3` has a totally different structure which would make CLEO crashes. But it's not impossible to support CLEO as `re3` is also open.

However, some CLEO mods themselves also expects the original game executable, thus this requires also an effort from both CLEO developers and mods authors.

This is not a bug, not a planned feature.

**Comment by strikersix23** [comment]
As i figured it would be extensive to do it i understand thanks for the information. The only reason i wanted to know the is i like to use blinkers and brake lights in my gta games and that is it i dont know if you would be able to allow this and possible headlight adjustment such as distant and normal range.

**Comment by strikersix23** [comment]
I am very happy you guys are back

**Comment by x87** [comment]
https://re.cleo.li/
