### ISSUE TITLE
Keyboard layout is english (QWERTY) only

### ISSUE THREAD

**Issue by ttyborg** [GTAmodding/re3#898]
Hi!

I am on Manjaro Linux (don't know if it matters), and the issue is, re3 always assumes english (probably US) keyboard layout.
This is most notable when remapping controls or using cheats, as some non-english layouts have letters in different positions.
Tried it in the original game on Steam through the Proton compatibility layer, and it picked up my non-english layout prefectly.

Happens on both re3 and reVC.

**Comment by ShFil119** [comment]
Maybe it's your desktop environment switching layout. I would try to get rid off any other layout than which you want (should be somewhere in setting).

**Comment by ttyborg** [comment]
@ShFil119 Just checked, as you suggested, and I have no other layouts installed, just my native one. Also tried to use LC_ALL to force my locale, as I had a similar issue a few years back in another game, Kerbal Space Program.

**Comment by ShFil119** [comment]
Can you also try build with opengl via wine?

(here all available binaries https://github.com/GTAmodding/re3/runs/1609208106 )

**Comment by ttyborg** [comment]
Okay, I tried to run all of them, but only one worked. It was re3_Debug_win-x86-librw_d3d9-mss, all others either hanged, or straight up crashed, but I can confirm, the one that worked, picked up my layout perfectly.

**Comment by ttyborg** [comment]
Sorry, I made a silly mistake. When I tried to run some of the binaries through wine, I was in a different folder in terminal. So, the ones that were hanging are now running as well.
In the end, I could run these:

re3_Release_win-x86-librw_gl3_glfw-mss
re3_Release_win-x86-librw_d3d9-mss
re3_Debug_win-x86-librw_d3d9-mss

What's interesting is, only the opengl version did not catch my layout, both dx version got it right.

**Comment by erorcun** [comment]
this is a restriction of glfw library and we don't have anything to do in near future, sorry :/
explanation:
to properly implement case insensitive path finding we had to do
```
setlocale(LC_CTYPE, "C");
setlocale(LC_COLLATE, "C");
```
but even if we remove those (which I can't, removing those makes game immediately crash on me) we're not sure if we will get GLFW_KEY_PERIOD on correct key, which probably not according to GLFW documentation

**Comment by ttyborg** [comment]
I see, thank you for taking a look at it.
I found something else, that maybe related, I don't know if I should open a new ticket for it, it's just a minor thing.
I cannot delete save files in the Linux build, it goes through without any ingame error message, but it's still in the list, when I run a Win binary with Wine, it can delete the saves file just fine.
I get these messages in the terminal, when I run the Linux binary and open the save games list:

casepath couldn't find dir/file "GTA3sf2.b", full path was userfiles\GTA3sf2.b
casepath couldn't find dir/file "GTA3sf3.b", full path was userfiles\GTA3sf3.b
casepath couldn't find dir/file "GTA3sf4.b", full path was userfiles\GTA3sf4.b
casepath couldn't find dir/file "GTA3sf6.b", full path was userfiles\GTA3sf6.b
casepath couldn't find dir/file "GTA3sf7.b", full path was userfiles\GTA3sf7.b
casepath couldn't find dir/file "GTA3sf8.b", full path was userfiles\GTA3sf8.b

In this case, the 1st and the 5th save slots are used. Using the Win binary, I don't get these messages.
Save games are loading fine, and can overwrite them with new saves.

**Comment by erorcun** [comment]
Just wanted to do say: this is now fixed :)

**Comment by ttyborg** [comment]
Nice, thanks! :)
