### ISSUE TITLE
On foot and in car controls "tied together"

### ISSUE THREAD

**Issue by ttyborg** [GTAmodding/re3#899]
Hi!

I wanted to remap controls to use some modern, GTA4 & 5 style controls, both "on foot" and "in cars" using a controller.
Tried to remap right trigger to "fire" on foot, and I also wanted to use it for "forward" in car, but only one of them is allowed to be used, even though, they are in separate categories.

This also happens with mouse and keyboard, and in the original release as well.

**Comment by erorcun** [comment]
yeah, but this is only a case in Fire. We solved it via implementing BIND_VEHICLE_FIREWEAPON, but it changes gta3.set (settings file) structure, so we can't enable it by default. You can enable it if you build game yourself though.
