### ISSUE TITLE
Some gravity problems while driving with PCJ-600 Bike

### ISSUE THREAD

**Issue by Achilleas117** [GTAmodding/re3#900]
![GTA_ Vice City 26_12_2020 10_25_23 πμ](https://user-images.githubusercontent.com/76263103/103148090-bf7eec00-4764-11eb-90cb-6f58237c3a71.png)
![GTA_ Vice City 26_12_2020 10_25_25 πμ](https://user-images.githubusercontent.com/76263103/103148094-c443a000-4764-11eb-8546-7b1f80735dd9.png)

I have some bugs with the PCJ-600 bike. First it has some gravity issues and second he takes again the bike but upside down and then he fells down from the bike and i can't drive with it now. I hope they will fix this problem.

**Comment by Calinou** [comment]
@Achilleas117 Did you find a solution to this problem?

**Comment by Achilleas117** [comment]
@Calinou OK. But they fixed it. I use the reVC version.
