### ISSUE TITLE
Lack of subtitles' shadows in cutscenes

### ISSUE THREAD

**Issue by Tomasak** [GTAmodding/re3#901]
Cutscene subtitles dont have shadows. (With borders off, with borders on, they dont obviously need em)
![Grand Theft Auto Vice City Screenshot 2020 12 26 - 12 41 57 24](https://user-images.githubusercontent.com/11007651/103150834-22c64980-4778-11eb-89a8-ab5f4c0cfa88.png)
![Grand Theft Auto Vice City Screenshot 2020 12 26 - 12 41 16 73](https://user-images.githubusercontent.com/11007651/103150838-26f26700-4778-11eb-8e29-a9dd3739990d.png)

**Comment by Sergeanur** [comment]
Fixed
