### ISSUE TITLE
[miami] Motorcycle wheelie distance always gives 0.0m

### ISSUE THREAD

**Issue by ttyborg** [GTAmodding/re3#903]
Motorcycle tricks, like wheelies and stoppies always give me 0.0m.

On the attached screenshot I did a wheelie across Ocean Beach.

![Screenshot_20201227_213033](https://user-images.githubusercontent.com/4703391/103181465-839d7100-48a1-11eb-8c08-fb6a7f8d173c.png)

Jump stunts on ramps are giving correct values.

![Screenshot_20201228_001203](https://user-images.githubusercontent.com/4703391/103181467-88622500-48a1-11eb-90ba-a054d1ab4e9c.png)

It also feels like, doing a wheelie is way easier and doing a stoppie is way harder, than in the original release.
If I have enough momentum, I can just hold down the "lean down" button, release the "forward" button, and the wheelie locks into place (at least for the PCJ600 and the Sanchez) until the bike slows down too much, while in the original I have to make corrections constantly.

**Comment by ShFil119** [comment]
Can you recheck now?

**Comment by ttyborg** [comment]
Yes, it is fixed now. Thanks!
