### ISSUE TITLE
Water droplet effect stops working, when looking away in vehicles

### ISSUE THREAD

**Issue by ttyborg** [GTAmodding/re3#906]
Water droplet effect stops working, when looking to the sides or behind, in vehicles.

Droplets stop in place and slowly disappear, then no additional droplet appears on the screen, until releasing the "look left/right/behind" buttons. 

On foot it works, however, the trailing effect of the droplets stops working, when running towards the camera.

Both in re3 and reVC.

**Comment by aap** [comment]
this should be original behaviour. in the code we have this:
```
	ms_enabled = !isTopDown && !isLookingInDirection;
	ms_movingEnabled = !isTopDown && !isLookingInDirection;
```

**Comment by ttyborg** [comment]
Ah, okay. I thought there was something wrong, because in the originals (at least in VC) it worked no matter if looked to the sides or behind.

**Comment by aap** [comment]
hm, i took the code mostly from III. can you check that maybe?

**Comment by ThirteenAG** [comment]
It should work, there's an error.
https://www.youtube.com/watch?v=VTEJdDJmq4w&hd=1

**Comment by aap** [comment]
fixed. was missing condition
