### ISSUE TITLE
Occasional input delay using keyboard

### ISSUE THREAD

**Issue by ttyborg** [GTAmodding/re3#912]
Hello everyone, Happy New Year!

I have been noticing an somewhat rarely happening input delay, while using keyboard controls (well, at least I couldn't reproduce it using a controller to a noticeable degree).

It happens on foot and in every type of vehicles, both in re3 and in reVC.

It's a bit odd, because it's not the same for every action and there's even a slight difference between re3 and VC, as well.

I have the most issues with VC, regarding this, as when there is a delay on the forward action(using "W" key), while inside a vehicle, it straight up locks up the action for that button(so, while I am holding "W", I can use the secondary "Up arrow" to go forward), until I release the button, after that "W" is working again. Other keys behave differently, as in, they just have a slight delay, a fraction of second (maybe 200ms), but they don't lock up.

I made a video for demonstration, in it you can see two examples of the bug happening, while intentionally driving wrong. 
I put a keyboard overlay in the video, so you can see what I am doing on the keyboard. Also there's a red square shown, when the delay is happening, it will be over the mini map.

The first was a missed right turn, around 34s, and it lasted for 200ms.
The second is around 40s, and you can see it lasts as long as I am holding the button (in this case 10s). Everything else is working, just the "W" locked up.

https://youtu.be/ska3XU7ANcU

I think this is probably an issue, specific to the Linux build, because I tried to run some of the auto-built Win binaries in Wine, and I could not reproduce this behavior.

Hope this helps.

Sorry for the lengthy post.

I am on Manjaro KDE 20.2 64bit, c74c7ce was the last commit when I built reVC.

**Comment by aap** [comment]
I can confirm this, but I was never able to even get some reproducible test case.

**Comment by ttyborg** [comment]
I can reproduce it with just standing still in a car and repeatedly switching between turn left-turn right, but it's still not very consistent.

**Comment by erorcun** [comment]
hi, thank you for the report.

as an attempt to fix it i did this today: https://github.com/GTAmodding/re3/commit/8846f50cb7df6eb05df9dc7fe5208120febcb016
can you try it again?

**Comment by ttyborg** [comment]
Just tested both re3 and miami, the bug is still present.

**Comment by erorcun** [comment]
ah ok, thanks.

**Comment by erorcun** [comment]
hi, can you try this again please? now we get keyboard input directly from X11.

**Comment by ttyborg** [comment]
Hi!
I tried it, and it seems to me, it's fixed.
Thank you very much!
