### ISSUE TITLE
Crash before playing the mission ''Death Row''

### ISSUE THREAD

**Issue by Achilleas117** [GTAmodding/re3#919]
I have the latest version of the re3, the miami branch as of 3/1/2021, running on Windows 10 and i started the mission ''Death Row'' and after i skipped the cutscene, appeared the objective for a while and then the game crashes before playing this mission. Here's a screenshot:
![RE3 Assertion Failed! 3_1_2021 11_43_43 πμ](https://user-images.githubusercontent.com/76263103/103475798-187bff00-4db9-11eb-8a30-ea66e1f153cd.png)

**Comment by Nick007J** [comment]
fixed by https://github.com/GTAmodding/re3/commit/29e0cfa98bb09361e3a3d051d5cf2c5a7328108f
