### ISSUE TITLE
Sentinel bumper bar is being transparent.

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#92]
GTA3:

![](https://cdn.discordapp.com/attachments/582894364737404963/595748997801574400/unknown.png)
RE3:

![](https://cdn.discordapp.com/attachments/582894364737404963/595747788738920448/unknown.png)

You can see that the bumper shiny bar is totally transparent in re3 you can see you'r under car body through it.

**Comment by aap** [comment]
fixed by ecf29b7769711fb4aebbe7ed6a441cd2bc7b881d
