### ISSUE TITLE
How to run reLCS?

### ISSUE THREAD

**Issue by ttyborg** [GTAmodding/re3#950]
I've compiled reLCS on Linux, and trying to run it, but I get some errors.

```bash
cdvd_stream: can't get filesystem info

RE3 ASSERT FAILED
        File: ../src/core/CdStreamPosix.cpp
        Line: 151
        Function: CdStreamInit
        Expression: 0
reLCS_debug_amd64_55320a0: ../src/core/re3.cpp:835: void re3_assert(const char*, const char*, unsigned int, const char*): Assertion `false' failed.
Félbeszakítva (core készült)
```

I tried to use the PAL PS2 version, do I have to use some other one, or do I have to do something to the file/directory structure?

Thanks in advance for your help.

**Comment by aap** [comment]
you can't run from any released game directly yet. i have prepared an archive that we use for testing, but i don't think i want to link to it publicly here because it contains most of the game. check the discord server

**Comment by ttyborg** [comment]
Ah, okay.
Thanks.
