### ISSUE TITLE
bug with radio switching 

### ISSUE THREAD

**Issue by majesticCoding** [GTAmodding/re3#958]
Sometimes it's possible to observe that the same radio is playing despite the fact you've switched to other stations

**Comment by erorcun** [comment]
vanilla tag? happens in vanilla too?

**Comment by majesticCoding** [comment]
> vanilla tag? happens in vanilla too?

yes

**Comment by erorcun** [comment]
I think this is fixed now on VC.

**Comment by erorcun** [comment]
I think fixed on III too.
