### ISSUE TITLE
Cops slow motion

### ISSUE THREAD

**Issue by Noskillx** [GTAmodding/re3#96]
Cops which chease you at one star wanted level run towards you in slow motion like you'd take adrenaline pill, everything else is not in slowmotion just the cop.
![image](https://user-images.githubusercontent.com/30195961/60552562-9af0b200-9d2f-11e9-9cdb-ff144a61761d.png)

**Comment by aap** [comment]
should be fixed by d62c6165459048c1a616d0e056e25e366b09c505
