### ISSUE TITLE
glfw controller config not fully loading on start

### ISSUE THREAD

**Issue by ZLau92** [GTAmodding/re3#985]
Affects iii, miami, lcs
When I load a game, the attack, radio, and handbrake buttons do not work on gamepad (tested with both xbox & ps3 controllers).
If I do a "restore defaults" in the control settings, all bindings are fixed.... But if I kill and restart, the issue persists.

Perhaps also worth noting that if I delete re.ini, all controls bind correctly on first load. But another kill & restart, and those controls unbind once more.

I'm thinking that something borked is being saved to the ini.

Running linux, in case that's helpful to know.

**Comment by erorcun** [comment]
thank you for the report, can you check what is last joy button initalized in bindings? i mean after you restore defaults, look at redefine controls table and check what is the "joy" binding with largest number (it's usually 16)

**Comment by ZLau92** [comment]
Yes, 16 is correct
`GO_LEFT = kbd:LEFT,2ndKbd:A,joy:16`

**Comment by erorcun** [comment]
fixed: https://github.com/GTAmodding/re3/commit/b728f8de6473409295a551507d16c20109413121, thank you
