### ISSUE TITLE
Keyboard controls don't recognize a held key

### ISSUE THREAD

**Issue by edricgarran** [GTAmodding/re3#993]
When I hold down WASD/arrows to move, re3 only recognizes the keypress briefly, and stops moving almost immediately, so I need to keep mashing the movement keys to walk.

Also tried playing with a controller (8bitdo SN30 pro) and the buttons are all acting random, and the camera spins around while the controller is connected.

**Comment by erorcun** [comment]
> When I hold down WASD/arrows to move, re3 only recognizes the keypress briefly, and stops moving almost immediately, so I need to keep mashing the movement keys to walk.

What? Sorry, I've never heard/experienced that before, so I doubt I can help but you can start by telling your OS.

> Also tried playing with a controller (8bitdo SN30 pro) and the buttons are all acting random, and the camera spins around while the controller is connected.

Yeah this is expected among games utilizing SDL/GLFW. I've recently heard that tool: https://www.generalarcade.com/gamepadtool/ Probably we should add this to readme.  

You can create your own mapping with that and set it as environment variable, or export to file(and move to gta3 root folder), we support both.

**Comment by edricgarran** [comment]
Sorry, I thought I had mentioned my OS, but didn't. I'm on Arch linux.
Made a video showing the issue, I hope it makes it clearer: https://imgur.com/a/0xnJUKT
Also noticed that if I jump without holding a direction, the game jumps in the direction of the last key I pressed, as if I was still holding it down.

**Comment by edricgarran** [comment]
I found out what the issue was, it was just a weirdness in my setup causing a double key repeat, not a bug in the engine.
